### ISSUE TITLE
Cannot write to BigQuery from within Databricks Spark (read is ok)

### ISSUE THREAD

**Issue by vasco-abreu** [GoogleCloudDataproc/spark-bigquery-connector#1003]
I am successful in **reading** data using `spark-bigquery-connector` however, using the exact same credentials, service account and project within GCP, while trying to **write** data to BigQuery, using a piece of code such as:

```
from pyspark.sql.types import StructType, StructField, StringType
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

spark.conf.set("credentialsFile", "<my-file-location>")
spark.conf.set("parentProject", "<my-parent-project>")

data = [
    ('a', 'b'),
    ('aa', 'bb'),
    (None, None),
]

schema = StructType([
    StructField("a", StringType(), True),
    StructField("b", StringType(), True)
])

data_df = spark.createDataFrame(data=data, schema=schema)

data_df \\
    .write \\
    .format("com.google.cloud.spark.bigquery") \\
    .option("temporaryGcsBucket","<my-bucket>") \\
    .mode("overwrite") \\
    .save("test_dataset.test_table")

```

I am facing the following error:

```
Py4JJavaError: An error occurred while calling o2389.save.
: java.io.IOException: Error getting access token from metadata server at: <http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token>

```

Caused by this:

```
Caused by: shaded.databricks.com.google.api.client.http.HttpResponseException: 404 Not Found
GET <http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token>
<?xml version="1.0" encoding="utf-8"?>
<Error xmlns:xsi="<http://www.w3.org/2001/XMLSchema-instance>" xmlns:xsd="<http://www.w3.org/2001/XMLSchema>">
    <Code>ResourceNotFound</Code>
    <Message>The specified resource does not exist.</Message>
    <Details>'computeMetadata' isn't a valid resource name.</Details>
</Error>

```

I am on Azure Databricks, having installed the Maven package with following coordinates:
`com.google.cloud.spark:spark-3.3-bigquery:0.31.1`

Running on a cluster with following specs:
Databricks Runtime Version - `11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)`
Python version - `Python 3.9.5`

Do you recognise this pattern as something observed previously?

Any help with this issue is welcome!

**Comment by davidrabinowitz** [comment]
Is your databricks cluster running on the Google cloud platform?

**Comment by vasco-abreu** [comment]
Hi @davidrabinowitz, thanks for checking by!
No, it is on Azure.

**Comment by vasco-abreu** [comment]
Should it then be concluded that while using `spark-bigquery-connector` it is...

GCP:
 - Possible to read data from BigQuery
 - Possible to write data to BigQuery

Other cloud providers:
- Possible to read data from BigQuery
- Not possible to write data to BigQuery due to the issue with `computeMetadata` resource url not available

?

**Comment by davidrabinowitz** [comment]
Attaching the full stack trace will help, but my guess is that the GCS connector is not well configured, failing to write to the intermediate bucket. Have you tried the DIRECT writeMethod?

**Comment by vasco-abreu** [comment]
In fact I wanted to perform DIRECT write originally but I was getting this error:
`IllegalArgumentException: Temporary or persistent GCS bucket must be informed.`
while attempting something such as:
```
data_df \
    .write \
    .format("com.google.cloud.spark.bigquery") \
    .option("writeMethod", "direct") \
    .mode("overwrite") \
    .save("test_dataset.test_table")
```

Having faced this roadblock, then I moved to try the INDIRECT method with `temporaryGcsBucket` and got stuck in the error originally posted.


This is the full stack trace:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1713790960533025> in <cell line: 31>()
     29 data_df = spark.createDataFrame(data=data, schema=schema)
     30 
---> 31 data_df \
     32     .write \
     33     .format("com.google.cloud.spark.bigquery") \

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    966             self._jwrite.save()
    967         else:
--> 968             self._jwrite.save(path)
    969 
    970     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1319 
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    194     def deco(*a: Any, **kw: Any) -> Any:
    195         try:
--> 196             return f(*a, **kw)
    197         except Py4JJavaError as e:
    198             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o726.save.
: java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
	at shaded.databricks.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:250)
	at shaded.databricks.com.google.cloud.hadoop.util.CredentialFactory.getCredential(CredentialFactory.java:389)
	at shaded.databricks.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1561)
	at shaded.databricks.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1700)
	at shaded.databricks.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1684)
	at shaded.databricks.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:482)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:537)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.<init>(BigQueryWriteHelper.scala:63)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:116)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:78)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:89)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:229)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:243)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:392)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:188)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:342)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:229)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:214)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:227)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:220)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:99)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:298)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:294)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:220)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:354)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:220)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:174)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:165)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:256)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:965)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:430)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:397)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
Caused by: shaded.databricks.com.google.api.client.http.HttpResponseException: 404 Not Found
GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
<?xml version="1.0" encoding="utf-8"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Code>ResourceNotFound</Code>
    <Message>The specified resource does not exist.</Message>
    <Details>'computeMetadata' isn't a valid resource name.</Details>
</Error>
	at shaded.databricks.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
	at shaded.databricks.com.google.cloud.hadoop.util.CredentialFactory$ComputeCredentialWithRetry.executeRefreshToken(CredentialFactory.java:192)
	at shaded.databricks.com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:494)
	at shaded.databricks.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:247)
	... 57 more
```

**Comment by vasco-abreu** [comment]
@davidrabinowitz have you had the opportunity to see my last comment?

**Comment by MarcBarreiro** [comment]
Hi, have you found a solution?

I'm reading data from Big Query using a JSON file with credentials associated to a service account. I want to process this data and write it back to BigQuery. There's no problem when I read, but when I try to write:

```
(
    final_df.write.format("bigquery") 
    .mode("overwrite")
    .option("credentialsFile", <<path_to_my_json_credentials_file>>)
    .option("parentProject", google_project)
    .option("temporaryGcsBucket", temporary_bucket)
    .option("table", target_table)
    .save()
)
```
where the variable target_table is a table that I've been able to create like this:

```
credentials = service_account.Credentials.from_service_account_file(
    <<path_to_my_json_credentials_file>>,
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
)

google_project = <<project>>
google_dataset = <<google_dataset>>
table_name = <<table_name>>
target_table = f"{google_project}.{google_dataset}.{table_name}"
temporary_bucket = <<temporary_bucket>>

# Create client
client = bigquery.Client(credentials=credentials, project=google_project,)

schema = [
    bigquery.SchemaField("column1", "STRING"),
    bigquery.SchemaField("column2", "STRING"),
]

bigquery_table = client.create_table(bigquery.Table(target_table, schema=schema))  # Make an API request.
```

This code creates an empty table with the specified schema. I know this table has been created because I can read it and it's an empty table with the correct schema, as expected.

But I'm getting this error when I try to write data into it (different from your error):

```
Py4JJavaError: An error occurred while calling o8528.save.
: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:93)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:116)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:96)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:259)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:211)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:167)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:166)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:1080)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:156)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:299)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:130)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:249)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:1080)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:469)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:439)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2197)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.databricks.sql.transaction.tahoe.DeltaTableUtils$.findDeltaTableRoot(DeltaTable.scala:175)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.validateNonDeltaWrite(DeltaValidation.scala:191)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:336)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:304)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:88)
	... 35 more
Caused by: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	... 44 more
```
Before trying this I was getting the error:

`java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found`

And what I did was setting the spark session configuration in my cluster like this:

```
fs.AbstractFileSystem.gs.impl com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
fs.gs.impl com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
google.cloud.auth.service.account.enable true
```

The error now has changed and says: `java.lang.RuntimeException: Failed to write to BigQuery` but there's still this `Caused by: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found`. Any idea of what's going on?

I am on Azure Databricks, having installed the Maven .jar package:
"spark_bigquery_with_dependencies_2_12_0_26_0.jar"

Running on a cluster with following specs:
Databricks Runtime Version - 9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)
Python version - Python 3.8.10

Any help would be appreciated!

**Comment by tamannareports** [comment]
I haven't found a solution to my issue yet, no..

**Comment by vasco-abreu** [comment]
I haven't found a solution to my issue yet, no..
