### ISSUE TITLE
'UnknownException' in 0.31.1 (Works fine in 0.28.0)

### ISSUE THREAD

**Issue by david-royo-db** [GoogleCloudDataproc/spark-bigquery-connector#1009]
Hi,

We upgraded our config to use the latest 0.31.1 version of the connector and all our spark jobs started failing with the same problem. Stack trace at the bottom.

Something interesting we observed is **writing data to BigQuery is ok** and our save steps just end ok. Reading data from BigQuery **fails only partially**:
- It saves the query into our temp dataset just fine (We can even query the query result table)
- It fails in a very cryptic way when transmitting the data back to spark (See stacktrace below)

This happens in Dataproc 2.0 and 2.1 (We initially thought our upgrade to 2.1 was the problem but the 0.28.0 version works perfectly fine with Dataproc 2.1)

Our uber jar doesn't include any com.google.cloud.spark classes, the jar is injected in the list of jars passed to dataproc when running the job.

This is the error that the connector writes to the output using 0.31.1. You can see the very simple query there (Redacted to mask our project/schema) but ANY query shows the same behaviour.

`23/06/30 10:24:38 INFO DirectBigQueryRelation: |Querying table our-project-redacted.temp._bqc_146a9d49d9c44ffc97f16633c2fbeb37, parameters sent from Spark:|requiredColumns=[a,b,c,d],|filters=[IsNotNull(b),GreaterThan(b,0)]
23/06/30 10:24:39 ERROR LoadJob: Spark Job Logger: LoadJob finished with errors: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
23/06/30 10:24:39 ERROR LoadJob: Unexpected exception thrown during the job execution: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]`

Full stack trace below

```
Exception in thread "main" com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnknownException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:119)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryReadClient.createReadSession(BigQueryReadClient.java:232)
		at com.google.cloud.bigquery.connector.common.ReadSessionCreator.create(ReadSessionCreator.java:136)
		at com.google.cloud.spark.bigquery.direct.BigQueryRDDFactory.createRddFromTable(BigQueryRDDFactory.java:138)
		at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.java:139)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$apply$4(DataSourceStrategy.scala:328)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:362)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:441)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:361)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:328)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
		at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:461)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:145)
		at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
		at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:512)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:185)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
		at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:184)
		at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:145)
		at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:138)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:158)
		at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
		at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:512)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:185)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
		at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:184)
		at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:158)
		at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:151)
		at org.apache.spark.sql.execution.columnar.InMemoryRelation$.apply(InMemoryRelation.scala:326)
		at org.apache.spark.sql.execution.CacheManager.$anonfun$cacheQuery$2(CacheManager.scala:124)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
		at org.apache.spark.sql.execution.CacheManager.cacheQuery(CacheManager.scala:119)
		at org.apache.spark.sql.execution.CacheManager.cacheQuery(CacheManager.scala:92)
		at org.apache.spark.sql.Dataset.persist(Dataset.scala:3320)
		at org.apache.spark.sql.Dataset.cache(Dataset.scala:3330)
		... our internal classes go here ...	
		at scala.Function0.apply$mcV$sp(Function0.scala:39)
		at scala.Function0.apply$mcV$sp$(Function0.scala:39)
		at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
		at scala.App.$anonfun$main$1$adapted(App.scala:80)
		at scala.collection.immutable.List.foreach(List.scala:431)
		at scala.App.main(App.scala:80)
		at scala.App.main$(App.scala:78)
		... our internal classes go here..
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:539)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SupportedGroupsExtension$SupportedGroups
	at java.base/sun.security.ssl.HandshakeContext.isActivatable(HandshakeContext.java:518)
	at java.base/sun.security.ssl.HandshakeContext.getActiveProtocols(HandshakeContext.java:289)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:167)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:229)
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:103)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.handler.ssl.JdkSslEngine.beginHandshake(JdkSslEngine.java:158)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:2098)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:2015)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.handler.ssl.SslHandler.handlerAdded(SslHandler.java:1997)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:269)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.handlerAdded0(ProtocolNegotiators.java:603)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.handlerAdded(ProtocolNegotiators.java:1048)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:572)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:515)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.fireProtocolNegotiationEvent(ProtocolNegotiators.java:1089)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.ProtocolNegotiators$WaitUntilActiveHandler.channelActive(ProtocolNegotiators.java:994)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more```

**Comment by davidrabinowitz** [comment]
Please notice that Dataproc 2.1 arrives with built in Spark BigQuery connector version 0.28.1. Adding an additional connector  will cause conflicting versions of netty. 

Can you please add the stack trace from image 2.0?

**Comment by david-royo-db** [comment]
Oh so we can assume the bigquery connector is a dependency which is updated together with the dataproc versions now? I mean that's nice, but it'd be nicer if it was described [here](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.1)

Thanks! 

Unfortunately I don't have the stack trace for Dataproc 2.0 but for what you said I have the suspicion that we tested that combination in a wrong way

**Comment by isha97** [comment]
Hi @david-royo-db The Dataproc 2.1 image comes with the connector. It's documented here https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/README.md#specifying-the--spark-bigquery-connector-version-in-a-dataproc-cluster
Please open a new issue if you face any error with 2.0 image.
