### ISSUE TITLE
[Error]Invalid dataset ID \"<dataset>\". Dataset IDs must be alphanumeric

### ISSUE THREAD

**Issue by kumar2901** [GoogleCloudDataproc/spark-bigquery-connector#1014]
Hi Team,

I am trying to pass query to bigquery using spark(Java11)
```
spark verison:2.12
Java : 11
```

String jarPackage= "com. google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.23.2"
String query="select * from `bigquery-public-data.stackoverflow.posts_questions` limit 10";
```
sparkSession.read()
                .format("com.google.cloud.spark.bigquery")
                .option("spark.jars.packages", jarPackage)
                .option("viewsEnabled", true)
                .option("materializationDataset", "<dataset>")
                .option("query", query)
                .load()
```
but getting error 
```
java.lang.IllegalArgumentException: No table has been specified
	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.lambda$from$1(SparkBigQueryConfig.java:122)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.base.Absent.or(Absent.java:60)
	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.from(SparkBigQueryConfig.java:120)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryConfig(BigQueryRelationProvider.scala:139)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:71)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:45)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
```

**Comment by davidrabinowitz** [comment]
Please use the latest version (0.31.1).

**Comment by davidrabinowitz** [comment]
Have you replaced the string `<dataset>` with an actual dataset name that you have writing permissions to ?

**Comment by davidrabinowitz** [comment]
Can you please share the current error? Also, an updated code sample will help
