### ISSUE TITLE
Issues when using the connector with Databricks

### ISSUE THREAD

**Issue by viniciuspnu** [GoogleCloudDataproc/spark-bigquery-connector#1029]
Hello everyone,

I'm trying to use the connector using a Databricks environment using Spark 3.3 (`com.google.cloud.spark:spark-3.3-bigquery:0.32.0`), but when trying to read I'm getting the following error:

```
spark
  .read
  .format("bigquery")
  .load("test_dataset.test_table")

AnalysisException: Multiple sources found for bigquery (com.google.cloud.spark.bigquery.BigQueryRelationProvider, com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider), please specify the fully qualified class name.
```

I'm supposing this is due to Databricks having the Scala based connector already built-in, so I've tried to specify `com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider`:

```
spark
  .read
  .format("com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider")
  .load("test_dataset.test_table")

ArrayStoreException: com.google.cloud.bigquery.connector.common.BigQueryClientModule
	at com.google.cloud.spark.bigquery.InjectorBuilder.build(InjectorBuilder.java:73)
	at com.google.cloud.spark.bigquery.v2.Spark3Util.createBigQueryTableInstance(Spark3Util.java:42)
	at com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider.getBigQueryTableInternal(Spark33BigQueryTableProvider.java:33)
	at com.google.cloud.spark.bigquery.v2.Spark31BigQueryTableProvider.inferSchema(Spark31BigQueryTableProvider.java:40)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:91)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.loadV2Source(DataSourceV2Utils.scala:138)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:333)
	at scala.Option.flatMap(Option.scala:271)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:331)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:240)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(
command-1348282051738379:26)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1348282051738379:83)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1348282051738379:85)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1348282051738379:87)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw$$iw.<init>(command-1348282051738379:89)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw$$iw.<init>(command-1348282051738379:91)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw$$iw.<init>(command-1348282051738379:93)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$$iw.<init>(command-1348282051738379:95)
	at $line63e74b7ce08644ab83df41642eb4397265.$read.<init>(command-1348282051738379:97)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$.<init>(command-1348282051738379:101)
	at $line63e74b7ce08644ab83df41642eb4397265.$read$.<clinit>(command-1348282051738379)
	at $line63e74b7ce08644ab83df41642eb4397265.$eval$.$print$lzycompute(<notebook>:7)
	at $line63e74b7ce08644ab83df41642eb4397265.$eval$.$print(<notebook>:6)
	at $line63e74b7ce08644ab83df41642eb4397265.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:223)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:227)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1271)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:1224)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:227)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$24(DriverLocal.scala:879)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:124)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$21(DriverLocal.scala:862)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:412)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:158)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:410)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:407)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:69)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:455)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:440)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:69)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:839)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:660)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:652)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:571)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:606)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:448)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:389)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:247)
	at java.lang.Thread.run(Thread.java:750)
```

Anyone that were able to use the connector in a Databricks environment can help me?

Thanks in advance.

**Comment by lmatsuura** [comment]
I had a similar issue and what I did was create a [cluster scoped init script](https://docs.databricks.com/clusters/init-scripts.html) that removes the built in library and installs a custom one. The script looks like this:

```
#!/bin/bash

rm -rf /databricks/jars/----ws_3_3--third_party--bigquery-connector--spark-bigquery-connector-*-0.22.2-SNAPSHOT.jar
cp <PATH-TO-THE-JAR-YOU-WANT-TO-INSTALL> /databricks/jars/
```

After that I was able to run `spark.read.format("bigquery")...`.

**Comment by davidrabinowitz** [comment]
Unfortunately two connectors cannot co-exist in the Spark runtime. Please ask Databricks on how to configure the BigQuery connector within their runtime, or remove it and use the Google official published one.

**Comment by mariussoutier** [comment]
I don't understand Databricks' policy of packaging outdated dependencies. The cluster script helped, but the current version is `---ws_3_5--`. Then you can add the current connector via library management or run a fat jar.

**Comment by davidrabinowitz** [comment]
Notice a fat jar wouldn't work, as there will be two connector implementations in the runtime.

**Comment by mariussoutier** [comment]
When removing Databrick's shaded 0.22 JAR it should work, right?

**Comment by davidrabinowitz** [comment]
yes
