### ISSUE TITLE
Getting "wrong column count" error when writing to an existing BigQuery table using `direct` write method

### ISSUE THREAD

**Issue by imrimt** [GoogleCloudDataproc/spark-bigquery-connector#1056]
Relevant used libraries:
Spark version: 3.1.3
Spark core: `org.apache.spark:spark-core_2.12:3.1.3`
Spark BigQuery connector: `com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.29.0@jar`

As the title suggests, I'm unable to write data to an existing BigQuery Table. Here's the error:
```
com.google.cloud.bigquery.connector.common.BigQueryConnectorException: unexpected issue trying to save [string_field: string, array_field: string]
	at com.google.cloud.spark.bigquery.write.BigQueryDataSourceWriterInsertableRelation.insert(BigQueryDataSourceWriterInsertableRelation.java:97)
	at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createRelation(CreatableRelationProviderHelper.java:54)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:107)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
        [...]
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Inserted row has wrong column count; Has 2, expected 1 at [4:30]
```

The data I'm trying to write has one additional column (called `array_field` -- its type is `string`, the name is misleading) as compared to the target BigQuery table, where its schema only has one column called `string_field`.

The Spark code I have is for the write configuration is:
```
    final DataFrameWriter<Row> writer = data.write().format("bigquery")
      .mode(SaveMode.Overwrite)
      .option("project", project)
      .option("parentProject", project)
      .option("writeMethod", "direct");

   // table name is omitted here for security
   writer.save(<qualifed_table_name>);
```

My impression is that `Overwrite` mode should be able to handle this case according to the [official documentation from Google](https://cloud.google.com/bigquery/docs/managing-table-schemas#add_columns_when_you_overwrite_or_append_data), but I'm not sure if the behavior might be different with `direct` write method.

Am I misunderstanding the expected behavior here?

**Comment by imrimt** [comment]
Looks like this is related to #929 , and given the fact that the Spark-BQ write follows streaming semantic, table's schema can't be overwritten.
