### ISSUE TITLE
Dataproc with Cloud Data Fusion is not able to read BigQuery Table

### ISSUE THREAD

**Issue by Ajinkya1788** [GoogleCloudDataproc/spark-bigquery-connector#1068]
Hi,
I am trying to read bigquery table using CDF Scala action plugin. I am using dataproc image version 2.0 and bigquery connector gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar (as suggested in google documentation).

**my code is:**

import io.cdap.cdap.api.spark
import org.apache.spark.sql.SparkSession

Object SparkProgram{
   def main(args:Array[String]): Unit = {
       val spark=SparkSession.builder().appName("SparkAction").getOrCreate()
       val bucket="temp bucket"
       spark.conf.set("temporaryGcsBucket",bucket)
      val test_df=spark.read.format("bigquery").load("project.datatset.table1")
      test_df.write.format("bigquery").mode("append").save("project.datatset.table2")
      
    }
}

**I am getting following error:**
```
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.spark.bigquery.SparkBigQueryConnectorUserAgentProvider.java:51)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$.headerProvider(DirectBigQueryRelation.scala:387)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$.createReadClient(DirectBigQueryRelation.scala:369)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$$anonfun$$lessinit$greater$default$3$1.apply(DirectBigQueryRelation.scala:43)~[na:na]
    at com.google.cloud.spark.bigquery.direct.BigQueryRDD.compute(BigQueryRDD.scala:50)~[na:na]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.scheduler.Task.run(Task.scala:131)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:505)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[na:1.8.0_382]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[na:1.8.0_382]
    at java.lang.Thread.run(Thread.java:750)[na:1.8.0_382]
```

Same plugin and jar I have used to write GCS bucket file into BQ table. But for reading from BQ table, it is and then throwing the error after creating read session.

Thanks

**Comment by davidrabinowitz** [comment]
Just verifying - is the connector version 0.23.2 or 0.32.2 ?

**Comment by Ajinkya1788** [comment]
Hi David, thank you for you reply. I am using connector version 0.23.2. Sharing longer trace. 


2023-09-26- 05:32:30,947 INFO [Driver: c.g.s.b.d.DirectBigqueryRelation@57] = Going to read from project_name.dataset_name.table_name columns=[colA,colB,colC,colD,olE], filter=''
2023-09-26- 05:32:35,297 INFO [Driver: c.g.s.b.d.DirectBigqueryRelation@57] = Created read session for table 'project_name.dataset_name.table_name': projects/CDF_project/location/--/session/--
2023-09-26- 05:32:36,240 - DEBUG [spark-listerner-group-shared i.c.c.a.r.s.AbstractSparkExecutionContext@110] - Spark program=program:location_CDF_Namespace.pipeline_name.SNAPSHOT.spark.phase-1, runId=---------, joiID=0 starts without transaction
2023-09-26- 05:32:36,247 - DEBUG [spark-listerner-group-shared i.c.c.a.r.s.SparkTransactionHandler@110] - Spark job started: JobTransaction(jobId=0, stageIds=[0], transaction=null)
2023-09-26- 05:32:38,510 - ERROR [Executor task launch worker for task 0.0 in stage 0.0 (TID 0):o.a.s.e.Executor@94]- Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.spark.bigquery.SparkBigQueryConnectorUserAgentProvider.java:51)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$.headerProvider(DirectBigQueryRelation.scala:387)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$.createReadClient(DirectBigQueryRelation.scala:369)~[na:na]
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$$anonfun$$lessinit$greater$default$3$1.apply(DirectBigQueryRelation.scala:43)~[na:na]
    at com.google.cloud.spark.bigquery.direct.BigQueryRDD.compute(BigQueryRDD.scala:50)~[na:na]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.scheduler.Task.run(Task.scala:131)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:505)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)~[spark-core_2.12-3.1.3.jar:3.1.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[na:1.8.0_382]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[na:1.8.0_382]
    at java.lang.Thread.run(Thread.java:750)[na:1.8.0_382]
Caused by: java.lang.NullPointerException: null
    at java.util.Properties$LineReader.readLine(Properties.java:434) ~[na:1.8.0_382]
    at java.util.Properties.load0(Properties.java:353) ~[na:1.8.0_382]
    at java.util.Properties.load0(Properties.java:341) ~[na:1.8.0_382]
    at com.google.cloud.spark.bigquery.SparkBigQueryUtil.loadBuildProperties(SparkBigQueryUtil.java.34) ~[na:na]  
    at com.google.cloud.spark.bigquery.SparkBigQueryUtil.<clinit>(SparkBigQueryUtil.java.27) ~[na:na]
        ... 18 common frame omitted

**Comment by isha97** [comment]
@Ajinkya1788 Can you please try this with the latest version of the connector (0.36.1) and check if you are still facing this issue.
