### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Product$class

### ISSUE THREAD

**Issue by chrisbeckett8** [GoogleCloudDataproc/spark-bigquery-connector#107]
When Passing in the parameter parentProject, using: 

df = spark.read.format("bigquery") \
.option('table', 'bigquery-public-data:samples.shakespeare') \
.option('project', 'myproject') \
.option('parentProject', 'myproject') \
.load()

I get this error: 

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-21-989759c77871> in <module>
      2 .option('table', 'bigquery-public-data:samples.shakespeare') \
      3 .option('project', 'myproject') \
----> 4 .option('parentProject', 'myproject') \
      5 .load()
      6 

D:\spark-3.0.0-preview2-bin-hadoop2.7\python\pyspark\sql\readwriter.py in load(self, path, format, schema, **options)
    164             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    165         else:
--> 166             return self._df(self._jreader.load())
    167 
    168     @since(1.4)

D:\spark-3.0.0-preview2-bin-hadoop2.7\python\lib\py4j-0.10.8.1-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1284         answer = self.gateway_client.send_command(command)
   1285         return_value = get_return_value(
-> 1286             answer, self.gateway_client, self.target_id, self.name)
   1287 
   1288         for temp_arg in temp_args:

D:\spark-3.0.0-preview2-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     96     def deco(*a, **kw):
     97         try:
---> 98             return f(*a, **kw)
     99         except py4j.protocol.Py4JJavaError as e:
    100             converted = convert_exception(e.java_exception)

D:\spark-3.0.0-preview2-bin-hadoop2.7\python\lib\py4j-0.10.8.1-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o560.load.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.google.cloud.spark.bigquery.SparkBigQueryOptions.<init>(SparkBigQueryOptions.scala:28)
	at com.google.cloud.spark.bigquery.SparkBigQueryOptions$.apply(SparkBigQueryOptions.scala:105)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryOptions(BigQueryRelationProvider.scala:110)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:50)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:35)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:240)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:229)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)

Do I need to have a certain Spark/Scala installed for the parentProject parameter to work? I am using Spark 3.0.0 with Python 3. 

Thanks for the help.

**Comment by chrisbeckett8** [comment]
As a note, I used the parentProject parameter via reading: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/33

**Comment by chrisbeckett8** [comment]
If anyone else comes across this and is unfamiliar with sbt, this is what I had to do:

1. Download sbt from scala/sbt.org
2. Download all the code from the main page using "clone/download" and unzip it. 
3. Open a command line and within ~/spark-bigquery-connector-master/ run: sbt assembly. 
4. Once this completed, look in  ~/spark-bigquery-connector-master/published/target/scala-2.11, the spark-bigquery-with-dependencies-assembly-0.12.0-beta-SNAPSHOT is what you need to copy and paste into your spark jars folder, for commands like "parentProject" or "credentialsFile" to work. @davidrabinowitz would you consider adding something like this to the sbt portion of the github page to make it easier for future non-java/scala developers like me?

**Comment by davidrabinowitz** [comment]
Spark 3.0.0 is probably running on scala 2.12. Can you please try using gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar?

**Comment by davidrabinowitz** [comment]
The new version (0.12.0-beta) new informs you if there's a mismatch between the Scala version of Spark and the Scala version of the connector.

**Comment by chrisbeckett8** [comment]
Thanks for the response and help. I ended up downgrading to spark 2.4.4 and using the spark big query latest along with compiling the jar for the option scala functions.
