### ISSUE TITLE
Error when trying to save on BigQuery through Dataproc & PySpark Job

### ISSUE THREAD

**Issue by konmavrakis** [GoogleCloudDataproc/spark-bigquery-connector#109]
When trying to save a DataFrame to BigQuery thorugh the Google BigQuery Connector I have this error: 
```
py4j.protocol.Py4JJavaError: An error occurred while calling o373.save.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.google.cloud.spark.bigquery.SparkBigQueryOptions.<init>(SparkBigQueryOptions.scala:28)
	at com.google.cloud.spark.bigquery.SparkBigQueryOptions$.apply(SparkBigQueryOptions.scala:105)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryOptions(BigQueryRelationProvider.scala:110)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:76)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 33 more
```

Code snippet: 

```
# Creating Spark Context
sc = SparkContext().getOrCreate()

ssc = StreamingContext(sc, BATCH_TIMEOUT)
sqlC = SQLContext(sc)

dstream = ssc.textFileStream(DATA_PATH)

...

# when trying to save
data_df.write.format('bigquery').option('table', 'dataest.table').option("temporaryGcsBucket","bucket").save()
```

Also when creating the PySpark job I pass the following jar `gs://spark-lib/bigquery/spark-bigquery-latest.jar`

**Comment by davidrabinowitz** [comment]
Which Spark version are you using? Which Scala version?

**Comment by konmavrakis** [comment]
Through the master VM the Spark version is 2.4.4 and Scala version is 2.12.10. Let me know if you need me to check version from UI.

**Comment by davidrabinowitz** [comment]
Thanks for your answer. Please use gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar instead, it is the relevant connector jar for scala 2.12.
