### ISSUE TITLE
Getting this error : java.lang.IllegalArgumentException: A metric named XXX.bigquery-metrics-source.scanTime already exists

### ISSUE THREAD

**Issue by mrigendrakr** [GoogleCloudDataproc/spark-bigquery-connector#1114]
Getting below error while trying to load data from multiple bigquery tables inside spark.
It doesn't stop execution but this keep printing in console log. 

`
**java.lang.IllegalArgumentException: A metric named local-1698747462144.driver.bigquery-metrics-source.scanTime already exists**

	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:168) ~[metrics-core-4.2.10.jar:4.2.10]
	at com.codahale.metrics.MetricRegistry$1.onTimerAdded(MetricRegistry.java:153) ~[metrics-core-4.2.10.jar:4.2.10]
	at com.codahale.metrics.MetricRegistry.notifyListenerOfAddedMetric(MetricRegistry.java:560) ~[metrics-core-4.2.10.jar:4.2.10]
	at com.codahale.metrics.MetricRegistry.addListener(MetricRegistry.java:393) ~[metrics-core-4.2.10.jar:4.2.10]
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:110) ~[metrics-core-4.2.10.jar:4.2.10]
	at org.apache.spark.metrics.MetricsSystem.registerSource(MetricsSystem.scala:165) ~[spark-core_2.13-3.3.2.jar:3.3.2]
	at com.google.cloud.spark.bigquery.v2.context.ArrowInputPartitionContext.createPartitionReaderContext(ArrowInputPartitionContext.java:70) ~[spark-3.1-bigquery-0.32.2.jar:?]
	at com.google.cloud.spark.bigquery.v2.BigQueryPartitionReaderFactory.createColumnarReader(BigQueryPartitionReaderFactory.java:35) ~[spark-3.1-bigquery-0.32.2.jar:?]
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:79) ~[spark-sql_2.13-3.3.2.jar:3.3.2]
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63) ~[spark-sql_2.13-3.3.2.jar:3.3.2]
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37) ~[spark-core_2.13-3.3.2.jar:3.3.2]
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:576) ~[scala-library-2.13.8.jar:?]`

**Comment by suryasoma** [comment]
hey @mrigendrakr, I am trying to replicate the same but couldn't. 

Used the following code 
```
    spark.read().format("bigquery").option("table", <TABLE_1>).load().show(5);

    spark.read().format("bigquery").option("table", "<TABLE_2>).load().show(10);
```

Can you please help me replicate the issue. And just to confirm you are using `spark-3.4-bigquery-0.34.0` connector right?

**Comment by isha97** [comment]
Hi @mrigendrakr , are you still facing this issue? If yes, please open a new issue providing the following details,
Sample spark code, details about how are you running the job.
