### ISSUE TITLE
BigQuery write fails with MessageSize is too large

### ISSUE THREAD

**Issue by eric-pa** [GoogleCloudDataproc/spark-bigquery-connector#1116]
Hi,

I'm trying to write a dataframe to a BigQuery table which seems to fails due to the Storage Write API limit of 10 MB per request.

### Code
The code looks as follows:
```py
df.write \
  .mode("overwrite") \
  .format("bigquery") \
  .option("writeMethod", "direct") \
  .option("writeDisposition", 'WRITE_TRUNCATE') \
  .save("xxx.xxx.xxx")
```

### Cluster configuration:
- serverless batch job
- spark-bigquery-with-dependencies_2.12-0.33.0.jar

### Error
Spark output:
```
Using the default container image
Waiting for container log creation
PYSPARK_PYTHON=/opt/dataproc/conda/bin/python
Generating /home/spark/.pip/pip.conf
Configuring index-url as 
Configuring target as /mnt/dataproc/python/site-packages
JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
SPARK_EXTRA_CLASSPATH=
:: loading settings :: file = /etc/spark/conf/ivysettings.xml
23/10/31 16:42:38 WARN BigQueryDataSourceWriterInsertableRelation: It seems that 1 out of 0 partitions have failed, aborting
23/10/31 16:42:38 WARN BigQueryDirectDataSourceWriterContext: BigQuery Data Source writer xxxxxxx-xxx aborted

```

Logs:
```
com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not retrieve AppendRowsResponse
    at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:212)
    at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.sendAppendRowsRequest(BigQueryDirectDataWriterHelper.java:188)
    at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.addRow(BigQueryDirectDataWriterHelper.java:169)
    at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:86)
    at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:35)
    at com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:61)
    at com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:33)
    at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1(JavaRDDLike.scala:102)
    at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1$adapted(JavaRDDLike.scala:102)
    at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:907)
    at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:907)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
    at org.apache.spark.scheduler.Task.run(Task.scala:136)
    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: MessageSize is too large. Max allow: 10000000 Actual: 10058872
    at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
    at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
    at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:55)
    at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:210)
    ... 21 moreCaused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: MessageSize is too large. Max allow: 10000000 Actual: 10058872
    at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.ConnectionWorker.appendInternal(ConnectionWorker.java:276)
    at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.ConnectionWorker.append(ConnectionWorker.java:267)
    at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter$SingleConnectionOrConnectionPool.append(StreamWriter.java:136)
    at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter.append(StreamWriter.java:371)
    at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.sendAppendRowsRequest(BigQueryDirectDataWriterHelper.java:187)
    ... 20 more
```

**Comment by vishalkarve15** [comment]
The log message suggests that the configuration for connector version is not getting applied correctly.
Can you please share which serverless version you're using?

**Comment by vishalkarve15** [comment]
It would be available in the next release.

**Comment by mayank-kapoor-db** [comment]
> It would be available in the next release.

Hi - Is this fixed? If yes, in which release version of the connector?
