### ISSUE TITLE
df.write()not working with Spark-Java code on serverless

### ISSUE THREAD

**Issue by saikrishnab27** [GoogleCloudDataproc/spark-bigquery-connector#1286]
Hello team, Amex is testing the connector and running into few issues.
I'm getting this TimestampTNZ exception when i'm trying to write data to a bigquery table.
If the table exists, it's giving a different error that the table already exists try append mode.

1.Error:
`
Using the default container image
Waiting for container log creation
PYSPARK_PYTHON=/opt/dataproc/conda/bin/python
JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
SPARK_EXTRA_CLASSPATH=
:: loading settings :: file = /etc/spark/conf/ivysettings.xml
24/09/04 17:59:30 INFO SparkBigQueryConnectorModule: Registering cleanup jobs listener, should happen just once
Exception in thread "main" java.lang.NoSuchFieldError: TimestampNTZType
	at com.google.cloud.spark.bigquery.v2.TimestampNTZTypeConverter.supportsSparkType(TimestampNTZTypeConverter.java:58)
	at com.google.cloud.spark.bigquery.SchemaConverters.lambda$toBigQueryType$7(SchemaConverters.java:586)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.google.cloud.spark.bigquery.SchemaConverters.toBigQueryType(SchemaConverters.java:588)
	at com.google.cloud.spark.bigquery.SchemaConverters.createBigQueryColumn(SchemaConverters.java:526)
	at com.google.cloud.spark.bigquery.SchemaConverters.sparkToBigQueryFields(SchemaConverters.java:468)
	at com.google.cloud.spark.bigquery.SchemaConverters.toBigQuerySchema(SchemaConverters.java:456)
	at com.google.cloud.spark.bigquery.write.BigQueryWriteHelper.<init>(BigQueryWriteHelper.java:99)
	at com.google.cloud.spark.bigquery.write.BigQueryDeprecatedIndirectInsertableRelation.insert(BigQueryDeprecatedIndirectInsertableRelation.java:41)
	at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createRelation(CreatableRelationProviderHelper.java:58)
	at com.google.cloud.spark.bigquery.v2.Spark31BigQueryTableProvider.createRelation(Spark31BigQueryTableProvider.java:65)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:47)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:357)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
	at com.example.ReadBigQueryTable.main(ReadBigQueryTable.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:984)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
24/09/04 17:59:33 INFO SparkBigQueryConnectorModule: In SparkListener.onApplicationEnd, going to activate cleanup jobs
24/09/04 17:59:33 INFO BigQueryClient: Running cleanup jobs. Jobs count is 0
24/09/04 17:59:33 INFO BigQueryClient: Clearing the cleanup jobs list
24/09/04 17:59:33 INFO BigQueryClient: Finished to run cleanup jobs.`

1.Java code being used:
`
package com.example;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;

public class ReadBigQueryTable {

    public static void main(String[] args) {

        // Create a Spark session
        SparkSession spark = SparkSession.builder()
                .appName("Read BigQuery Table")
                .getOrCreate();

        // Set your Google Cloud project ID
        spark.conf().set("views.query.project", "amex-test-370307");

        // Use the BigQuery connector to read the table
        Dataset<Row> df = spark.read()
            .format("bigquery")
            .option("table", "xxxx-test-370307.average_weather.employees")
            //.option("filter", "timestamp_month = '2018-10-01'")
            .load();
        
        df.write()
            .format("bigquery")
            //.option("writeMethod", "direct")
            //.mode("Append")
            //.mode(SaveMode.Append)
            .option("temporaryGcsBucket","gs://dataproc-staging-us-central1-335164402719-7p9cexwa/tmp/")
            .save("average_weather.employees1");

        // Show the first 20 rows of the DataFrame
        df.show();

        // Stop the Spark session
        spark.stop();
    }
}
`

3.Pom file being used:
```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.1</version>

  <name>demo</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <java.version>17</java.version>
  </properties>

  <dependencies>
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.11</version>
    <scope>test</scope>
  </dependency>

  <dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-core_2.13</artifactId> 
    <!--version>3.4.1</version-->
    <version>3.3.0</version>
    <scope>provided</scope>
  </dependency>

  <dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-sql_2.13</artifactId>
    <version>3.3.0</version>
    <scope>provided</scope>
  </dependency>

  <!--dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-bigquery</artifactId>
  </dependency-->

  <!-- <dependency> 
    <groupId>com.google.cloud.spark</groupId>
    <artifactId>spark-bigquery-with-dependencies_2.13</artifactId>
    <version>0.28.1</version>
    <scope>provided</scope>
  </dependency> -->

  </dependencies>

  <!--dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        <version>26.1.5</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement-->


  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
          <configuration>
            <archive>
              <manifestEntries>
                <Main-Class>com.example.ReadBigQueryTable</Main-Class>
              </manifestEntries>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
`
5.I'm running this jar file from Airflow DatprocBatchCreateOperator
`
import datetime

from airflow import models
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocCreateBatchOperator,
    DataprocDeleteBatchOperator,
    DataprocGetBatchOperator,
    DataprocListBatchesOperator,
)
from airflow.utils.dates import days_ago

# Define your variables here or use Airflow Variables
PROJECT_ID = 'xxxxx-test-370307'
REGION = 'us-central1'
BUCKET = 'dataproc-staging-us-central1-335164402719-7p9cexwa'
JAR_FILE = 'demo-0.1.jar'
GCS_JAR_PATH = f'gs://{BUCKET}/{JAR_FILE}'
BASE_BATCH_ID = 'batch-create-phs'

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'start_date': days_ago(1),
}

with models.DAG(
    'dataproc_serverless_java_test',
    default_args=default_args,
    description='Submit a Spark job to Dataproc Serverless using batch operators',
    schedule_interval=None,  # Set to a cron expression if scheduling
    catchup=False,
) as dag:
    
    BATCH_ID = BASE_BATCH_ID + '-' + '{{ ts_nodash.replace("T", "") }}'

    create_batch = DataprocCreateBatchOperator(
        task_id='create_batch',
        batch={
            'spark_batch': {
                'main_jar_file_uri': GCS_JAR_PATH,
                'jar_file_uris': [GCS_JAR_PATH,'gs://spark-lib/bigquery/spark-3.5-bigquery-0.40.0.jar'], ##tried without connector as serverless have a default connector
                'args': [],  # Add any arguments to pass to your application here
            },
            'environment_config': {
                'peripherals_config': {
                    'spark_history_server_config': {
                        'dataproc_cluster': 'projects/{}/regions/{}/clusters/{}'.format(PROJECT_ID, REGION, 'phs-server'),
                    },
                },
            }
        },
        batch_id=BATCH_ID,
        project_id=PROJECT_ID,
        region=REGION,
    )

    list_batches = DataprocListBatchesOperator(
        task_id='list_batches',
        project_id=PROJECT_ID,
        region=REGION,
    )

    get_batch = DataprocGetBatchOperator(
        task_id='get_batch',
        batch_id=BATCH_ID,
        project_id=PROJECT_ID,
        region=REGION,
    )

    create_batch >> list_batches >> get_batch
```

**Comment by isha97** [comment]
`TimestampNTZType` was introduced in spark 3.5. Please use Spark 3.5 and use the latest version of Spark 3.5 connector
https://github.com/GoogleCloudDataproc/spark-bigquery-connector?tab=readme-ov-file#maven--ivy-package-usage
`com.google.cloud.spark:spark-3.5-bigquery:0.41.0`
