### ISSUE TITLE
pyspark issue while connecting the bigquery for read and write in DATAPROC

### ISSUE THREAD

**Issue by san120612** [GoogleCloudDataproc/spark-bigquery-connector#1308]
@davidrabinowitz 

Hello @gomrinal @davidrabinowitz ,
I am getting the below error while connecting bigquery with pyspark.
from pyspark.sql import SparkSession
spark = SparkSession.builder
.appName('1.2. BigQuery Storage & Spark SQL - Python')
.config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar')
.getOrCreate()

df = (
spark.read.format("bigquery")
.option("table", "vz-it-np-hbnv-dev-tfsdo-0.tfs_raw_hashed.zoominfo_company")
.load()
)

Py4JJavaError: An error occurred while calling o131.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:692)
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:746)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:265)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:666)
at scala.util.Try$.apply(Try.scala:213)
at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:666)
at scala.util.Failure.orElse(Try.scala:224)
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:666)

pyspark version :3.1.3

**Comment by san120612** [comment]
@davidrabinowitz I am running on DATAPROC cluster

**Comment by san120612** [comment]
@davidrabinowitz 

Looking for help to fix the issue.

**Comment by isha97** [comment]
Hi @san120612 Can you specify the Dataproc image that you are using to run the job?
Please follow these guidelines to use connector with a Dataproc cluster/batch https://github.com/GoogleCloudDataproc/spark-bigquery-connector?tab=readme-ov-file#specifying-the--spark-bigquery-connector-version-in-a-dataproc-cluster

**Comment by isha97** [comment]
@san120612 Please open a new bug if you are still facing the issue after trying the steps mentioned in the previous comment with the Dataproc image details.
