### ISSUE TITLE
Received provider not found error when running Spark and BigQuery in GCP Dataproc

### ISSUE THREAD

**Issue by shihgianlee** [GoogleCloudDataproc/spark-bigquery-connector#136]
I created a simple maven project that contains the following Scala code:

```scala
package com.my.company.bigquery

import com.google.cloud.spark.bigquery._
import org.apache.spark.sql.SparkSession

object SparkBigQuery {
  def main(args: Array[String]) {

    val spark = SparkSession.builder()
      .appName("spark-bigquery")
      .getOrCreate()

    // Use the Cloud Storage bucket for temporary BigQuery export data used
    // by the connector. This assumes the Cloud Storage connector for
    // Hadoop is configured.
    val bucket = spark.sparkContext.hadoopConfiguration.get("fs.gs.system.bucket")
    spark.conf.set("temporaryBigQueryBucket", bucket)

    val projectDF = spark.read.bigquery("gcp-project:test.appointment").cache()
    projectDF.show(2)

    println("Done!")
  }
}
```

Then I built an uber jar and deployed to GCP dataproc:
```bash
gcloud dataproc jobs submit spark \
	--cluster=dataproc-bigquery-jobs-1 \
	--region=us-central1 \
	--properties spark.driver.memory=1g,spark.executor.memory=1g,spark.driver.cores=1,spark.executor.cores=1 \
	--class=com.my.company.bigquery.SparkBigQuery \
	--jars=spark-bigquery-1.0-SNAPSHOT.jar
```

Then I received the following error:
```
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:618)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
	at shaded.com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
	at com.porch.science.bigquery.SparkBigQuery$.main(SparkBigQuery.scala:21)
	at com.porch.science.bigquery.SparkBigQuery.main(SparkBigQuery.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I have searched exhausively on the Web to find out what `Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider not found` mean but with no luck.

Can someone let me know what did I do wrong?

**Comment by shihgianlee** [comment]
Ok, I didn't include `gs://spark-lib/bigquery/spark-bigquery-latest.jar`. The example in README is for pyspark and I thought I didn't need it since I have included the following in my `pom.xml`:
```xml
<dependency>
   <groupId>com.google.cloud.spark</groupId>
   <artifactId>spark-bigquery_2.11</artifactId>
   <version>0.13.1-beta</version>
</dependency>
```
Here is an updated sumbit job command:
```
gcloud dataproc jobs submit spark \
	--cluster=dataproc-bigquery-jobs-1 \
	--region=us-central1 \
	--properties spark.driver.memory=1g,spark.executor.memory=1g,spark.driver.cores=1,spark.executor.cores=1 \
	--class=com.my.company.bigquery.SparkBigQuery \
	--jars=spark-bigquery-1.0-SNAPSHOT.jar,gs://spark-lib/bigquery/spark-bigquery-latest.jar
```

**Comment by davidrabinowitz** [comment]
You need to add the connector jar, unless you have created an uber-jar or fat jar - have all your dependencies in the jar as well. If your jar contains just your logic, then the connector has to be added to Spark's classpath by using --jars or --packages

**Comment by shihgianlee** [comment]
Thank you for your reply, David!

I did create an uber jar with maven dependency above (`spark-bigquery-with-dependencies_2.11`). What additional dependencies will I need to include in my uber jar?

**Comment by davidrabinowitz** [comment]
All the dependencies which are not provided by default by Spark, or when you need a version different from what spark provides. Notice that in the latter case you would need to [shade the dependency](https://softwareengineering.stackexchange.com/questions/297276/what-is-a-shaded-java-dependency), in order to avoid collusion with the Spark classpath.

**Comment by shihgianlee** [comment]
That makes sense! I have `shaded` uber jar. Everything has been renamed and repackaged. No wonder spark cluster could not find the classes it need. You are right that we have versions different from spark provide. So, we are using shaded jar. 

Thanks for your help!
