### ISSUE TITLE
Use spark-bigquery connector on Zeppelin but received error

### ISSUE THREAD

**Issue by shihgianlee** [GoogleCloudDataproc/spark-bigquery-connector#138]
I have a Zeppelin running in dataproc. How do I install spark-bigquery connector on Zeppelin?

I tried the following:
```scala
z.load("com.google.cloud.spark:spark-bigquery_2.11:0.13.1-beta")
val df = spark.read.bigquery("table:dataset.table").cache()
```

but I got the following error:
```
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
  at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:84)
  at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:88)
  at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:74)
  at com.google.cloud.RetryHelper.run(RetryHelper.java:75)
  at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
  at com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:665)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:56)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:37)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
  at com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
```

The Web search points to mismatch of Guava version that is used by spark-bigquery and hadoop. But, I could not find any proof of that.

Any ideas what I can try?

**Comment by davidrabinowitz** [comment]
Please try 
```
z.load("com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.13.1-beta")
```

**Comment by shihgianlee** [comment]
> Please try
> 
> ```
> z.load("com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.13.1-beta")
> ```

That is it! It works! I am so glad it is that simple. Now, spark-bigquery works in both `zeppelin` and gcloud `dataproc jobs submit spark`. Thank you David!
