### ISSUE TITLE
Unable to insert data into Time Column from spark scala.

### ISSUE THREAD

**Issue by charan478** [GoogleCloudDataproc/spark-bigquery-connector#144]
I am trying to insert data into bigquery table with Time column from spark . I am currently trying with 0.13.1-beta, I have also tried with 0.11.1-beta which gave me same error. I am aware that Spark sql have no TimeType and when reading data from bigquery to spark it converts that into long type. I am trying to insert column of type long into field of Time type in bigquery and failing with error that the column is integer. I am confused why the type is infered as integer when the type of scrum_time column is long in spark. I tried intermediate type parquet and orc no diffrence 

Snippet I am using to push to Bigquery in spark is

```
batchDf.printSchema()
batchDf.show(false)
tables.foreach(table=>batchDf.write.mode(SaveMode.Append).format("com.google.cloud.spark.bigquery").option("temporaryGcsBucket", "sparkoperatorexample").option("table", table).save()
```
The schema for the row I am trying to insert into bigquery is 
```20/03/24 07:34:22 INFO CodeGenerator: Code generated in 415.620557 ms
root
 |-- name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- birthday: timestamp (nullable = true)
 |-- employed_date: date (nullable = true)
 |-- scrum_time: long (nullable = true)

Few Sample data is as follows
20/03/24 07:34:41 INFO DAGScheduler: Job 0 finished: start at ConfluentKafkaAvroReader.scala:84, took 17.865636 s
+------+---+-------------------+-------------+----------+
|name  |age|birthday           |employed_date|scrum_time|
+------+---+-------------------+-------------+----------+
|ching |22 |1991-06-28 18:50:20|2019-09-03   |39650099  |
|charan|28 |1991-06-28 13:17:00|2019-09-03   |39650099  |
|ching |22 |1991-06-28 18:50:20|2019-09-03   |39650099  |
|charan|28 |1991-06-28 13:17:00|2019-09-03   |39650099  |
|ching |22 |1991-06-28 18:50:20|2019-09-03   |39650099  |
|charan|28 |1991-06-28 13:17:00|2019-09-03   |39650099  |
|ching |22 |1991-06-28 18:50:20|2019-09-03   |39650099  |
|charan|28 |1991-06-28 13:17:00|2019-09-03   |39650099  |
+------+---+-------------------+-------------+----------+
```

Table Schema 
```
Field name	Type		Mode		Description
name		STRING		NULLABLE	employee name
age		INTEGER		NULLABLE	employee age
birthday	TIMESTAMP	NULLABLE	employee birthday
employed_date	DATE		NULLABLE	date that employee get employed
scrum_time	TIME		NULLABLE	time that employee do scrum
```
The error I am getting 

```
java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:78)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:85)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$3(ConfluentKafkaAvroReader.scala:89)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$3$adapted(ConfluentKafkaAvroReader.scala:88)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$2(ConfluentKafkaAvroReader.scala:88)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$2$adapted(ConfluentKafkaAvroReader.scala:84)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$14(MicroBatchExecution.scala:536)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:349)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:198)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:349)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Failed to load to data-infrastructure-test-env.emptest.emptesttable1 in job JobId{project=data-infrastructure-test-env, job=6fcf9a62-8ba9-4cde-8897-715f66b8ff40, location=EU}. BigQuery error was Provided Schema does not match Table data-infrastructure-test-env:emptest.emptesttable1. Field scrum_time has changed type from TIME to INTEGER
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:135)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:76)
	... 47 more
20/03/24 08:07:24 INFO AbstractCoordinator: [Consumer clientId=consumer-1, groupId=spark-kafka-source-ef72bc8d-f86d-4f75-8341-da75e6616d06--42496990-driver-0] Member consumer-1-5666a81c-b3e2-493b-a270-cd67afef80e5 sending LeaveGroup request to coordinator kafka-2.kafka-svc.default:9092 (id: 2147483645 rack: null)
Exception in thread "main" org.apache.spark.sql.streaming.StreamingQueryException: Failed to write to BigQuery
=== Streaming Query ===
Identifier: [id = 583f71ab-586b-498b-987f-67d7339bb960, runId = 2c21a62e-9a59-4a8e-8c57-4bdecc3fa58c]
Current Committed Offsets: {}
Current Available Offsets: {KafkaV2[Subscribe[dna-emp-test]]: {"dna-emp-test":{"0":8}}}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
Project [data#21.name AS name#33, data#21.age AS age#34, data#21.birthday AS birthday#35, data#21.employed_date AS employed_date#36, data#21.scrum_time AS scrum_time#37L]
+- Filter isnotnull(data#21)
   +- Project [from_avro(value#8, None, Some(Map(value.schema.id -> latest, value.schema.naming.strategy -> topic.name, schema.name -> native_complete, schema.registry.topic -> dna-emp-test, schema.namespace -> all-types.test, key.schema.id -> latest, schema.registry.url -> http://sr-svc:8081)), true) AS data#21]
      +- StreamingExecutionRelation KafkaV2[Subscribe[dna-emp-test]], [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13]

	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:302)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:78)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:85)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$3(ConfluentKafkaAvroReader.scala:89)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$3$adapted(ConfluentKafkaAvroReader.scala:88)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$2(ConfluentKafkaAvroReader.scala:88)
	at com.geotab.ghadp.examples.ConfluentKafkaAvroReader$.$anonfun$startStreams$2$adapted(ConfluentKafkaAvroReader.scala:84)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$14(MicroBatchExecution.scala:536)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:349)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:198)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:349)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	... 1 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Failed to load to data-infrastructure-test-env.emptest.emptesttable1 in job JobId{project=data-infrastructure-test-env, job=6fcf9a62-8ba9-4cde-8897-715f66b8ff40, location=EU}. BigQuery error was Provided Schema does not match Table data-infrastructure-test-env:emptest.emptesttable1. Field scrum_time has changed type from TIME to INTEGER
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:135)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:76)
	... 47 more

```

**Comment by charan478** [comment]
I have aslo tried creating a udf to convert it to string in format [H]H:[M]M:[S]S[.DDDDDD] and tried to push that dataset, No sucess. I am wondering which format/type in spark will be accepted as a valid time.

**Comment by charan478** [comment]
Any update on estimated time to complete.

**Comment by Gaurangi94** [comment]
We are working on trying out potential solutions for this issue. We will update you once we have fixed this

**Comment by charan478** [comment]
I have tried with avro intermediateFormat , just to check if that fixes this. It seems like avro is more lacking behing I am not able to serilize date logical type also. Is that a known issue?

**Comment by tsuxia** [comment]
I am having the same problem too, hope we could get a fix for this.

**Comment by vishalkarve15** [comment]
Added functionality to write String to BQ TIME type.
