### ISSUE TITLE
Returns empty dataframe

### ISSUE THREAD

**Issue by sharath-data** [GoogleCloudDataproc/spark-bigquery-connector#151]
Is this the right way to query an unpartitioned table based on a condition?
Querying a table (the source table raw_c.metrics does not have a partition):

```
    spark = SparkSession.builder \
        .config("spark.jars.packages", "com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.14.0-beta") \
        .getOrCreate()
    df = spark.read.format("bigquery") \
        .option("table", "raw_c.metrics") \
        .option("filter", "cast(timestamp as date) = '2020-04-01'") \
        .load() \
        .toJSON()

    by_metrics = df.flatMap(process_row).keyBy(lambda r: json.loads(r)['metric']['_metricname'])
    print("done by_metrics")
    metric_names = by_metrics.keys().distinct().collect()
    print("metric_names -> ", metric_names)
```
Error:

done by_metrics
metric_names ->  []
Traceback (most recent call last):
  File "/tmp/dfed9226406b4d3184d72445f60c22df/cli_loader.py", line 8, in <module>
    sys.exit(module.main(sys.argv[2:]))
  File "/tmp/dfed9226406b4d3184d72445f60c22df/Click-7.0-py2.py3-none-any.zip/click/core.py", line 764, in __call__
  File "/tmp/dfed9226406b4d3184d72445f60c22df/Click-7.0-py2.py3-none-any.zip/click/core.py", line 717, in main
  File "/tmp/dfed9226406b4d3184d72445f60c22df/Click-7.0-py2.py3-none-any.zip/click/core.py", line 956, in invoke
  File "/tmp/dfed9226406b4d3184d72445f60c22df/Click-7.0-py2.py3-none-any.zip/click/core.py", line 555, in invoke
  File "/tmp/dfed9226406b4d3184d72445f60c22df/data_procs-0.2.110-py3-none-any.zip/data_procs/ccloud_metrics.py", line 73, in main
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 58, in toDF
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 746, in createDataFrame
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 390, in _createFromRDD
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 361, in _inferSchema
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1381, in first
**ValueError: RDD is empt**

**Comment by davidrabinowitz** [comment]
Hi @sharath-data ,

Is `timestamp` a field of `raw_c.metrics` ? What happens if you run this query directly on BigQuery?

**Comment by sharath-data** [comment]
Yes, timestamp is a field of `raw_c.metrics` 
Running this query : `select count(*) from raw_c.metrics where cast(timestamp as date) = '2020-04-01'` gives me about 800k records.

**Comment by sharath-data** [comment]
I updated to latest jar, this is getting me the records. 
I am closing this issue. Thanks.
