### ISSUE TITLE
Writing to BigQuery throwing FileNotFound Exception

### ISSUE THREAD

**Issue by mamdouhweb** [GoogleCloudDataproc/spark-bigquery-connector#175]
Hi,

I'm using the connector to write to BQ from a scala spark job on Dataproc GCP. 
The exception I'm getting is:

```scala
Exception in thread "main" java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.google.cloud.spark.bigquery.SparkBigQueryOptions.createCredentials(SparkBigQueryOptions.scala:70)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider$.createBigQuery(BigQueryRelationProvider.scala:126)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider$$anonfun$getOrCreateBigQuery$1.apply(BigQueryRelationProvider.scala:109)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider$$anonfun$getOrCreateBigQuery$1.apply(BigQueryRelationProvider.scala:109)
	at scala.Option.getOrElse(Option.scala:121)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.getOrCreateBigQuery(BigQueryRelationProvider.scala:109)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:81)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
```

Looking at the source code, this is expecting an access token. But even when I try to force credentialFile it still the same error with line 70

Here's the code snippet 

```scala
 df.write
      .format("bigquery")
      .option("table", tableId)
      .mode("overwrite")
      .save()
```

and build.sbt relevant parts

```scala
"com.google.cloud.bigdataoss" % "gcs-connector" % "hadoop2-2.0.0" exclude("javax.jms", "jms") exclude("com.sun.jdmk", "jmxtools") exclude("com.sun.jmx", "jmxri"),
      "com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.15.1-beta" % "provided",
```

Note: Reading from GCS is working completely fine, and here are the main configs for that

```scala
sc.hadoopConfiguration.set(
      "fs.gs.impl",
      "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    sc.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl",
                               "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
    sc.hadoopConfiguration
      .set("fs.gs.project.id", projectId) // actual project filled in
    sc.hadoopConfiguration
      .set("google.cloud.auth.service.account.enable", "true")
    sc.hadoopConfiguration
      .set("google.cloud.auth.service.account.json.keyfile", keyfilePath)
```

Any thoughts on why would this exception gets triggered?

Spark Version: 2.4.4
Scala: 2.11.9

**Comment by davidrabinowitz** [comment]
The exception occurs since spark cannot find the file at `keyfilePath`. Can you please verify it exists on all the cluster's nodes in the same location?

**Comment by mamdouhweb** [comment]
@davidrabinowitz thanks for the quick response. That was my guess, but I’m connected to GCS and downloading Avro files with no issues in the same job.
Is there a specific configuration for BQ I have to consider?
The default service account in data processing should be just good enough, correct?

**Comment by davidrabinowitz** [comment]
@mamdouhweb  The only thing that comes to mind is that the files are being read from GCS in the executors while the above error is in the driver. Are there any differences between the nodes?

The connector also uses the GCS connector configuration of `google.cloud.auth.service.account.json.keyfile`, and the fact it arrives to this line means that it was configured correctly.

Can you please add a small test in the driver? Add the following code and see if it emits the content of the JSON file:
```
println(scala.io.Source.fromFile(sc.hadoopConfiguration.get("google.cloud.auth.service.account.json.keyfile")).getLines.mkString("\n"))
```

**Comment by mamdouhweb** [comment]
@davidrabinowitz you're right!
```scala
Exception in thread "main" java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:91)
	at scala.io.Source$.fromFile(Source.scala:76)
	at scala.io.Source$.fromFile(Source.scala:54)
	at BatchProcess$.main(BatchProcess.scala:93)
```

This is seriously a weird behavior on Dataproc. This is a very minimal build with Dataproc image 1.4. It should be including the service account by default. Even when I specified `--service-account` and in the `describe` I see it attached, it's still not seeing it.

This is a dataproc issue so I believe we can close this one, and I have to look into why DP is acting this way.

Appreciate your help

**Comment by davidrabinowitz** [comment]
Can you share more data where how `keyfilePath` is populated?

**Comment by medb** [comment]
@mamdouhweb if you are setting `--service-account` in Dataproc it does not mean that you need to set `google.cloud.auth.service.account.enable` and `google.cloud.auth.service.account.json.keyfile` properties, because they override `--service-account` setting with custom key files.

If you will drop these configs, it will work as you expect, at least on GCS connector side.
