### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll

### ISSUE THREAD

**Issue by mohammadskhan** [GoogleCloudDataproc/spark-bigquery-connector#185]
java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V
	at com.google.cloud.bigquery.storage.v1.ReadSession$TableReadOptions$Builder.addAllSelectedFields(ReadSession.java:1854)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.scala:111)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:403)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:321)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)

**Comment by davidrabinowitz** [comment]
Can you please give more context? How did you run the application? How have you imported the connector?

**Comment by mohammadskhan** [comment]
@davidrabinowitz Thanks for your response, the issue got resolved by adding the shading option mentioned below.
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/35#issuecomment-511401360
