### ISSUE TITLE
Bug when reading views

### ISSUE THREAD

**Issue by afghifariii** [GoogleCloudDataproc/spark-bigquery-connector#196]
when reading to a `view` on a different project, it always try to create the job in the default `projectId`. here is the example
for context i am running the spark job also on different project let say `current-project-id`

```
val parentProjectId = "parent-project-id"
val anotherProjectid = "another-project-id"
val fullTableName = s"$anotherProjectId:some_table.some_view"
val viewMaterializationDataset = "some_tmp_dataset"

val df = spark.read
    .option("parentProject", parentProjectId)
    .option("viewsEnabled", true)
    .option("viewMaterializationProject", parentProjectId)
    .option("viewMaterializationDataset", viewMaterializationDataset)
    .bigquery(fullTableName)
```

from my understanding, it should create a `materialized view` on project `parent-project-id` and dataset `some_tmp_dataset`, but what happened is it try to create the `materialized view` using `current-project-id` because i get permission issue because the ServiceAccount doesn't have permission `job.create` in `current-project-id`

**Comment by davidrabinowitz** [comment]
Can you please set the log to debug and look for the log line that begins with `destinationTable is`? This should give us the materialization table.

**Comment by afghifariii** [comment]
```
main DEBUG DirectBigQueryRelation: destinationTable is GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=some_tmp_dataset, projectId=parent-project-id, tableId=_sbc_e696652833fa4c4cb914b663e9e89eef}}
```

**Comment by kmjung** [comment]
At a high level, from BigQuery's perspective, it's possible for all of these projects to be different:
- The project which owns the view being read from
- The project which owns the job to query the view and is billed for the query execution
- The project which owns the destination table to which data is written by the query
- The project which reads the data (e.g. the parent project for the read session) and is billed for the read

It's also possible for the project in which the Dataproc job is running to be distinct from all of the above.

I'm not familiar with what the connector actually does here, but my expectation would be that, by default, if you've specified a `"parentProject"` option, then the query job to read from the view should be created in the context of that project, and that the output table should also be created in the context of that project. It sounds like this is not the case today, and that the job to query the view is actually created in the context of the "current" project (e.g. the one associated with the service account in which your job is running). @davidrabinowitz does that sound right to you?

Note that [BigQuery materialized views](https://cloud.google.com/bigquery/docs/materialized-views-intro) are not involved here -- the connector simply executes a `SELECT *` query against the target view and writes the result to a simple destination table.

**Comment by afghifariii** [comment]
yes correct @kmjung . any update on this ?

**Comment by kmjung** [comment]
I think the next step here is for @davidrabinowitz or @Gaurangi94 to weigh in.

**Comment by chezihp** [comment]
Not sure if it's related by I have similar problem. Im trying to access a view with viewMaterializationProject/viewMaterializationDataset parameters which are not the same as where the view is located. This is the error Im getting:

`
20/07/06 18:10:50 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Querying table project_name.dataset_name.table_name, parameters sent from Spark: requiredColumns=[], filters=[IsNotNull(event_name),EqualTo(event_name,LM_MAP_TOOLS_SHOWN)]
com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Not found: Dataset project_name.dataset_name was not found in location us-east1
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.getActualTable(DirectBigQueryRelation.scala:200)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.scala:93)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:338)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:337)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:415)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:333)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3260)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2780)
	at com.funnalytics.spark.apps.BiqQueryTestApp.call(BiqQueryTestApp.java:38)
	at com.funnalytics.spark.apps.BiqQueryTestApp.call(BiqQueryTestApp.java:7)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1701)
	at picocli.CommandLine.access$900(CommandLine.java:146)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2059)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2026)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1893)
	at picocli.CommandLine.execute(CommandLine.java:1822)
	at com.funnalytics.spark.apps.BiqQueryTestApp.main(BiqQueryTestApp.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:890)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
`
Other tables (not views) from the project where the view is located are accessible without any problem.
I already verified that the Service Account being used has BigQueryAdmin permissions on the viewMaterializationProject and BigQueryDataViewer+BigQueryJobUser on the project where the view is located. What else Im missing?
can you help please?

**Comment by davidrabinowitz** [comment]
@chezihp Are you having datasets in two different locations? It seems the error is `Not found: Dataset project_name.dataset_name was not found in location us-east1`. If so, can you please open this as another bug?

**Comment by chezihp** [comment]
Thanks David. 
Iv'e opened another issue: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/205

**Comment by afghifariii** [comment]
I think the issue lies on when creating `BigQueryClient`, the parent project is not defined, so by default it'll use the  `current_project_id` which is the project where the spark job is running. CMIIW. [`createCredentials`](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala#L66)

wdyt @davidrabinowitz ?

**Comment by davidrabinowitz** [comment]
@afghifariii  If you are using spark 2.x, please check version 0.17.2 - it may solve your issue

**Comment by afghifariii** [comment]
thanks @davidrabinowitz will check on it

**Comment by amoussoubaruch** [comment]
Hi All, 

I have same issue when trying to read view in project_id_1 with viewMaterializationProject in project_id_2. 
I used spark 2.3.4 and tried my job with spark-bigquery jar lastest version, 0.17.2 version, 0.17.3 version. I had same error : 

`Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Not found: Dataset project_id_1:dataset was not found in location europe-west1
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:625)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1342)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1337)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1336)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1320)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job$1.call(Job.java:334)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job$1.call(Job.java:331)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.poll(RetryHelper.java:64)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:240)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.createTableFromQuery(DirectBigQueryRelation.scala:226)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$DestinationTableBuilder.call(DirectBigQueryRelation.scala:65)
	at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$DestinationTableBuilder.call(DirectBigQueryRelation.scala:64)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 90 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
GET https://www.googleapis.com/bigquery/v2/projects/project_id_2/queries/a6a077f1-f0ae-4f9e-9ced-e8a1388cc5cd?location=europe-west1&maxResults=0&prettyPrint=false
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: Dataset project_id_1:dataset1 was not found in location europe-west1",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Dataset project_id_1:dataset1 was not found in location europe-west1",
  "status" : "NOT_FOUND"
}`

@afghifariii have you any good result in your side? 

Thanks

**Comment by amoussoubaruch** [comment]
Hi all, 

I just want to confirm that the connector work fine to read table view. Dataset location not found error happened when you haven't same location between destination dataset and reading dataset. Use same location fix that. 

Thanks
