### ISSUE TITLE
Error on writing in GCS

### ISSUE THREAD

**Issue by leoneuwald** [GoogleCloudDataproc/spark-bigquery-connector#224]
Hi,

We are running spark-bigquery-connector in an on-premise cluster, and we are getting the following error when we try to write in BigQuery/GCS. Read operation is working.

```
INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
    at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:220)
    at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialConfiguration.getCredential(CredentialConfiguration.java:75)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1869)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1058)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1021)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
    at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
    at com.google.cloud.spark.bigquery.BigQueryWriteHelper.<init>(BigQueryWriteHelper.scala:58)
    at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:41)
    at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:100) 
```

```
    spark.sparkContext.hadoopConfiguration.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    spark.sparkContext.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.project.id", settings.project)
    spark.sparkContext.hadoopConfiguration.set("fs.gs.system.bucket", settings.bucket)
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.enable", "true")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.email", account.clientEmail)
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key.id", account.privateKeyId)
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key", account.privateKey)
```

```
dataFrame.write.mode(saveMode).format("bigquery")
      .option("table", table)
      .option("credentials", credentials)
      .option("project", project)
      .option("parentProject", parentProject)
      .option("temporaryGcsBucket", bucket)
```

Any idea how could I fix this?

**Comment by davidrabinowitz** [comment]
@medb it seems to be an issue with the GCS connector configuration. can you please check?

**Comment by medb** [comment]
Configuration seems correct: https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#authentication

But exception shows that it didn't apply.

What GCS connector version do you use?

Also, may you try to set these configuration properties in Spark config files or on CLI using `--config` flag?

**Comment by leoneuwald** [comment]
Hi @medb,

I'm not defining any GCS connector version. I'm running with `--jars spark-bigquery-with-dependencies_2.11-0.17.0.jar`.

I tried to using --configs flags. But the result is the same.

**Comment by medb** [comment]
May you share a full command that you use to configure GCS connector auth using `--config` flag?

**Comment by leoneuwald** [comment]
Hi @medb ,

I tried it with two ways:

```
val spark = SparkSession.builder()
.appName("")
.config(new SparkConf()
        .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
        .set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
        .set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
        .set("fs.gs.project.id", <project_id>)
        .set("fs.gs.system.bucket", <bucket>)
        .set("fs.gs.auth.service.account.enable", "true")
        .set("fs.gs.auth.service.account.email", <email>)
        .set("fs.gs.auth.service.account.private.key.id", <key_id>)
        .set("fs.gs.auth.service.account.private.key", <key>))
      .master("")
      .getOrCreate()

OR

spark-submit --master yarn --deploy-mode cluster --queue default --driver-memory 1g --executor-memory 1g --executor-cores 1 --num-executors 1 --driver-java-options -Dhdp.version=3.1.0.0-78 --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:///logs/spark --conf spark.hadoop.yarn.timeline-service.enabled=false --conf spark.yarn.maxAppAttempts=1 --conf spark.yarn.submit.waitAppCompletion=true --conf spark.yarn.archive=hdfs:///<libdir>/spark-2.4.4.tar --conf spark.io.compression.codec=lz4 --conf spark.hadoop.yarn.timeline-service.enabled=false --conf spark.yarn.jars=hdfs:///<libdir>/spark-bigquery-with-dependencies_2.11-0.17.0.jar --conf spark.driver.extraClassPath=spark-bigquery-with-dependencies_2.11-0.17.0.jar --conf spark.executor.extraClassPath=spark-bigquery-with-dependencies_2.11-0.17.0.jar --conf spark.executor.extraJavaOptions=-Dhdp.version=3.1.0.0-78 --conf spark.driver.extraJavaOptions=-Dhdp.version=3.1.0.0-78 --conf fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --conf fs.gs.project.id=<project_id> --conf fs.gs.system.bucket=<bucket> --conf fs.gs.auth.service.account.enable=true --conf fs.gs.auth.service.account.email=<account_email> --conf fs.gs.auth.service.account.private.key.id=<private_key_id> --conf fs.gs.auth.service.account.private.key=-----BEGIN PRIVATE KEY-----<private_key>=\n-----END PRIVATE KEY----- --jars hdfs:///<lib_dir>/spark-bigquery-with-dependencies_2.11-0.17.0.jar --class <package>.Main hdfs:////<lib_dir>/myjar.jar -m yarn-cluster

**Comment by medb** [comment]
When you specify GCS connector properties through command line you need to add `spark.hadoop.` prefix to them (i.e. `--conf spak.hadoop.fs.gs.auth.service.account.enable=true`).

May you try if it fixes your issue?

**Comment by leoneuwald** [comment]
Yes. Tks @medb!

Can I submit a PR to add these details in README.md?

**Comment by medb** [comment]
It's mentioned in GCS connector instructions: https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md#configure-spark

Feel free to send PR to clarify this and/or add similar clarification to BQ Spark connector configuration.
