### ISSUE TITLE
Unable to specify location for temporary nor permanent gcs bucket

### ISSUE THREAD

**Issue by OatmealLick** [GoogleCloudDataproc/spark-bigquery-connector#231]
For example when calling:
```ds.write
      .format("bigquery")
      .option("partitionType", "DAY")
      .option("allowFieldAddition", "true")
      .option("temporaryGcsBucket", "some-bucket")
      .option("datePartition", "date")
      .mode(SaveMode.Overwrite)
      .save("project.dataset.table")
```

Bucket `some-bucket` is assumed to be in US region (even though eu-west-1 is the default for given project and service account is from eu-west1). However, there are service accounts (like this one) that cannot create anything in us location/region.

**Comment by Gaurangi94** [comment]
Hello,

It will be easier for me to debug this issue if you could share the following information:
1. Which region is your Dataproc cluster in?
2. Does the bucket in Europe exist or do you want it to be automatically created?
3. Could you share the stack trace of the error you get?

Thanks!

**Comment by OatmealLick** [comment]
1. Europe-west1
2. It does not exist.
3. Stacktrace:
```Exception in thread “main” com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.json.GoogleJsonResponseException: 412 Precondition Failed
POST https://storage.googleapis.com/storage/v1/b?project=XXX
{
 “code” : 412,
 “errors” : [ {
  “domain” : “global”,
  “location” : “If-Match”,
  “locationType” : “header”,
  “message” : “‘us’ violates constraint ‘constraints/gcp.resourceLocations’“,
  “reason” : “conditionNotMet”
 } ],
 “message” : “‘us’ violates constraint ‘constraints/gcp.resourceLocations’”
}
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:149)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:112)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:39)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.ResilientOperation$AbstractGoogleClientRequestExecutor.call(ResilientOperation.java:171)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:67)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.create(GoogleCloudStorageImpl.java:471)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.create(GoogleCloudStorageImpl.java:434)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.mkdirsInternal(GoogleCloudStorageFileSystem.java:476)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.mkdirs(GoogleCloudStorageFileSystem.java:418)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.mkdirs(GoogleHadoopFileSystemBase.java:1034)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2216)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.setupJob(FileOutputCommitter.java:369)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupJob(HadoopMapReduceCommitProtocol.scala:162)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:139)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:170)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:677)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:677)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:272)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:230)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:567)
...
```

**Comment by davidrabinowitz** [comment]
2. The bucket need to exist and the service account need to have the proper permissions to add and delete objects from it.

**Comment by Gaurangi94** [comment]
As pointed out by David, this seems to be an issue with your cloud storage setup. I tried reproducing this issue by having my entire setup in Europe, and by having temp-bucket in Europe and cluster in the US, but did not get any error.

Have you tried the exact same setup in any other region?

**Comment by OatmealLick** [comment]
Seems that we have some other setup (we cant change it too much because it’s our prod). I mean https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy those settings (inherited) cannot be changed. We have two options:
* add option to create temporaryGcsBucket in chosen zone
* point out option (in organization settings/polices) where to set default which is used by spark-bigquery-connector to create temporaryGcsBucket

Otherwise, we’re forced to create those temps in other tasks and we try to avoid that.

**Comment by Gaurangi94** [comment]
We will explore these two options and other ways to support your scenario, and get back to you.

**Comment by davidrabinowitz** [comment]
Hi @OatmealLick is the bucket already exist by the time the Spark process runs, or are you counting on the Spark process to create it?
