### ISSUE TITLE
Unable to read from Bigquery since 0.17.2 Update in Jupyter on Dataproc Spark

### ISSUE THREAD

**Issue by parthtapcart** [GoogleCloudDataproc/spark-bigquery-connector#244]
Using the standard method:

`df = spark.read.format("bigquery").load("[DATASET].[TABLE]")
`
This method will work just fine on 0.17.0, but NOT on 0.17.2, which was released yesterday. I haven't seen any updates to documentation, so I don't believe the syntax has changed. Below is the error that is thrown:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-2-5fc465fa785b> in <module>
      1 # Extract Raw Tables
----> 2 apps_df = spark.read.format("bigquery").load(bq_dataset+".tapcart_internalBi_apps_raw")
      3 # subscriptions_df = spark.read.format("bigquery").load(bq_dataset+".tapcart_internalBi_subscriptions_raw")
      4 # notifications_df = spark.read.format("bigquery").load(bq_dataset+".tapcart_internalBi_notifications_raw")
      5 # drops_df = spark.read.format("bigquery").load(bq_dataset+".tapcart_internalBi_drops_raw")

/usr/lib/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    176         self.options(**options)
    177         if isinstance(path, basestring):
--> 178             return self._df(self._jreader.load(path))
    179         elif path is not None:
    180             if type(path) != list:

/opt/conda/anaconda/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    129     def deco(*a, **kw):
    130         try:
--> 131             return f(*a, **kw)
    132         except py4j.protocol.Py4JJavaError as e:
    133             converted = convert_exception(e.java_exception)

/opt/conda/anaconda/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o60.load.
: java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/DataSourceOptions
	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.fromV1(SparkBigQueryConfig.java:117)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryConfig(BigQueryRelationProvider.scala:138)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:70)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:44)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.sources.v2.DataSourceOptions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more
```

Any clarification on the issue, or what I might be doing wrong, would be greatly appreciated.

PS: I have tried the following without success:

`df = spark.read.format("bigquery").load("[PROJECT-ID]:[DATASET].[TABLE]")
`

**Comment by davidrabinowitz** [comment]
Which Spark version is it? Unfortunately version 0.17.2 has a compatibility issue with Spark 3. Reverting to version 0.17.1 should solve this. This issue has been fixed in PR #242

**Comment by parthtapcart** [comment]
Ah! That's definitely it, as I am using Spark 3. Okay, will stick to 0.17.1. 

That being said, when I submit jobs to the cluster via Dataproc, if I'm using the 

`gs://spark-lib/bigquery/spark-bigquery-latest.jar`

Will that pull 0.17.2?

**Comment by davidrabinowitz** [comment]
No, we have reverted spark-bigquery-latest.jar to point to version 0.17.1 in order to better serve Spark 3 users.

**Comment by parthtapcart** [comment]
Ahh makes sense! Thank you!
