### ISSUE TITLE
Writing DataFrame to hadoop gives an Error

### ISSUE THREAD

**Issue by UtkarshPatkar** [GoogleCloudDataproc/spark-bigquery-connector#252]
I get the below error while saving the DataFrame to HDFS.

**_com.google.cloud.spark.bigquery.repackaged.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact_**

Below is my sbt file

>  libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-hive" % sparkVersion % "provided",
  "org.apache.hadoop" % "hadoop-client" % hadoopVersion % "provided",
  "com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.17.3"
)
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case "application.conf" => MergeStrategy.concat
  case "reference.conf" => MergeStrategy.concat
  case x => MergeStrategy.first
}

Appreciate any help on this.

**Comment by davidrabinowitz** [comment]
@UtkarshPatkar Can you please share a sample code?

**Comment by UtkarshPatkar** [comment]
Thanks for the quick response. I updated the merge strategy to include services folder:
```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", "services", xs @ _*)  => MergeStrategy.filterDistinctLines
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case "application.conf" => MergeStrategy.concat
  case "reference.conf" => MergeStrategy.concat
  case x => MergeStrategy.first
}
```
After this I am getting a different exception:
```
Exception in thread "main" java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:233)
        at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:414)
        at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:513)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:314)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
        at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ClientContext.create(ClientContext.java:166)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.stub.EnhancedBigQueryReadStub.create(EnhancedBigQueryReadStub.java:89)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryReadClient.<init>(BigQueryReadClient.java:129)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryReadClient.create(BigQueryReadClient.java:110)
        at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$.createReadClient(DirectBigQueryRelation.scala:354)
        at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$$anonfun$$lessinit$greater$default$3$1.apply(DirectBigQueryRelation.scala:44)
        at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation$$anonfun$$lessinit$greater$default$3$1.apply(DirectBigQueryRelation.scala:44)
        at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.scala:127)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)

```

The code is pretty straightforward. This works on spark shell. Only when I try to create a fat jar it has issues.

```
    spark.conf.set("credentials", "<<base64 encoded string>>")


    val outputDF = spark.read.format("com.google.cloud.spark.bigquery")
      .option("project", bqProject)
      .option("parentProject", bqProject)
      .option("dataset", bqDataset)
      .option("table", bqTable)
      .load()


    println(s"# of rows: ${outputDF.count()}")
    outputDF.write.format("parquet").mode("overwrite").saveAsTable("db.tablename")
```

**Comment by davidrabinowitz** [comment]
Which Java, Scala and Spark version are you using?

**Comment by UtkarshPatkar** [comment]
Java: 1.8
Scala: 2.11.12
Spark 2.4.0

**Comment by UtkarshPatkar** [comment]
Let me know if you need any other information on this.

**Comment by UtkarshPatkar** [comment]
Any update on this?

**Comment by davidrabinowitz** [comment]
Please update to the latest version (0.18.0). Also please make sure that the `META-INF/native/` directory is untouched.
