### ISSUE TITLE
Why no support for external table ? 

### ISSUE THREAD

**Issue by richiesgr** [GoogleCloudDataproc/spark-bigquery-connector#255]
Hi
I'm trying the connector to BQ when I try to request a table defined as External I get 
`java.lang.UnsupportedOperationException: The type of table measurement-dev.facts.FactExt is currently not supported: EXTERNAL
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:89)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:45)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
  at com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
`

So it's very explicit my question is why ?

**Comment by davidrabinowitz** [comment]
The Spark BigQuery connector is using the BigQuery Storage API in order to efficiently read the data in a distributed manner. This API does not support external tables, and that's why the connector does not support them as well for the moment. It is on our roadmap to add support for them.
