### ISSUE TITLE
UnsupportedOperationException when I try to read EXTERNAL BigQuery tables.

### ISSUE THREAD

**Issue by andretadeu** [GoogleCloudDataproc/spark-bigquery-connector#257]
Hi!

I am trying to read an external table on BigQuery using **spark-bigquery-connector**, using the following components:

- Apache Spark 2,4,7
- Java 8.0.265 HotSpot from AdoptJDK
- Scala 2.11.12
- Gradle 6.6.1
- spark-bigquery-with-dependencies_2.11, version 0.17.3

And this is the result:

```
Exception in thread "main" java.lang.UnsupportedOperationException: The type of table <projectId>.<dataset>.<table> is currently not supported: EXTERNAL
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:88)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:45)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
	at com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
	at ex.dataproc.CalcVarsApp$.main(CalcVarsApp.scala:52)
	at ex.dataproc.CalcVarsApp.main(CalcVarsApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
where **<projectId>.<dataset>.<table>** were redacted. Examining this table at BigQuery console:

Table info 
  Table ID: <projectId>.<dataset>.<table>
  Table size: 0 B
  Number of rows: 0
  Created: Oct 20, 2020, 8:32:52 PM
  Table expiration: Never
  Last modified: Oct 20, 2020, 8:32:52 PM
  Data location: US

External Data Configuration
  Source URI(s): [REDACTED]
  Auto-detect schema: false
  Ignore unknown values: false
  Source format: AVRO
  Max bad records: 0

I read the code and it seems to be a feature that is missing.

**Comment by davidrabinowitz** [comment]
Duplicate of issue #255
