### ISSUE TITLE
Unable to write to DateTime datatype column from Spark Java

### ISSUE THREAD

**Issue by arunkindra** [GoogleCloudDataproc/spark-bigquery-connector#293]
I have a partitioned table where one of the column is of type DateTime and the table is partitioned on same column. According to spark-bigquery documentation, the corresponding Spark SQL type is of String type.

**Code Snippet:**
ZonedDateTime nowPST = ZonedDateTime.ofInstant(Instant.now(), TimeZone.getTimeZone("PST").toZoneId());
        df = df.withColumn("createdDate", lit(nowPST.toLocalDateTime().toString()));

**Error:**

Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Failed to load to <PROJECT_ID>:<DATASET_NAME>.<TABLE_NAME> in job JobId{project=<PROJECT_ID>, job=<JOB_ID>, location=US}. BigQuery error was Provided Schema does not match Table <PROJECT_ID>:<DATASET_NAME>.<TABLE_NAME>. Field createdDate has changed type from DATETIME to STRING
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:156)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:89)
        ... 36 more

**Dependencies:**
<dependency>
            <groupId>com.google.cloud.spark</groupId>
            <artifactId>spark-bigquery-with-dependencies_2.11</artifactId>
            <version>0.17.3</version>
</dependency>

**Comment by davidrabinowitz** [comment]
Unfortunately as Spark does not support DateTime as a data type, we cannot write it directly into BigQuery. The way to do it is to write is a String into a temporary table and then run an `INSERT INTO .... SELECT ...` job on BigQuery.
