### ISSUE TITLE
Unable to use the connector on Dataproc image 2.0

### ISSUE THREAD

**Issue by richiesgr** [GoogleCloudDataproc/spark-bigquery-connector#327]
Hi
Struggling to get the connector running on Dataproc image 2.0
Scala is 2.12 Spark is 3.1.1

So First I try to use it in JupyterLab installed on the dataproc like in documentation:
```
from pyspark.sql import SparkSession
spark = SparkSession
.builder
.config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar')
.enableHiveSupport().getOrCreate()

bucket = "xxx"
spark.conf.set('temporaryGcsBucket', bucket)

df.write.format('bigquery') \
  .option('table', 'mytable') \
  .save()
``` 
It seems that the connector jar is not loaded in Spark Session at all So I get the well know
```
java.lang.ClassNotFoundException: bigquery.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:663)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:663)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:663)
```  

Now Of course I try to put the jar into the dataproc cluster itself using:

- Initialisation Script (copying the jar into /usr/lib/spark/jars) => this break spark completely meaning pyspark is not able anymore to open a yarn process. (may be the fat jar of the connector includes some other package)
-  using --properties from dataproc command line like 
```
--properties 'spark:spark.jars=gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar'
```
The result is the same Spark broke again

Do you have any solution or something not documented may be not use the fat jar ...

Best Regards

**Comment by davidrabinowitz** [comment]
Please add the following at the beginning of your code:
```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar pyspark-shell'
```

**Comment by richiesgr** [comment]
Sorry to bother you 
but even with your recommendation it's not working 
all my code 

```
from pyspark.sql import SparkSession
import pyspark
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar pyspark-shell'
conf = pyspark.SparkConf() 
conf = conf.set('spark.jars.packages', 'com.google.cloud.spark:spark-bigquery_2.12:0.19.0')
spark = SparkSession.builder.config(conf=conf).getOrCreate()
bucket = "dv-dataproc-temp"
spark.conf.set('temporaryGcsBucket', bucket)

df.write.format('bigquery') \
  .option('table', 'facts.agg_result') \
  .save()
```

do you see something wrong ?
Thanks

**Comment by davidrabinowitz** [comment]
You can pre-install the connector by re-creating the cluster with the following parameters:
```
REGION=<region>
CLUSTER_NAME=<cluster_name>
gcloud dataproc clusters create ${CLUSTER_NAME} \
    --region ${REGION} \
    --initialization-actions gs://goog-dataproc-initialization-actions-${REGION}/connectors/connectors.sh \
    --metadata spark-bigquery-connector-version=0.19.1 \
    ... other params ...
```

Here the connector will be part of the spark classpath and no additional config (`--jars`, `spark.jars`, etc.) is needed
