### ISSUE TITLE
Having trouble running the example

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [GoogleCloudDataproc/spark-bigquery-connector#330]
```scala
spark.conf.set("viewsEnabled","true")
spark.conf.set("materializationDataset","<dataset>")

sql = """
  SELECT tag, COUNT(*) c
  FROM (
    SELECT SPLIT(tags, '|') tags
    FROM `bigquery-public-data.stackoverflow.posts_questions` a
    WHERE EXTRACT(YEAR FROM creation_date)>=2014
  ), UNNEST(tags) tag
  GROUP BY 1
  ORDER BY 2 DESC
  LIMIT 10
  """
df = spark.read.format("bigquery").load(sql)
df.show()
```

I'm trying to run this example and it fails with error "Must match '^(((\S+)[:.])?(\w+)\.)?([\S&&[^.:]]+)$$'"

I tried passing the table name directly to load function and it works. 

Also, the same happens when I use .option("query", sql). It throws a must match error. I copied the below example from the integration tests in this repo and I still get the same error. 

I'm using 0.19.1 version of the connector
```scala
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Table ID 'SELECT corpus, corpus_date FROM `bigquery-public-data:samples.shak
espeare` WHERE word='spark' AND 'bigquery'='bigquery''. Must match '^(((\S+)[:.])?(\w+)\.)?([\S&&[^.:]]+)$$'
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryUtil.parseTableId(BigQueryUtil.java:101)
        at com.google.cloud.spark.bigquery.SparkBigQueryConfig.from(SparkBigQueryConfig.java:136)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryConfig(BigQueryRelationProvider.scala:139)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:71)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:45)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:232)
```

**Comment by davidrabinowitz** [comment]
Can you please share more details about the execution environment? Here is my run from a Dataproc image 1.4 (Spark 2.4.7):
```
$ pyspark --jars gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.11-0.19.1.jar
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/03/04 19:37:16 WARN org.apache.spark.scheduler.FairSchedulableBuilder: Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure pools in fairscheduler.xml or set spark.scheduler.allocation.file to a file that contains the configuration.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.7
      /_/

Using Python version 3.6.12 (default, Sep  8 2020 23:10:56)
SparkSession available as 'spark'.
>>> spark.conf.set("viewsEnabled","true")
>>> spark.conf.set("materializationDataset","davidrab")
>>> sql = """
  SELECT tag, COUNT(*) c
  FROM (
    SELECT SPLIT(tags, '|') tags
    FROM `bigquery-public-data.stackoverflow.posts_questions` a
    WHERE EXTRACT(YEAR FROM creation_date)>=2014
  ), UNNEST(tags) tag
  GROUP BY 1
  ORDER BY 2 DESC
  LIMIT 10
  """
>>> sql
"\n  SELECT tag, COUNT(*) c\n  FROM (\n    SELECT SPLIT(tags, '|') tags\n    FROM `bigquery-public-data.stackoverflow.posts_questions` a\n    WHERE EXTRACT(YEAR FROM creation_date)>=2014\n  ), UNNEST(tags) tag\n  GROUP BY 1\n  ORDER BY 2 DESC\n  LIMIT 10\n  "
>>> df = spark.read.format("bigquery").load(sql)
>>> df.show()
+----------+-------+                                                            
|       tag|      c|
+----------+-------+
|javascript|1643617|
|    python|1352904|
|      java|1218220|
|   android| 913638|
|       php| 911806|
|        c#| 905331|
|      html| 769499|
|    jquery| 608071|
|       css| 510343|
|       c++| 458938|
+----------+-------+

>>> 
```
Also, the query in the error is one form the integration tests, not the one in the example.

**Comment by ArulselvanMadhavan** [comment]
@davidrabinowitz Thanks for the response! I was using spark 3.0.1. I think there may have been a collision with gcs-hadoop connector that was in my runtime. I removed that and things seemed to work. For now, I think we can close this.
