### ISSUE TITLE
[spark 2.4.5][bqco 0.19.1] code example in doc not working

### ISSUE THREAD

**Issue by Jsebayhi** [GoogleCloudDataproc/spark-bigquery-connector#332]
Hi, we have an unexpected situation.

Using spark 2.4.5
with the version 0.19.1 of the bq connector

The doc says this in the `datePartition` section:
```
The date partition the data is going to be written to. Should be given in the format YYYYMMDD. Can be used to overwrite the data of a single partition, like this: df.write.format("bigquery")   .option("datePartition", "YYYYMMDD")   .mode("overwrite")   .save("table")
(Optional). On write only.
```

But when we do it:
```
  private val dateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMdd")
  private def formatDate(date: ZonedDateTime): String = {
    date.format(dateTimeFormatter)
  }
def write[T](
    dst: BigQueryDstTable,
    businessDate: ZonedDateTime)(data: Dataset[T])(implicit ev: Encoder[T]): Try[Unit] = Try {
    import spark.sqlContext.implicits._
    import org.apache.spark.sql.functions._

    data
      .write
      .format("bigquery")
      .option("createDisposition", dst.createIfNotExist.value)
      .option("allowFieldAddition", "true")
      .option("temporaryGcsBucket", dst.temporaryGcsBucket)
      .option("datePartition", formatDate(businessDate))
      .mode("overwrite")
      .save(s"${dst.dataset}.${dst.table}")
  }
```

We get the following exception:
```
Exception in thread "main" java.lang.RuntimeException: job failed
Caused by: java.lang.RuntimeException: Failed to write to BigQuery
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: The field specified for partitioning cannot be found in the schema.
```

full stack trace:
```
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
05-03-2021 13:41:07 CET app INFO - Caused by: java.lang.RuntimeException: Failed to write to BigQuery
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:92)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:113)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:696)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:80)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:310)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
05-03-2021 13:41:07 CET app INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.bigquery.SparkBigQueryDataFrameWriter.$anonfun$write$1(BigQueryDataFrameWriter.scala:62)
05-03-2021 13:41:07 CET app INFO - 	at scala.util.Try$.apply(Try.scala:213)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.bigquery.SparkBigQueryDataFrameWriter.write(BigQueryDataFrameWriter.scala:40)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.job.Pipeline$.writeTradeItemOfferToBigQuery(Pipeline.scala:59)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.job.TradeItemOfferComputer$.$anonfun$getComputationProcedure$2(TradeItemOfferComputer.scala:26)
05-03-2021 13:41:07 CET app INFO - 	at scala.util.Success.flatMap(Try.scala:251)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.job.TradeItemOfferComputer$.$anonfun$getComputationProcedure$1(TradeItemOfferComputer.scala:23)
05-03-2021 13:41:07 CET app INFO - 	at scala.util.Success.flatMap(Try.scala:251)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.job.TradeItemOfferComputer$.getComputationProcedure(TradeItemOfferComputer.scala:22)
05-03-2021 13:41:07 CET app INFO - 	at com.carrefour.phenix.offers.sale.assortment.computer.app.Boot$.delayedEndpoint$com$carrefour$phenix$offers$sale$assortment$computer$app$Boot$1(Boot.scala:45)
05-03-2021 13:41:07 CET app INFO - 	... 22 more
05-03-2021 13:41:07 CET app INFO - Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: The field specified for partitioning cannot be found in the schema.
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:411)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:248)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:179)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$lzycompute$1(BigQueryWriteHelper.scala:152)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$1(BigQueryWriteHelper.scala:152)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:176)
05-03-2021 13:41:07 CET app INFO - 	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:89)
05-03-2021 13:41:07 CET app INFO - 	... 53 more
```

We tried specifying the columns _PARTITIONDAY but we encountered another error saying we are not allowed to specify a column containing a _.

The only way we could make something work is by doing this:
```
  private val dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
  private def formatDate(date: ZonedDateTime): String = {
    date.format(dateTimeFormatter)
  }

def write[T](
    dst: BigQueryDstTable,
    businessDate: ZonedDateTime)(data: Dataset[T])(implicit ev: Encoder[T]): Try[Unit] = Try {
    import spark.sqlContext.implicits._
    import org.apache.spark.sql.functions._

    data
      .withColumn("businessDate", lit(formatDate(businessDate)).cast("date"))
      .write
      .format("bigquery")
      .option("createDisposition", dst.createIfNotExist.value)
      .option("allowFieldAddition", "true")
      .option("temporaryGcsBucket", dst.temporaryGcsBucket)
      .option("datePartition", "20210302")// <= this is being completely ignored...
      .option("partitionField", "businessDate")
      .option("partitionType", "DAY")
      .mode("overwrite")
      .save(s"${dst.dataset}.${dst.table}")
```
But we do not want to add this businessDate column to our schema, we want to use the default internal bigquery _PARTITONDATE column. Also, the fact that the date being provided to the `datePartition` option is ignored is very, very weird.

Did we misunderstand something in the doc ?

**Comment by davidrabinowitz** [comment]
`_PARTITONDATE` is used for ingestion time partitioning, and cannot be controlled by the user (See [1](https://cloud.google.com/bigquery/docs/creating-partitioned-tables), [2](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#ingestion-time_partitioned_table_pseudo_columns)). If you want a date partitioning you can control then use a regular `date` field.

**Comment by BastienBigue** [comment]
Thank you for your answer @davidrabinowitz
But then, I don't understand what is the purpose of the `datePartition` option.
From the documentation, I would have expected that specifying `.option("datePartition", "20210318")` (without any column of my data used as a partitioning column) would write my data to the given partition "20210318", the same way as when, with bq CLI, we specify the ingestion-time partition (like [this](https://cloud.google.com/bigquery/docs/creating-partitioned-tables#creating_an_ingestion-time_partitioned_table_when_loading_data))
But apparently I am missing something.

**Comment by BastienBigue** [comment]
Problem solved
