### ISSUE TITLE
connector stucks and does not fails by itself

### ISSUE THREAD

**Issue by kumgaurav** [GoogleCloudDataproc/spark-bigquery-connector#333]
One of my spark job was running from last 10 days which generally does not take more than 30-40 minutes. Need help to understand

 why it did not get terminated by itself. I do not see any scala configuration where we set timeout period for bigquery. what can be do to avoid this kind of situation.

Below is the log for the application:
```
21/02/22 00:26:23 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Created read session for table 'ite-aia-dp._c9ed711d96d74023efa414071f2ff98e4fbf52e2.anon526e81dc_a9f6_476f_9de1_3bc31452edfc': projects/ite-aia-dp/locations/us/sessions/CAISDG1PeFNGVjdxX2c5LRoCbmEaAm9zGgJqcRoCanIaAm93GgJpchoCamMaAmpzGgJqZBoCb2oaAml3
21/02/22 00:26:23 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Created read session for table 'ite-aia-dp._c9ed711d96d74023efa414071f2ff98e4fbf52e2.anondccd3e19_fc32_4f9a_9fc0_227a2629a47c': projects/ite-aia-dp/locations/us/sessions/CAISDEUzTmJ5RHh4Mi1TSRoCbmEaAm9zGgJqcRoCanIaAm93GgJpchoCamMaAmpzGgJqZBoCb2oaAml3
21/02/22 00:26:23 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Created read session for table 'ite-aia-dp._c9ed711d96d74023efa414071f2ff98e4fbf52e2.anon526e81dc_a9f6_476f_9de1_3bc31452edfc': projects/ite-aia-dp/locations/us/sessions/CAISDHpodi1NeEJVYjZRWRoCbmEaAm9zGgJqcRoCanIaAm93GgJpchoCamMaAmpzGgJqZBoCb2oaAml3
21/02/22 00:46:00 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 315.0 in stage 23.0 (TID 2736, dp-dproc-w-23.c.ite-aia-dp.internal, executor 38): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:288)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:198)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:197)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection timed out (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:920)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:884)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:706)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:230)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:209)
	at org.conscrypt.ConscryptEngineSocket.waitForHandshake(ConscryptEngineSocket.java:547)
	at org.conscrypt.ConscryptEngineSocket.getOutputStream(ConscryptEngineSocket.java:290)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:465)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:142)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1011)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.execute(BatchHelper.java:175)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.lambda$queue$0(BatchHelper.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

Job output is complete
```
Equivalent: 

 etl_saplookup_bq_02-22-2021T000306_132bbc03
Start time:
Feb 21, 2021, 4:03:07 PM
Elapsed time:
10 days 21 hr
Status:
Canceled
Region
us-central1
Cluster
dp-dproc
Job type
Spark
Main class or jar
com.paloaltonetworks.sap.CreateSapTableForLookup
Jar files
gs://ite-aia-dp/BaxterOutputHelper/jars/BaxterOutputHelper-1.0-SNAPSHOT.jar
gs://spark-lib/bigquery/spark-bigquery_2.11-0.10.0-beta-shaded.jar
Properties
spark.executor.cores
4
spark.executor.memoryOverhead
4098
spark.yarn.am.memory
4098
Arguments
sap.conf
Labels
airflow-ve... : v1-10-12-a...
Equivalent:

**Comment by kumgaurav** [comment]
one more clarification read me says beta , is BQ connector is still in beta.

**Comment by davidrabinowitz** [comment]
Can you please try with the latest version - gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.11-0.19.1.jar ?
Also, can you please share the version of dataproc image, JVM , spark and scala?

**Comment by kumgaurav** [comment]
Sorry for late reply, dependent on admins for info . I can try the latest jar but it hard to reproduce, I am running this program from almost last 8-9 months , saw this error first time.
Here is the requested info-
dataproc version : 1.3.84-debian10
spark : 2.3.4
scala : 2.11.8
java :  1.8

**Comment by davidrabinowitz** [comment]
Try to increase the following timeout configurations:
```
fs.gs.http.connect-timeout
fs.gs.http.read-timeout
``` 
By default they are set to 20000 (20 seconds)
