### ISSUE TITLE
Error writing to BQ from Pyspark on Dataproc (bigquery.DefaultSource does not allow create table as select)

### ISSUE THREAD

**Issue by yoavgal10** [GoogleCloudDataproc/spark-bigquery-connector#337]
I'm trying to write a table to BQ from a Pyspark app running on Dataproc.
The table does not exist at the time if the write.

Code:

```df_data_types_adjusted. \
            write. \
            format('com.google.cloud.spark.bigquery'). \
            option("datePartition", "YYYYMMDD"). \
            option("partitionField", partition_column). \
            option("partitionExpirationMs", 365 * 24 * 60 * 60 * 1000). \
            option("table", %s.%s.%s % (project_id, dataset_id, table_id)). \
            option("create_table", "true"). \
            mode("overwrite"). \
            save()
```

Cluster properties

```
cluster_properties = {
    'spark:spark.sql.execution.arrow.enabled': 'true',
    'spark:spark.jars':
        'gs://spark-lib/bigquery/spark-bigquery-latest_2.11.jar',
    'spark:spark.jars.packages':
        'com.google.cloud.spark:spark-bigquery_2.11:0.8.1-beta',
}
```

Error message:
```
21/03/11 16:34:11 WARN org.apache.spark.util.Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.
dump finished. runtime: 11.181494
Traceback (most recent call last):
  File "/tmp/***.py", line 206, in <module>
    args.output_table, args.partition_column, args.date)
  File "/tmp/***.py", line 181, in main
    mode("overwrite"). \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 734, in save
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o332.save.
: java.lang.RuntimeException: com.google.cloud.spark.bigquery.DefaultSource does not allow create table as select.
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:526)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:281)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

21/03/11 16:34:22 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@65f92ea9{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
```

The cluster's service account has editor permissions on the destination BQ project
Any ideas?

**Comment by davidrabinowitz** [comment]
Notice you import the connector twice, once in `spark.jars` and once in `spark.jars.packages` - which refers to a very old version of the connector. Please remove the `spark.jars` parameter, and change the `spark.jars.packages` to `com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.19.1`.
