### ISSUE TITLE
[Question] Version conflict with Apache Arrow

### ISSUE THREAD

**Issue by maasg** [GoogleCloudDataproc/spark-bigquery-connector#343]
We're using Apache Arrow 3.0 in our project. When trying to run a job with the spark-bigquery-connector, I get the following error:
```
Caused by: java.lang.NoSuchMethodError: 'io.netty.buffer.ArrowBuf org.apache.arrow.vector.VarCharVector.getOffsetBuffer()'
	at com.google.cloud.spark.bigquery.ArrowSchemaConverter$StringAccessor.getUTF8String(ArrowSchemaConverter.java:389)
	at com.google.cloud.spark.bigquery.ArrowSchemaConverter.getUTF8String(ArrowSchemaConverter.java:116)
	at org.apache.spark.sql.execution.vectorized.MutableColumnarRow.getUTF8String(MutableColumnarRow.java:135)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$2.hasNext(WholeStageCodegenExec.scala:636)
```
I see that the connector is using Apache Arrow 0.16. 
Is there any workaround possible?  I'm kind of stuck. 

Thanks!

**Comment by davidrabinowitz** [comment]
Can you please share the Java and Spark versions?

**Comment by maasg** [comment]
Thanks for the response, David.
Here's the data:

Java 11, Spark 2.4.5
Connector version: "com.google.cloud.spark:spark-bigquery_2.12:0.19.1"

I also tried the 'fat jar' "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.19.1"
But then I get:
```
java.lang.ExceptionInInitializerError
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.11.3
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:64)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:51)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:819)
	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
```
BTW, I tried compiling the connector using Java 8 as you suggested, but the `assembly` task gets many 'duplicate file' errors. 
I tried tweaking the `mergeStrategy` rules but it looked like it had no effect on the error. Puzzling.

**Comment by davidrabinowitz** [comment]
When compiling you can run `sbt publishM2` and get the uber jar from the local maven repo. I'll check the jackson issue.

**Comment by maasg** [comment]
Thanks, @davidrabinowitz 
I forced the jackson versions to match the version in Spark 2.4.5 and it's working now.
```
implementation('com.fasterxml.jackson.core:jackson-databind') {
        version {
            strictly '2.6.7.3'
        }
    }
implementation('com.fasterxml.jackson.core:jackson-core') {
        version {
            strictly '2.6.7'
        }
    }
```
