### ISSUE TITLE
Field <Field> has changed mode from REQUIRED to NULLABLE

### ISSUE THREAD

**Issue by raviranjankumarsinha** [GoogleCloudDataproc/spark-bigquery-connector#356]
I have manually created Table with column as REQUIRED and the type of the column is String, when i am trying to write RDD to Bigquery Table i am getting error "Field <Field> has changed mode from REQUIRED to NULLABLE", so how can i fix without changing column Type From REQUIRED to NULLABLE?

**Comment by jtvmatos** [comment]
Hi,

More information is needed to assess whether there is a problem with the connector. Apparently, your spark job is creating intermediate files with a nullable schema, which is incompatible with the bigquery schema.

may be related with #https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/116

what is the intermediate format used?

**Comment by raviranjankumarsinha** [comment]
Actually, if table does not exists, it creates the bigquery table(its good) and all STRING Column it makes as Nullable, but when we manually creates the table with String Column Not null and use the connector to write the data  it gives error. 

Please find below stack trace error.

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:686)
Caused by: java.lang.RuntimeException: Failed to write to BigQuery
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:82)
        at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:112)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:305)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)

        ... 5 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table Field corpId has changed mode from REQUIRED to NULLABLE
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:411)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:248)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:179)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$lzycompute$1(BigQueryWriteHelper.scala:152)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.com$google$cloud$spark$bigquery$BigQueryWriteHelper$$finishedJob$1(BigQueryWriteHelper.scala:152)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:176)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:89)
        ... 31 more

Exception in thread "main" org.apache.spark.SparkException: Application application_1617200614606_0017 finished with failed status
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:1151)
        at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1531)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by davidrabinowitz** [comment]
Can you verify that the nullable flag of the `corpId` field in the Dataframe and in BigQuery are the same?

**Comment by raviranjankumarsinha** [comment]
corpId i put as REQUIRED while creating table in Bigquery and in Bean class i created Property as private String corpId;

When i change corpId as NULLABLE in table it works fine, but it means that i cannot create any String column as REQUIRED in table and write the data the dataframe, so i force to change all the String Field as NULLABLE in Bigquery table

**Comment by davidrabinowitz** [comment]
Spark treats unknown Strings as nullable as they can receive `null` values. Can you  please share the output of `df.printSchema()`. Also, you may want to consult with this [StackOverflow question](https://stackoverflow.com/questions/33193958/change-nullable-property-of-column-in-spark-dataframe)
