### ISSUE TITLE
Unable to support ARM architecture cluster

### ISSUE THREAD

**Issue by jackylam0812** [GoogleCloudDataproc/spark-bigquery-connector#359]
I am facing a problem when running the AWS EMR with r6g.xlarge(ARM) spark cluster connected to Bigquery.
But there is normal and no any problems in m5.xlarge(x86).

Is there any compatible issue between ARM and this connector?

The symptom is when running df.show() after get the tables, there will hang up there, and wait for a while it will prompt error as follow: 
```
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:533)
  ... 14 more
Caused by: com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: bigquerystorage.googleapis.com/2607:f8b0:4004:829:0:0:0:200a:443
Caused by: java.net.SocketException: Network is unreachable
  at sun.nio.ch.Net.connect0(Native Method)
  at sun.nio.ch.Net.connect(Net.java:482)
  at sun.nio.ch.Net.connect(Net.java:474)
  at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:91)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:88)
  at java.security.AccessController.doPrivileged(Native Method)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:88)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:315)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:248)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:150)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at com.google.cloud.spark.bigquery.repackaged.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
  Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
    at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
    at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
    at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryReadClient.createReadSession(BigQueryReadClient.java:230)
    at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.scala:134)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:323)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:323)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:356)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:355)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:433)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:351)
    at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:319)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:100)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:90)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:106)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:105)
    at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3388)
    at org.apache.spark.sql.Dataset.head(Dataset.scala:2553)
    at org.apache.spark.sql.Dataset.take(Dataset.scala:2767)
    at org.apache.spark.sql.Dataset.getRows(Dataset.scala:256)
    at org.apache.spark.sql.Dataset.showString(Dataset.scala:293)
    at org.apache.spark.sql.Dataset.show(Dataset.scala:754)
    at org.apache.spark.sql.Dataset.show(Dataset.scala:713)
    at org.apache.spark.sql.Dataset.show(Dataset.scala:722)
root
 |-- word: string (nullable = false)
 |-- word_count: long (nullable = false)
 |-- corpus: string (nullable = false)
 |-- corpus_date: long (nullable = false)
```

Here is the scala file what I ran:
```
import com.google.cloud.spark.bigquery.BigQueryDataFrameReader
import org.apache.spark.sql._

val table = "bigquery-public-data.samples.shakespeare"
val token = <mytoken>

// load data from BigQuery
val df = spark.read.format("bigquery").option("table", table).option("parentProject", "jacky-gcct-demo").option("gcpAccessToken", token).load()
df.show()
df.printSchema()
df.createOrReplaceTempView("words")
```

**Comment by isha97** [comment]
Hi @jackylam0812 ,

I tried the connector on `2.1-ubuntu20-arm` dataproc image and it worked as expected.
So, the connector is compatible with the ARM version. Please reopen if you are still facing the issue.
