### ISSUE TITLE
"Failed to find data source: bigquery" error with jupyter notebook examples

### ISSUE THREAD

**Issue by ShobhaRaniD** [GoogleCloudDataproc/spark-bigquery-connector#388]
- The [readme doc](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#using-in-jupyter-notebooks) states that the connector can be used in Jupyter notebooks even if it is not installed on the Spark cluster. 
- But that isn't the case since we run into the error listed below with the [example](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/examples/notebooks/Top%20words%20in%20Shakespeare%20by%20work.ipynb) provided.
- We have found that the issue is similar to this [SO post](https://stackoverflow.com/questions/55739463/cant-add-jars-pyspark-in-jupyter-of-google-dataproc?answertab=votes#tab-top) where Spark does not support dynamically adding jars into the driver classpath.
- Manually copying the jar into the "/usr/lib/spark/jars" folder on the cluster resolves this.

Can we get more insights into this and update the readme doc accordingly?

```
java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:678)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:213)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:652)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:652)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:652)
	... 13 more
```
![image](https://user-images.githubusercontent.com/17057701/117089915-7b37d400-ad74-11eb-99d4-052149a3f6a0.png)

**Comment by davidrabinowitz** [comment]
Is it a pyspark kernel or a python one? in pyspark jupyter builds the spark session for you and in this point you cannot add additional jars. Moving to a python kernel should solve it.

In addition, which scala version is used in spark? The link you are using is for Scala 2.11, for Scala 2.12 please use `gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar`

**Comment by jgraves-clgx** [comment]
> Is it a pyspark kernel or a python one? in pyspark jupyter builds the spark session for you and in this point you cannot add additional jars. Moving to a python kernel should solve it.
> 
> In addition, which scala version is used in spark? The link you are using is for Scala 2.11, for Scala 2.12 please use `gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar`

Hi David, I am the one who brought up this issue. This is on a 1.4 dataproc cluster so we are using the 2.11 jar. 

Does this mean that pyspark kernels are not able to utilize the BQ connector unless it is already downloaded in the spark jar directory on the cluster?

**Comment by davidrabinowitz** [comment]
pyspark kernels are not able to change their classpath in runtime, therefore it means they cannot use any external jars or packages in runtime, including the BigQuery connector.

So the two ways to overcome this spark limitation are:
* Preinstall the connector (as you've mentioned), placing it in the Spark's classpath from the get go;
* Use the python kernel, which does not initialise the Spark context and session for you, giving you more freedom for their configuration.

**Comment by gomrinal** [comment]
Resolution:
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/963
