### ISSUE TITLE
Connecting using NonDataproc Spark failed

### ISSUE THREAD

**Issue by batawfic** [GoogleCloudDataproc/spark-bigquery-connector#423]
Spark version 2.4.3
Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_292
Branch heads/v2.4.3

code
```
my_jar = glob('/BigQuery/spark-bigquery-with-dependencies_2.11-0.21.1.jar')
my_jar_str = ','.join(my_jar)

my_jar = glob('/BigQuery/01_googlehadoop/gcs-connector-hadoop2-2.1.0.jar')
my_jar_str = my_jar_str + ',' + ','.join(my_jar)

print(my_jar_str)

spark = SparkSession \
    .builder \
    .master('local') \
    .appName('spark-read-from-bigquery') \
    .getOrCreate()



spark.conf.set("spark.jars", my_jar_str)
spark.conf.set("project", "project_ID")
spark.conf.set('credentialsFile', "/secrets/etl.json")

# Use the Cloud Storage bucket for temporary BigQuery export data used
# by the connector.
bucket = "bigquery-gs-landing"
spark.conf.set('temporaryGcsBucket', bucket)

my_query = '''select * from project_ID:test.test limit 10'''


# Load data from BigQuery.
df = spark.read.format('bigquery') \
  .option("query", my_query) \
  .load()

df.printSchema()
```

**Error**:

```
File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o35.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
        at scala.util.Try.orElse(Try.scala:84)
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:634)
        ... 13 more
```

please NOTE that this standalone spark version

**Comment by davidrabinowitz** [comment]
You need to add the `spark.jars to the configuration **before** creating the session:
```
spark = SparkSession \
    .builder \
    .master('local') \
    .appName('spark-read-from-bigquery') \
    . config('spark.jars', my_jar_str)
    .getOrCreate()
```

BTW, is it running on a single machine or on a cluster?

**Comment by batawfic** [comment]
Thank you so much for getting back to me. Yes I was trying this code on single machine (spark image).
Your suggestion eliminate the error. Does it means I should remove this useless line

```
spark.conf.set("spark.jars", my_jar_str)
```

There is another one about views although I'm not querying any view
```
: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Views are not enabled. You can enable views by setting 'viewsEnabled' to true. Notice additional cost may occur.
```

I will try to dig into

**Comment by batawfic** [comment]
I got everything worked. Thank you again
