### ISSUE TITLE
Cannot write to BIGNUMERIC

### ISSUE THREAD

**Issue by Skargonas** [GoogleCloudDataproc/spark-bigquery-connector#432]
When writing from Spark, if we write a dataframe that has any DecimalType that wouldn't fit in a BigQuery NUMERIC (scale bigger than 9), we get an error like:
```
Caused by: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:71)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:85)
	...
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Failed to load to [...] in job [...]. BigQuery error was Error while reading data, error message: The value for column 'f4' is out of valid NUMERIC range: Value will lose precision after scaling down to NUMERIC type; input length: 9; scale: 15; input data: 00002b12383f5bdf79
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:142)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:77)
	...
```

**Comment by davidrabinowitz** [comment]
BigQuery NUMERIC has a scale of 9. Your data has a finer scale than this at 15. If you can reduce the scale to 9, your data should be saved without a problem. If you need a scale of 15, you can save it as String or bytes and make the necessary conversions before writing/after reading.

In a short while we will release the BIGNUMERIC support, so you will be able to save your numbers in scale of up to 38.

**Comment by Skargonas** [comment]
> In a short while we will release the BIGNUMERIC support, so you will be able to save your numbers in scale of up to 38.

- Can you specify exactly what kind of support will be added? I took a look at #404 and it seemed to me that only added support for reading BIGNUMERIC, not for writing to them; am I right about that?
- What I'd be suggesting is that when the Spark dataframe column type has a scale bigger than 9, use BIGNUMERIC instead of NUMERIC. Could that be done?
