### ISSUE TITLE
Cannot query `project-id.data_set.INFORMATION_SCHEMA.TABLES` due to rigid name parsing

### ISSUE THREAD

**Issue by chajath** [GoogleCloudDataproc/spark-bigquery-connector#434]
As a workaround to #433 I'm looking to query `INFORMATION_SCHEMA.TABLES`. However, doing so generates the following `400` error:

```
[error] {
[error]   "code" : 400,
[error]   "errors" : [ {
[error]     "domain" : "global",
[error]     "message" : "Invalid project ID 'project_id:data_set'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.",
[error]     "reason" : "invalid"
[error]   } ],
[error]   "message" : "Invalid project ID 'project_id:data_set'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.",
[error]   "status" : "INVALID_ARGUMENT"
[error] }
```

Can we workaround this hardwired assumption and query `INFORMATION_SCHEMA.TABLES`?

**Comment by kmjung** [comment]
I can't tell from this log output which API call is producing this error -- do you know?

**Comment by chajath** [comment]
from the stack trace, I see: 

`GET https://www.googleapis.com/bigquery/v2/projects/project_id.data_set/datasets/INFORMATION_SCHEMA/tables/TABLES?prettyPrint=false`

**Comment by chajath** [comment]
Full stack trace upto spark:

```
[error] Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
[error] GET https://www.googleapis.com/bigquery/v2/projects/project_id.data_set/datasets/INFORMATION_SCHEMA/tables/TABLES?prettyPrint=false
[error] {
[error]   "code" : 400,
[error]   "errors" : [ {
[error]     "domain" : "global",
[error]     "message" : "Invalid project ID 'project_id.data_set'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.",
[error]     "reason" : "invalid"
[error]   } ],
[error]   "message" : "Invalid project ID 'project_id.data_set'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.",
[error]   "status" : "INVALID_ARGUMENT"
[error] }
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getTable(HttpBigQueryRpc.java:284)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$17.call(BigQueryImpl.java:717)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$17.call(BigQueryImpl.java:714)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.run(RetryHelper.java:76)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:713)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.getTable(BigQueryClient.java:88)
[error]         at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.getReadTable(BigQueryClient.java:101)
[error]         at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:78)
[error]         at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:47)
[error]         at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:354)
[error]         at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
[error]         at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
[error]         at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
...

I'm using `"com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.21.1"`
```

**Comment by kmjung** [comment]
It's not totally clear to me from the "Limitations" section in the public documentation ([link](https://cloud.google.com/bigquery/docs/information-schema-intro#limitations)), but I believe that most BigQuery table metadata APIs don't work with `INFORMATION_SCHEMA` since it's not a proper table or dataset. The short-term workaround that I would recommend would be to use a query to fetch the information you need and then to use the storage API to read from the resulting table.

**Comment by davidrabinowitz** [comment]
Please try the following:
```
spark.conf.set("viewsEnabled","true")
spark.conf.set("materializationDataset","<dataset>")
val tablesDF = spark.read.format("bigquery").load("select * from `<projectId>.<dataset>.__TABLES__`")
```

**Comment by himanshukohli09** [comment]
Also, as mentioned by David [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/433#issuecomment-884518679), please add the following configuration to your spark application: 
`spark.conf.set("readDataFormat", "AVRO")`
