### ISSUE TITLE
Issue while Reading External Tables

### ISSUE THREAD

**Issue by praveenkumarb1207** [GoogleCloudDataproc/spark-bigquery-connector#436]
Hi , 

When  we try to read  the external tables in BigQuery, We are getting the following exception 

```
com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Table type 'EXTERNAL' of table 'spark.external_test' is not supported
  at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.getReadTable(BigQueryClient.java:120)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:78)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:47)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:317)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
  at com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
  ... 49 elided
``` 

Steps to reproduce the issue 

spark-shell command : 

```
spark-shell --master yarn --packages "com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.21.1" 
```

code : 

```
spark.conf.set("credentials", "<base64 encoded json>")

import com.google.cloud.spark.bigquery._
val df = spark.read.bigquery("<project>:<dataset_name>.<table_name>") (external table)
```

Can we read the external tables using this connector ? If not ,  is there anyway to read external tables using Spark ?

**Comment by kmjung** [comment]
At the moment, external tables are not supported in the [BigQuery storage API](https://cloud.google.com/bigquery/docs/reference/storage) which underlies the Spark connector. This is on our road map for 2022.

As a workaround and depending on your BigQuery setup, you can push down a query over an external table to BigQuery using `spark.read.format("bigquery").load("SQL text")` per the instructions [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-data-from-a-bigquery-query). You can then read the results of the query from Spark using the storage API.
