### ISSUE TITLE
Read and write of PySpark code to BigQuery from kubernetes cluster with Java 11 and Java 8 errors

### ISSUE THREAD

**Issue by michTalebzadeh** [GoogleCloudDataproc/spark-bigquery-connector#437]
Hi,

I built docker image from PySpark 3.1.1 with JAVA 11. That worked and could write to GBQ but throwing error reading the data with error "error: java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available".

I followed few threads and according to Spark 3.1.2 doc 

```
"For Java 11, -Dio.netty.tryReflectionSetAccessible=true is required additionally for Apache Arrow library. This prevents java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.(long, int) not available when Apache Arrow uses Netty internally.
```

I added the following:
```
spark-submit --verbose \
--conf spark.driver.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" \
--conf spark.executor.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" \
```
No Luck.  There was a mention of issue with JAVA 11. So I created a docker image for PySpark 3.1.1 with Java 8.

I have a minikube on premise. So I tested this docker image. It can read and write

Then I pushed the image to GCP and tried to run it in GKE as follows:
```
        unset PYSPARK_DRIVER_PYTHON
        export PYSPARK_PYTHON=/usr/bin/python3
        gcloud config set compute/zone europe-west2-c
        export PROJECT=$(gcloud info --format='value(config.project)')
        export CODE_DIRECTORY="gs://$PROJECT-spark-on-k8s/codes"
        gcloud container clusters get-credentials spark-on-gke --zone europe-west2-c
        export KUBERNETES_MASTER_IP=$(gcloud container clusters list --filter name=spark-on-gke --format='value(MASTER_IP)')

        spark-submit --verbose \
           --properties-file ${property_file} \
           --master k8s://https://$KUBERNETES_MASTER_IP:443 \
           --deploy-mode cluster \
           --name pytest \
           --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=./pyspark_venv/bin/python \
           --py-files $CODE_DIRECTORY/DSBQ.zip \
           --conf spark.kubernetes.namespace=$NAMESPACE \
           --conf spark.executor.memory=5000m \
           --conf spark.network.timeout=300 \
           --conf spark.executor.instances=2 \
           --conf spark.kubernetes.driver.limit.cores=1 \
           --conf spark.driver.cores=1 \
           --conf spark.executor.cores=1 \
           --conf spark.executor.memory=2000m \
           --conf spark.kubernetes.driver.docker.image=${IMAGEGCP} \
           --conf spark.kubernetes.executor.docker.image=${IMAGEGCP} \
           --conf spark.kubernetes.container.image=${IMAGEGCP} \
           --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-bq \
           --conf spark.driver.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" \
           --conf spark.executor.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" \
           --conf spark.sql.execution.arrow.pyspark.enabled="true" \
           $CODE_DIRECTORY/${APPLICATION}
```
I have created secrets etc. These are the PySpark settings for GBQ
```
def setSparkConfBQ(spark):
    try:
        spark.conf.set("GcpJsonKeyFile", config['GCPVariables']['jsonKeyFile'])
        spark.conf.set("BigQueryProjectId", config['GCPVariables']['projectId'])
        spark.conf.set("BigQueryParentProjectId", config['GCPVariables']['projectId'])
        spark.conf.set("BigQueryDatasetLocation", config['GCPVariables']['datasetLocation'])
        spark.conf.set("google.cloud.auth.service.account.enable", "true")
        spark.conf.set("fs.gs.project.id", config['GCPVariables']['projectId'])
        spark.conf.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
        spark.conf.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
        spark.conf.set("temporaryGcsBucket", config['GCPVariables']['tmp_bucket'])
        spark.conf.set("spark.sql.streaming.checkpointLocation", config['GCPVariables']['tmp_bucket'])
        return spark
    except Exception as e:
        print(f"""{e}, quitting""")
        sys.exit(1)
```
That reference to 
```
spark.conf.set("GcpJsonKeyFile", config['GCPVariables']['jsonKeyFile'])
```
Is from the yaml file loaded to the image. It makes a reference to this BQ service account in location
```
/home/hduser/axial-glow-224522-1a8ab25e740e.json
```
That location has been created inside the docker image and service account file is loaded so it is there. However, I am getting the following error:
```
: java.io.UncheckedIOException: Failed to create Credentials from file
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryCredentialsSupplier.createCredentialsFromFile(BigQueryCredentialsSupplier.java:63)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryCredentialsSupplier.<init>(BigQueryCredentialsSupplier.java:41)
        at com.google.cloud.spark.bigquery.SparkBigQueryConfig.createCredentials(SparkBigQueryConfig.java:328)
        at com.google.cloud.spark.bigquery.BigQueryUtilScala$.createBigQuery(BigQueryUtil.scala:63)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.$anonfun$getOrCreateBigQuery$1(BigQueryRelationProvider.scala:128)
        at scala.Option.getOrElse(Option.scala:189)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.getOrCreateBigQuery(BigQueryRelationProvider.scala:128)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:100)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
        at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/hduser/axial-glow-224522-1a8ab25e740e.json (No such file or directory)
```
Since k8s works with secrets, I assume because of Java 8 some problems have been added?

The secret is loaded to mount point
```
 /mnt/secrets/spark-sa.json
```
 on a Dataproc host that I use for Spark and I submit this k8s job from.

My question is why this JAVA 8 looking at other credentials but not secrets file?

Alternatively I prefer to use Java 11 which can write to GBQ but cannot read because of the error I mentioned at the beginning.

Apologies for this being long winded but appreciate any advice.

Mich

**Comment by michTalebzadeh** [comment]
Sorted out :)

I removed all references to Jason Service Key file i.e.
```
spark.conf.set("GcpJsonKeyFile", config['GCPVariables']['jsonKeyFile'])
```
from the code and it worked.

```
 writing to BigQuery table test.randomData

 Populated BigQuery table test.randomData

 rows written is  100

 Reading from BigQuery table test.randomData


 rows read in is  2300
+---+
|ID |
+---+
|43 |
|57 |
|2  |
|49 |
|32 |
|46 |
|66 |
|67 |
|72 |
|89 |
|91 |
|55 |
|14 |
|28 |
|70 |
|1  |
|22 |
|54 |
|79 |
|82 |
+---+
only showing top 20 rows
```

I assume that it checks json service account key file references before checking secrets! 

So in summary PySpark 3.11 with Java 8 with  spark-bigquery-latest_2.12.jar works fine inside docker image.

The problem is that Debian buster no longer supports Java 8.

HTH

**Comment by davidrabinowitz** [comment]
According to https://wiki.debian.org/Java OpenJDK 8 is still supported on Debian. We will check the Java 11 compatibility issue.
