### ISSUE TITLE
Error writing a new table in BigQuery

### ISSUE THREAD

**Issue by ddelasheras-stratio** [GoogleCloudDataproc/spark-bigquery-connector#451]
BigQuery datasource 0.22.0
Spark 3.1.0

The following query should create a new table in BigQuery called `bigquerytest.test-write` with 2 columns and 2 rows. I have the BigQuery and GCS credentials properly configured.
```sql
create table test_bigquery
using bigquery OPTIONS (
'credentials'='xxx', 
'table'='bigquerytest.test-write', 
'project'= 'connectorstorage', 
'temporaryGcsBucket'= 'connectors-bucket')
AS SELECT 1 AS id, 'Name 1' AS name UNION SELECT 2 AS id, 'Name 2' AS name;
```

The query fails with this exception:
```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.schema(BigQueryInsertableRelation.scala:70)
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:183)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:120)
	at org.apache.spark.sql.crossdata.execution.XDPlan.$anonfun$executeCollect$12(XDPlan.scala:306)
	at scala.util.Try$.apply(Try.scala:213)
```

The funny thing is **the table is in fact created in BigQuery**.
My guess is there is a race condition between writing the data and reading the metadata.
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/fceda816307e8cbb5bfcf367afaf0ef3bf270c40/spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryInsertableRelation.scala#L70

**Comment by davidrabinowitz** [comment]
Can you please test with version 0.31.1?

**Comment by ddelasheras-stratio** [comment]
@jneira-stratio @trasgum FYI

**Comment by jneira-stratio** [comment]
@davidrabinowitz thanks for the update, just in case, do you know what commit or pr could have fixed it?

**Comment by davidrabinowitz** [comment]
PR #616

**Comment by jneira-stratio** [comment]
many thanks for the info, we have to setup the reproduction case but i am not sure when we will able to do

**Comment by isha97** [comment]
Please create a new issue if you are still facing this with the latest connector version.
