### ISSUE TITLE
Need some help with bigquery connector

### ISSUE THREAD

**Issue by iostreamdoth** [GoogleCloudDataproc/spark-bigquery-connector#462]
hi everyone.
I m trying to run this in jypyter notebook in dataproc cluster.
```#!/usr/bin/python
"""BigQuery I/O PySpark example."""
from pyspark.sql import SparkSession

spark = SparkSession \
  .builder \
  .master('yarn') \
  .appName('spark-bigquery-demo') \
  .config('spark.jars.packages', "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.22.1") \
  .getOrCreate()
spark.sparkContext._jvm.scala.util.Properties.versionString()

# Use the Cloud Storage bucket for temporary BigQuery export data used
# by the connector.
bucket = "dataproc-bucket-iostreamdoth"
spark.conf.set('temporaryGcsBucket', bucket)

# Load data from BigQuery.
words = spark.read.format('bigquery') \
  .option('table', 'bigquery-public-data:samples.shakespeare') \
  .load()
words.createOrReplaceTempView('words')

# Perform word count.
word_count = spark.sql(
    'SELECT word, SUM(word_count) AS word_count FROM words GROUP BY word')
word_count.show()
word_count.printSchema()
```

i m getting  below error can someone guide me what I m missing in this?

```
java.lang.ClassNotFoundException: com.google.cloud.spark.bigquery.direct.BigQueryPartition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1986)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by iostreamdoth** [comment]
https://cloud.google.com/dataproc/docs/tutorials/bigquery-connector-spark-example#pyspark

**Comment by davidrabinowitz** [comment]
Are you running a python notebook or a pyspark notebook? A python notebook is required. Another option is to create a new cluster with the [connectors init action](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/connectors) which will install the spark-bigquery-connector on your cluster, so the `spark.jars.packages` configuration won't be needed

**Comment by iostreamdoth** [comment]
I added them as part of properties of dataproc cluster config and it worked.
