### ISSUE TITLE
Not able to write to BigQuery table

### ISSUE THREAD

**Issue by github-lucas-plaetevoet** [GoogleCloudDataproc/spark-bigquery-connector#468]
Hello,

I'm trying to read/write in some BQ table from spark. 
I am using this version of the lib in scala:
```
"com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.22.0"
```

Reading is fine. Following the doc, this works:
```
val data: DataFrame = spark.read
      .format("bigquery")
      .option("credentials", credStrings)
      .option("parentProject", projectId)
      .option("dataset", bqDataset)
      .load(bqTable)

    logger.info(s"COUNT : ${data.count}")
```
Unfortunately, writing some `df` to the same table does not seem to work:

```
df.write
      .mode(SaveMode.Append)
      .format("bigquery")
      .option("credentials", credStrings)
      .option("temporaryGcsBucket", bucketDirectory)
      .option("parentProject", projectId)
      .option("dataset", bqDataset)
      .save(bqTable)
```
I get the following error:

``` 
 diagnostics: User class threw exception: java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
	at com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:236)
	at com.google.cloud.hadoop.util.CredentialConfiguration.getCredential(CredentialConfiguration.java:91)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1613)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1699)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1658)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:683)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:646)
```

Is there a specific thing to do with the writing operation, compared to just reading?

It seems someone had the same issue on SO: https://stackoverflow.com/questions/67081843/spark-bigquery-connector-error-getting-access-token-from-metadata-server

Thanks for your help

**Comment by github-lucas-plaetevoet** [comment]
I've managed to make it work!

`spark` being a `SparkSession`, I've set the following:

```
spark.sparkContext.hadoopConfiguration.set("fs.gs.project.id", projectId)
spark.sparkContext.hadoopConfiguration.set("fs.gs.impl",classOf[GoogleHadoopFileSystem].getName)
spark.sparkContext.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl", classOf[GoogleHadoopFS].getName)
spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.json.keyfile", credentialsPath)
```

and I've written the credentials (a base64 string) I was passing as an option to the `df.write` method (see my first post) as a decoded json string on the executors and drivers, like so:

```
val credentialsPath = "/tmp/gcp-credentials"
val path  = Paths.get(credentialsPath)
val creds = Base64.getDecoder.decode(credStrings)
Files.write(path, creds)
val nbExecutors = spark.sparkContext.getConf.get("spark.executor.instances").toInt
spark.range(nbExecutors.toLong).toDF.repartition(nbExecutors).foreachPartition {
  (_: Iterator[Row]) =>
    val path    = Paths.get(credentialsPath)
    val p: Path = Files.write(path, creds)
}
```

Writing did not change:

```
df.write
      .mode(SaveMode.Append)
      .format("bigquery")
      .option("credentials", credStrings)
      .option("temporaryGcsBucket", bucketDirectory)
      .option("parentProject", projectId)
      .option("dataset", bqDataset)
      .save(bqTable)
```

Hope this helps other people, thanks @davidrabinowitz
