### ISSUE TITLE
Permission bigquery.tables.get denied on table when Using Spark-Bigquery connector

### ISSUE THREAD

**Issue by jonaslahwf21** [GoogleCloudDataproc/spark-bigquery-connector#478]
Hello,
here's my code: 
```
val rawObj: Dataset[RawObject] = sparkSession.read.format("bigquery")
      .option("table","project.dataset.table")
      .option("filter", s"d = $token")
      .load()
     ...
```

I'm using 
<dependency>
            <groupId>com.google.cloud.spark</groupId>
            <artifactId>spark-bigquery-with-dependencies_2.11</artifactId>
            <version>0.22.2</version>
        </dependency>

I'm using my own user which has all the rights to read  this table but I'm getting this error:

`Exception in thread "main" com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Access Denied: Table project.dataset.table: Permission bigquery.tables.get denied on table project.dataset.table (or it may not exist).
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getTable(HttpBigQueryRpc.java:286)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$18.call(BigQueryImpl.java:746)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$18.call(BigQueryImpl.java:743)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:742)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.getTable(BigQueryClient.java:89)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.getReadTable(BigQueryClient.java:102)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:78)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:47)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:890)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
GET https://www.googleapis.com/bigquery/v2/projects/project/datasets/dataset/tables/table?prettyPrint=false
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Access Denied: Table project:dataset.table: Permission bigquery.tables.get denied on table project:dataset.table (or it may not exist).",
    "reason" : "accessDenied"
  } ],
  "message" : "Access Denied: Table project:dataset.table: Permission bigquery.tables.get denied on table project:dataset.table (or it may not exist).",
  "status" : "PERMISSION_DENIED"
}
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getTable(HttpBigQueryRpc.java:284)
	... 26 more
21/10/13 15:06:30 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@76a5e9e4{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}`
Any idea what to do in this case ? why is my user credentials not used ?
PS I tried setting the parentProject but it didn't work.

**Comment by jonaslahwf21** [comment]
found the missing rights

**Comment by 1Bullzeye1** [comment]
how did you fixed your rights

**Comment by davidrabinowitz** [comment]
@1Bullzeye1 please go to https://console.cloud.google.com/iam-admin/iam

**Comment by lisageek** [comment]
hello @jonaslahwf21 can you please tell me how you fixed the issue? I am having the exact same message trying to run serverless spark. I followed the link @davidrabinowitz provided without knowing what to do there.
I took me to the iam/admin home page.
Any help would be apreciated.

Thanks

**Comment by irajhedayati** [comment]
same issue, that would be nice to share the solution

**Comment by vmariyappa** [comment]
Hi , can anyone please let me know how this issue was fixed . I have below permissions on my service account but still getting the error 

BigQuery Admin
BigQuery Data Transfer Service Agent
BigQuery Data Viewer
BigQuery Job User
BigQuery User
Owner
Storage Object Viewer

**Comment by ankit001mittal** [comment]
What permissions do we need to give to resolve this issue? I am running into the same problem as well.

**Comment by davidrabinowitz** [comment]
For reading only
* [BigQuery Data Viewer](https://cloud.google.com/bigquery/docs/access-control#bigquery.dataViewer)
* [BigQuery Read Session User](https://cloud.google.com/bigquery/docs/access-control#bigquery.readSessionUser)
* [BigQuery Job User](https://cloud.google.com/bigquery/docs/access-control#bigquery.jobUser) (If views are used)
For writing
* [BigQuery Data Editor](https://cloud.google.com/bigquery/docs/access-control#bigquery.dataEditor)
* [BigQuery Job User](https://cloud.google.com/bigquery/docs/access-control#bigquery.jobUser) (Indirect writes)
* GCS write permissions for the relevant bucket

A catch all role is [BigQuery User](https://cloud.google.com/bigquery/docs/access-control#bigquery.user)
