### ISSUE TITLE
Repacked dependencies not found

### ISSUE THREAD

**Issue by kevinlacire** [GoogleCloudDataproc/spark-bigquery-connector#479]
I'm trying to write to BigQuery using Spark 3. Despite the presence of all the dependencies in my fatjar (also added to $SPARK_HOME/jars but still not working)

While I was looking for the missing class pointed by the below stacktrace I found out that all dependencies under the `repack` package could not be found on BigQuery Writer initialization.
I can go futher by downloading each dependencies individually and add them to `$SPARK_HOME/jars` but I'ms sure it's not the solution (I already added 20 jars required by the Spark BigQuery connector but I'm still facing exceptions...)

`implementation 'com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.22.2'`

```bash
21/10/18 08:23:00 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/client/http/HttpRequestInitializer
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2532)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2497)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2593)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3269)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.<init>(BigQueryWriteHelper.scala:63)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:113)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
	at com.hellowork.datalab.happymealstats.io.writer.BigQueryWriter.write(BigQueryWriter.scala:31)
	at com.hellowork.datalab.happymealstats.stats.MyStat$.process(MyStat.scala:50)
	at com.hellowork.datalab.happymealstats.stats.MyStat$.main(MyStat.scala:29)
	at com.hellowork.datalab.happymealstats.stats.MyStat.main(MyStat.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.http.HttpRequestInitializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
21/10/18 08:23:00 INFO ShutdownHookManager: Shutdown hook called
```

Tried to apply the workaround of https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/274 same result.

The Spark 2.4 BigQuery connector was working like a charm and was also repacked. 
Am I missing something ?

Thanks in advance for your help

**Comment by davidrabinowitz** [comment]
Can you please try with the latest version (0.23.0) ?

**Comment by kevinlacire** [comment]
> Can you please try with the latest version (0.23.0) ?

Same result unfortunately
I'm surely not the only one to use this connector's version 🤔 
Does somebody have a minimal example of this running ?

**Comment by davidrabinowitz** [comment]
Have you installed the GCS connector yourself? Which jar have you installed?

**Comment by kevinlacire** [comment]
I've embedded the jar on every of my executors (which are kubernetes Pods btw), this exact version : https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.0/gcs-connector-hadoop3-2.2.0.jar

**Comment by kevinlacire** [comment]
> Have you installed the GCS connector yourself? Which jar have you installed?

I've embedded the jar on every of my executors (which are kubernetes Pods btw), this exact version : https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.0/gcs-connector-hadoop3-2.2.0.jar

**Comment by davidrabinowitz** [comment]
Please use https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.0/gcs-connector-hadoop3-2.2.0-shaded.jar instead, it contains all the dependencies

**Comment by kevinlacire** [comment]
> Please use https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.0/gcs-connector-hadoop3-2.2.0-shaded.jar instead, it contains all the dependencies

seems promising, my job goes further now 👍  
thanks a lot.
