### ISSUE TITLE
ETL Connector not loading in aws

### ISSUE THREAD

**Issue by AltafHussain4748** [GoogleCloudDataproc/spark-bigquery-connector#490]
I am using bigquery connector for aws glue in my glue job. It was working fine few days ago but now suddenly it is giving me below error:

```
LAUNCH ERROR | Glue ETL Marketplace - failed to download connector.Please refer logs for details.

```

Below is the full error that i am getting on cloudwatch

```

2021-11-08T11:33:02.045+05:00	Traceback (most recent call last): File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main

2021-11-08T11:33:02.070+05:00	"__main__", mod_spec) File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/tmp/aws_glue_custom_connector_python/docker/unpack_docker_image.py", line 361, in <module>

2021-11-08T11:33:02.070+05:00	main() File "/tmp/aws_glue_custom_connector_python/docker/unpack_docker_image.py", line 351, in main

2021-11-08T11:33:02.070+05:00	res += download_jars_per_connection(conn, region, endpoint, proxy) File "/tmp/aws_glue_custom_connector_python/docker/unpack_docker_image.py", line 304, in download_jars_per_connection

2021-11-08T11:33:02.070+05:00	download_and_unpack_docker_layer(ecr_url, layer["digest"], dir_prefix, http_header) File "/tmp/aws_glue_custom_connector_python/docker/unpack_docker_image.py", line 168, in download_and_unpack_docker_layer

2021-11-08T11:33:02.070+05:00	layer = send_get_request(layer_url, header) File "/tmp/aws_glue_custom_connector_python/docker/unpack_docker_image.py", line 80, in send_get_request

2021-11-08T11:33:02.070+05:00	

2021-11-08T11:33:02.070+05:00	response.raise_for_status() File "/home/spark/.local/lib/python3.7/site-packages/requests/models.py", line 765, in raise_for_status

2021-11-08T11:33:02.071+05:00	raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request

2021-11-08T11:33:02.119+05:00	Glue ETL Marketplace - failed to download connector, activation script exited with code 
```

**Comment by davidrabinowitz** [comment]
Can you please provide details on the configuration?

**Comment by AltafHussain4748** [comment]
@davidrabinowitz 
I have setup the secret which have the key **credentials** and base64 encoded string of my service account.

Apart from that  my configrations are:

![bigquery](https://user-images.githubusercontent.com/28758144/140781935-f23991de-3c2a-4614-ad4a-9bb6f40f1d35.png)

As i am inserting data into bigquery
i am passing - 

```
--conf: spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=service-account.json
```

Please note that same settings were working few days ago.

**Comment by davidrabinowitz** [comment]
It is not clear how the connector is added to the spark job. Have you contacted the Glue user support?

**Comment by AltafHussain4748** [comment]
Nope I am using basic plan and might not have option to support center
