### ISSUE TITLE
Could not handle BIGNUMERICs while writing 

### ISSUE THREAD

**Issue by rupeshbhujbal41184** [GoogleCloudDataproc/spark-bigquery-connector#500]
Could not handle BIGNUMERICs while writing to BQ,

**Comment by VinayLondhe14** [comment]
Can you please post more information about the issue that you are facing?

**Comment by davidrabinowitz** [comment]
Please provide spark version, connector version, stack trace and if possible - a short code snippet to reproduce the issue

**Comment by rupeshbhujbal41184** [comment]
spark version 3.1.2, spark-bigquery-connector-version 0.22.2, bigquery-connector-version1.2.0

below is the printschema of dataframe: 
root
 |-- retailer_name: string (nullable = true)
 |-- total_ton: decimal(32,20) (nullable = true)
 |-- Total_GST_Value_RUB: decimal(32,20) (nullable = true)
 |-- ZDDZ: decimal(32,20) (nullable = true)
 |-- ZDYZ: decimal(32,20) (nullable = true)

while writing to BigQuery its throwing below error,
df.write.format("bigquery") \
    .option("temporaryGcsBucket", 'XXXXXXXXXXXXXXXXXXXXXXXXXXX') \
    .mode('overwrite').save('#############')

Py4JJavaError: An error occurred while calling o393.save.
: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:93)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:113)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: The value for column 'total_ton' is out of valid NUMERIC range: Value will lose precision after scaling down to NUMERIC type; input length: 14; scale: 20; input data: 0000000000014d28388ee06a3448
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:419)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:252)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:179)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$lzycompute$1(BigQueryWriteHelper.scala:153)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$1(BigQueryWriteHelper.scala:153)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.$anonfun$loadDataToBigQuery$3(BigQueryWriteHelper.scala:155)
	at org.apache.spark.internal.Logging.logInfo(Logging.scala:57)
	at org.apache.spark.internal.Logging.logInfo$(Logging.scala:56)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.logInfo(BigQueryWriteHelper.scala:33)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:155)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:90)
	... 34 more


​

**Comment by rupeshbhujbal41184** [comment]
also df.columns doesn't work, if df contain bignumeric columns. throws below error,

--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_18008/2553322557.py in <module>
     20     df = spark.read.format("bigquery").load("{}.{}".format('XXXXXXXXXXX', 'XXXXXXXXXXXXXX'))
     21     df.printSchema()
---> 22     if not FILENAME_COLNAME in df.columns:
     23         print("not found")
     24     else:

/usr/lib/spark/python/pyspark/sql/dataframe.py in columns(self)
   1197         ['age', 'name']
   1198         """
-> 1199         return [f.name for f in self.schema.fields]
   1200 
   1201     def colRegex(self, colName):

/usr/lib/spark/python/pyspark/sql/dataframe.py in schema(self)
    274         if self._schema is None:
    275             try:
--> 276                 self._schema = _parse_datatype_json_string(self._jdf.schema().json())
    277             except AttributeError as e:
    278                 raise Exception(

/usr/lib/spark/python/pyspark/sql/types.py in _parse_datatype_json_string(json_string)
    891     >>> check_datatype(complex_maptype)
    892     """
--> 893     return _parse_datatype_json_value(json.loads(json_string))
    894 
    895 

/usr/lib/spark/python/pyspark/sql/types.py in _parse_datatype_json_value(json_value)
    908         tpe = json_value["type"]
    909         if tpe in _all_complex_types:
--> 910             return _all_complex_types[tpe].fromJson(json_value)
    911         elif tpe == 'udt':
    912             return UserDefinedType.fromJson(json_value)

/usr/lib/spark/python/pyspark/sql/types.py in fromJson(cls, json)
    594     @classmethod
    595     def fromJson(cls, json):
--> 596         return StructType([StructField.fromJson(f) for f in json["fields"]])
    597 
    598     def fieldNames(self):

/usr/lib/spark/python/pyspark/sql/types.py in <listcomp>(.0)
    594     @classmethod
    595     def fromJson(cls, json):
--> 596         return StructType([StructField.fromJson(f) for f in json["fields"]])
    597 
    598     def fieldNames(self):

/usr/lib/spark/python/pyspark/sql/types.py in fromJson(cls, json)
    439     def fromJson(cls, json):
    440         return StructField(json["name"],
--> 441                            _parse_datatype_json_value(json["type"]),
    442                            json["nullable"],
    443                            json["metadata"])

/usr/lib/spark/python/pyspark/sql/types.py in _parse_datatype_json_value(json_value)
    910             return _all_complex_types[tpe].fromJson(json_value)
    911         elif tpe == 'udt':
--> 912             return UserDefinedType.fromJson(json_value)
    913         else:
    914             raise ValueError("not supported type: %s" % tpe)

/usr/lib/spark/python/pyspark/sql/types.py in fromJson(cls, json)
    753         pyModule = pyUDT[:split]
    754         pyClass = pyUDT[split+1:]
--> 755         m = __import__(pyModule, globals(), locals(), [pyClass])
    756         if not hasattr(m, pyClass):
    757             s = base64.b64decode(json['serializedClass'].encode('utf-8'))

ModuleNotFoundError: No module named 'google.cloud.spark'

​

**Comment by colea911** [comment]
same issue for me - anyone find a solution?

**Comment by nolivier-bm** [comment]
Hello! 👋 

Same issue here, we get this error while trying to write to BigQuery: 
`Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: The value for column 'rate' is out of valid NUMERIC range: Value will lose precision after scaling down to NUMERIC type; input length: 8; scale: 10; input data: xxx`

##Libraries versions 
- spark-bigquery-with-dependencies_2.12-0.26.0
- pyspark 3.2.1 
- Databricks 10.3 (includes Apache Spark 3.2.1, Scala 2.12) 

##Code snippet
```
df.write \
    .format("bigquery") \
    .mode("overwrite") \
    .option("temporaryGcsBucket", "my_bucket") \
    .option("project", "my_project") \
    .option("table", "test.my_table") \
    .save()
```

##Source dataframe 
```
df:pyspark.sql.dataframe.DataFrame
- rate:decimal(18,10)
```

It should be written as a BigNumeric in BigQuery as the scale exceeds Numeric's scale of 9. 
We also wonder if it comes from Databricks.
Can you help? Thanks!
