### ISSUE TITLE
Strange behavior of the spark24 version

### ISSUE THREAD

**Issue by Letreguilly** [GoogleCloudDataproc/spark-bigquery-connector#504]
Hi, I am doing some test arround the new spark24 version of the connector, unfortunately I have some issue.

So I am using spark 2.4.8 with scala 2.11 to write some data to bigquery. I use the following code (simplified) from a spark structrured streaming query to write a micro batchs to bigquery. At the time of theses test, the service account has the bigqueryAdmin permission and I have tried to set it trough the ENV variable `GOOGLE_APPLICATION_CREDENTIAL` and directly on the dataframewriter via `.option("credentialsFile", "/Users/sylvain/IdeaProjects/bigquery-realtime-loader")
`

```scala
foreachBatch ...
df.write
      .format("com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2")
      .option("writeMethod", "direct")
      .option("partitionField", "date_created")
      .mode(SaveMode.Append)
      .save("tableName")
``` 

When running this query two error happend randomly :

```
com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not create write-stream after multiple retries
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:70)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.<init>(BigQueryDirectDataWriter.java:72)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterFactory.createDataWriter(BigQueryDirectDataWriterFactory.java:65)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:113)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:411)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.NotFoundException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Not found: table Table is deleted: 193385559989:...............................................
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCallable(BigQueryDirectDataWriterHelper.java:122)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCreateWriteStream(BigQueryDirectDataWriterHelper.java:89)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:68)
	... 13 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.NotFoundException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Not found: table Table is deleted: 193385559989:.......................................................
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
	Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1beta2.BigQueryWriteClient.createWriteStream(BigQueryWriteClient.java:232)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.lambda$retryCreateWriteStream$0(BigQueryDirectDataWriterHelper.java:92)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCallable(BigQueryDirectDataWriterHelper.java:122)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCreateWriteStream(BigQueryDirectDataWriterHelper.java:89)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:68)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.<init>(BigQueryDirectDataWriter.java:72)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterFactory.createDataWriter(BigQueryDirectDataWriterFactory.java:65)
		at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:113)
		at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
		at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
		at org.apache.spark.scheduler.Task.run(Task.scala:123)
		at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:411)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417)
		... 3 more
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Not found: table Table is deleted: .................................................
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:535)
	... 13 more
```

And 

```
	com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not retrieve AppendRowsResponse
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:200)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.sendAppendRowsRequest(BigQueryDirectDataWriterHelper.java:176)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.addRow(BigQueryDirectDataWriterHelper.java:157)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.write(BigQueryDirectDataWriter.java:81)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.write(BigQueryDirectDataWriter.java:35)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:118)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:411)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.PermissionDeniedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource ....................................... (or it may not exist).
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:56)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:198)
	... 18 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.PermissionDeniedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource '................................................' (or it may not exist).
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource '.................................................' (or it may not exist).
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:535)
	... 10 more
```

If i switch back to indirect mode I have another error, the partition column is well a timestamp and not an INT64 (check with df.printSchema)

```
org.apache.spark.SparkException: Writing job aborted.
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:92)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:136)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:160)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:157)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:280)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter.doWrite(BigQueryGoogleWriter.scala:93)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter$$anonfun$com$wizbii$bigqueryV2$core$pipeline$writer$bigquery$BigQueryGoogleWriter$$writeDFWithRetry$1.apply(BigQueryGoogleWriter.scala:100)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter$$anonfun$com$wizbii$bigqueryV2$core$pipeline$writer$bigquery$BigQueryGoogleWriter$$writeDFWithRetry$1.apply(BigQueryGoogleWriter.scala:100)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryWriterErrorHandler$$anonfun$1.apply$mcV$sp(BigQueryWriterErrorHandler.scala:75)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryWriterErrorHandler$$anonfun$1.apply(BigQueryWriterErrorHandler.scala:73)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryWriterErrorHandler$$anonfun$1.apply(BigQueryWriterErrorHandler.scala:73)
	at scala.util.Try$.apply(Try.scala:192)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryWriterErrorHandler$.retryWrite(BigQueryWriterErrorHandler.scala:73)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryWriterErrorHandler$.handle(BigQueryWriterErrorHandler.scala:44)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter.com$wizbii$bigqueryV2$core$pipeline$writer$bigquery$BigQueryGoogleWriter$$writeDFWithRetry(BigQueryGoogleWriter.scala:100)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter$$anonfun$start$1.apply(BigQueryGoogleWriter.scala:47)
	at com.wizbii.bigqueryV2.core.pipeline.writer.bigquery.BigQueryGoogleWriter$$anonfun$start$1.apply(BigQueryGoogleWriter.scala:42)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$19.apply(MicroBatchExecution.scala:548)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:546)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:545)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: The field specified for DAY partitioning can only be of type TIMESTAMP, DATETIME or DATE. The type found is: INT64.
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:419)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:252)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:305)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:295)
	at com.google.cloud.spark.bigquery.v2.BigQueryIndirectDataSourceWriter.loadDataToBigQuery(BigQueryIndirectDataSourceWriter.java:197)
	at com.google.cloud.spark.bigquery.v2.BigQueryIndirectDataSourceWriter.commit(BigQueryIndirectDataSourceWriter.java:140)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:76)
	... 47 more
```

Thank in advance for your help.

Regards

**Comment by davidrabinowitz** [comment]
Thanks for the information! Direct writing uses the [BigQuery Storage Write API](https://cloud.google.com/bigquery/docs/write-api), can you please verify you have the [correct permissions](https://cloud.google.com/bigquery/docs/write-api#required_permissions)?

**Comment by Letreguilly** [comment]
I have grant the bigquery admin role to the service account used for the test, as explain in your link permission should be fine

**Comment by Letreguilly** [comment]
I have done some additionnal test to be sure that it was not an issue related to the permission. 

So I have created a new service account with just the bigquery admin right on the projet ==> TABLES_UPDATE_DATA permission denied when I launch the job. 

Then without much conviction I add more permission to the service account : dataOwner and dataEditor (they are not included inside the admin role ?). This time it work until the batch 9 : TABLES_UPDATE_DATA permission denied again. I check the created table on the SQL console however the table is not partionned. After that I re launch the job to test again but it just thow an error : table is deleting. The table was indded deleted on bigquery.

The code snippet used to write data to bigquery is the following : 

```  
df.write
      .format("com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2")
      .option("writeMethod", "direct")
      .option("partitionField", "...")
      .mode(SaveMode.Append)
      .save("tableName")
```

In my case, direct write don't work very well ... Have you been able to reproduce similar issue ?

**Comment by davidrabinowitz** [comment]
Thanks for the additional information - I will have a look
