### ISSUE TITLE
Failed to write to BigQuery with BigNumeric data type from PySpark

### ISSUE THREAD

**Issue by stas-snow** [GoogleCloudDataproc/spark-bigquery-connector#541]
I am unable to write to BigNumber to BigQuery. Saving fails.

py4j.protocol.Py4JJavaError: An error occurred while calling o83.save.
java.lang.RuntimeException: Failed to write to BigQuery
BigQueryException: Provided Schema does not match Table my_project:my_dateset.test_bignumeric. Field xyz has changed type from BIGNUMERIC(38, 18) to STRING

`
22/02/07 03:05:12 INFO com.google.cloud.bigquery.connector.common.BigQueryClient: Submitted job LoadJobConfiguration{type=LOAD, destinationTable=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=asdf, projectId=qwerty, tableId=test_bignumeric}}, decimalTargetTypes=null, destinationEncryptionConfiguration=null, createDisposition=CREATE_IF_NEEDED, writeDisposition=WRITE_APPEND, formatOptions=FormatOptions{format=PARQUET}, nullMarker=null, maxBadRecords=null, schema=null, ignoreUnknownValue=null, sourceUris=[gs://asdf/.spark-bigquery-application_1234124321341234/part-00000-123421342134-c000.snappy.parquet], schemaUpdateOptions=null, autodetect=true, timePartitioning=null, clustering=null, useAvroLogicalTypes=null, labels=null, jobTimeoutMs=null, rangePartitioning=null, hivePartitioningOptions=null}. jobId: JobId{project=qwerty, job=222222222222222222222, location=US}
Traceback (most recent call last):
  File "/tmp/764f739955d247e0a4bc94c8b785293a/big_numeric.py", line 73, in <module>
    df.write.format('bigquery') \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1107, in save
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o83.save.
: java.lang.RuntimeException: Failed to write to BigQuery
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:94)
        at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:111)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
        at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table my_project:my_dateset.test_bignumeric. Field xyz has changed type from BIGNUMERIC(38, 18) to STRING
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:419)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:252)
        at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:305)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$lzycompute$1(BigQueryWriteHelper.scala:154)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.finishedJob$1(BigQueryWriteHelper.scala:154)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.$anonfun$loadDataToBigQuery$3(BigQueryWriteHelper.scala:156)
        at org.apache.spark.internal.Logging.logInfo(Logging.scala:57)
        at org.apache.spark.internal.Logging.logInfo$(Logging.scala:56)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.logInfo(BigQueryWriteHelper.scala:34)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:156)
        at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:91)
        ... 34 more

22/02/07 03:05:14 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@451eb821{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
`

**Comment by stas-snow** [comment]
Some additional information. Here is the code that I'm running:

```
# Load data from BigQuery.
df = spark.read.format('bigquery') \
    .option('table', 'my_dateset.test_bignumeric') \
    .option("parentProject", "xyz") \
    .load()

df.show()
df.printSchema()

# Saving the data to BigQuery
df.write.format('bigquery') \
    .option('table', 'my_dateset.test_bignumeric') \
    .mode('append') \
    .save()
```

What's interesting is that this code starts to work if I change the mode from 'append' to 'overwrite'.

Please note that df.printSchema() properly shows bignumeric data type for the DataFrame.

Is there a way to give a hint to BigQuery Job to use decimalTargetTypes? Seems like this is something that should be exposed as options for writing to BigQuery.

**Comment by davidrabinowitz** [comment]
Can you please share the spark and connector versions? Also, have you added the code specified in the [BigNumeric Support section](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#bignumeric-support)?

**Comment by stas-snow** [comment]
Spark version: 3.1.2

Run command:
```
gcloud dataproc jobs submit pyspark big_numeric.py --project=my-project --cluster=test3 --region=us-central1 --jars=gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar
```

Python code to start SparkSession:
```
spark = SparkSession \
    .builder \
    .master('yarn') \
    .appName('spark-bignumeric-test') \
    .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar') \
    .config('spark.submit.pyFiles', 'gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip') \
    .config('spark.files', 'gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip') \
    .getOrCreate()
```

**Comment by stas-snow** [comment]
Additional clarification... Something I didn't notice in one of the prior runs...
When I ran with mode('overwrite') it worked, but only because it recreated the table from scratch, and instead of using BIGNUMERIC it created **STRING** data type in BigQuery.

**Comment by stas-snow** [comment]
@VinayLondhe14 / @davidrabinowitz , do you have any updates on this item? Do you need more info from me?

**Comment by stas-snow** [comment]
Looking at the code inside of convertByBigQueryType function...

```
    if (LegacySQLTypeName.NUMERIC.equals(bqField.getType())) {
      byte[] bytes = getBytes((ByteBuffer) value);
      BigDecimal b = new BigDecimal(new BigInteger(bytes), BQ_NUMERIC_SCALE);
      Decimal d = Decimal.apply(b, BQ_NUMERIC_PRECISION, BQ_NUMERIC_SCALE);

      return d;
    }

    if (LegacySQLTypeName.BIGNUMERIC.equals(bqField.getType())) {
      byte[] bytes = getBytes((ByteBuffer) value);
      BigDecimal bigDecimal = new BigDecimal(new BigInteger(bytes), BQ_BIG_NUMERIC_SCALE);
      return UTF8String.fromString(bigDecimal.toString());
    }
```

It looks like the first block properly returns Decimal. I would expect that second block would return BigDecimal, but instead it returns a string. It seems that this is where the problem is.

**Comment by flo076** [comment]
Hello, any update on it ?

**Comment by roshniraoof** [comment]
@davidrabinowitz I am seeing the same issue. Was there any update on this?

**Comment by davidrabinowitz** [comment]
Fixed in version 0.31.0
