### ISSUE TITLE
custom parrallel task and spark connector

### ISSUE THREAD

**Issue by MadMenHitBooker** [GoogleCloudDataproc/spark-bigquery-connector#559]
Hello,

I have an issue regarding a specific task which need parallel execution.

when i configure my job as

```scala
val etlconf : ParMap[Id, Conf]= getConf().par
etlconf .foreach(
    f = jobid => {
    etl(jobid)
}
)
```

Everything is fine.

However when i want to customize my parrallel tasks as

```scala
val etlconf : ParMap[Id, Conf]= getConf().par
val taskSupport                                     = new ForkJoinTaskSupport(new scala.concurrent.forkjoin.ForkJoinPool(4))
etlconf .tasksupport = taskSupport

etlconf .foreach(
    f = jobid => {
    etl(jobid)
}
)
```

With the same code i get errors regarding the bigquery source

```shell
Exception in thread "main" java.lang.ClassNotFoundException: 
Failed to find data source: bigquery. Please find packages at
http://spark.apache.org/third-party-projects.html
       
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failedToFindDataSourceError(QueryExecutionErrors.scala:443)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:670)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:720)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
```

I use the this specific jar
gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar

**Comment by davidrabinowitz** [comment]
Can you please share the spark app / SParkSession configuration?

**Comment by MadMenHitBooker** [comment]
yes sure

```scala
  val sparkSession: SparkSession = SparkSession
    .builder()
    .config(
      spark_conf_with_credential
        .set("spark.sql.parquet.int96RebaseModeInRead", "CORRECTED")
        .set("spark.sql.parquet.int96RebaseModeInWrite", "CORRECTED")
        .set("spark.sql.parquet.datetimeRebaseModeInRead", "CORRECTED")
        .set("spark.sql.parquet.datetimeRebaseModeInWrite", "CORRECTED")
        .set("viewsEnabled", "true")
        .set("materializationDataset", materializationDataset)
        .set("temporaryGcsBucket", temporaryGcsBucket)
    )
    .getOrCreate()
```

with additional conf when launching

```shell
spark_properties = "spark.sql.adaptive.enabled=true,spark.sql.analyzer.failAmbiguousSelfJoin=false,spark.sql.debug.maxToStringFields=100"
```

FYI i'm using dataproc in serverless mode 

```xml
        <scala.majorversion>2.12</scala.majorversion>
        <scala.minorversion>14</scala.minorversion>
...
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.majorversion}</artifactId>
            <version>3.2.1</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by suryasoma** [comment]
Hi, can you retry by adding the  `.config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar')` to the spark session.
