### ISSUE TITLE
BigQuery direct write API to a partitioned table failing

### ISSUE THREAD

**Issue by yeshvantbhavnasi** [GoogleCloudDataproc/spark-bigquery-connector#560]
Spark-Bigquery connector with WriteMethod = direct is having issues with the temporary file name that it creates with the SaveMode is OverWrite.  

This is the stack trace: 

```
1) Error in custom provider, com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Invalid table ID "online_sales_transaction-compact$20211204380202332308351". Table IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long. Also, Table decorators cannot be used.
  at com.google.cloud.spark.bigquery.v2.BigQueryDataSourceWriterModule.provideDirectDataSourceWriter(BigQueryDataSourceWriterModule.java:61)
  while locating com.google.cloud.spark.bigquery.v2.BigQueryDirectDataSourceWriter

1 error
com.google.cloud.spark.bigquery.repackaged.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Invalid table ID "online_sales_transaction-compact$20211204380202332308351". Table IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long. Also, Table decorators cannot be used.
  at com.google.cloud.spark.bigquery.v2.BigQueryDataSourceWriterModule.provideDirectDataSourceWriter(BigQueryDataSourceWriterModule.java:61)
  while locating com.google.cloud.spark.bigquery.v2.BigQueryDirectDataSourceWriter

1 error
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2.createWriter(BigQueryDataSourceV2.java:126)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:255)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at com.box.dataplatform.spark.context.internal.bigquery.BigQueryWriterImpl.write(BiqQueryWriter.scala:182)
	at com.box.dataplatform.spark.context.internal.DataPlatformContextImpl.com$box$dataplatform$spark$context$internal$DataPlatformContextImpl$$write(DataPlatformContextImpl.scala:132)
	at com.box.dataplatform.spark.context.internal.DataPlatformContextImpl$$anonfun$write$1.apply(DataPlatformContextImpl.scala:68)
	at com.box.dataplatform.spark.context.internal.DataPlatformContextImpl$$anonfun$write$1.apply(DataPlatformContextImpl.scala:66)
```

This looks like - https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/383

The change seems to be applied to indirect writes and not for direct writes to BigQuery.

**Comment by davidrabinowitz** [comment]
Setting a partition is supported only by the indirect write method, as stated in the [README](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#properties). Once the BigQuery Storage Write API will add this functionality it will be supported in the connector as well.
