### ISSUE TITLE
BigQuery direct write is failing with `Exceeds 'CreateWriteStream requests per minute'` quota

### ISSUE THREAD

**Issue by yeshvantbhavnasi** [GoogleCloudDataproc/spark-bigquery-connector#594]
We are using the spark bigQuery connector v0.23.1-preview it was working fine for some days until yesterday we saw seeing exceptions on write.

Error stacktrace :
```
22/04/15 13:28:06 INFO TaskSetManager: Starting task 9842.3 in stage 2.0 (TID 10608, ip-10-26-3-235.prod.dp.box.net, executor 92, partition 9842, PROCESS_LOCAL, 7778 bytes)
22/04/15 13:28:40 WARN TaskSetManager: Lost task 9601.2 in stage 2.0 (TID 10496, ip-10-26-3-235.prod.dp.box.net, executor 88): com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not create write-stream after multiple retries
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:70)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.<init>(BigQueryDirectDataWriter.java:72)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterFactory.createDataWriter(BigQueryDirectDataWriterFactory.java:65)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:113)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ResourceExhaustedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'CreateWriteStream requests per minute' quota, user_id: project000000ed7286d151_us (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description. Before requesting an increase, please ensure your existing streams have enough utilization in terms of write traffic. Entity: projects/box-prod-dp-enterprise-events/datasets/tmp/tables/enterprise-events-compact-cc18286c85
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCallable(BigQueryDirectDataWriterHelper.java:122)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCreateWriteStream(BigQueryDirectDataWriterHelper.java:89)
	at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:68)
	... 13 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ResourceExhaustedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'CreateWriteStream requests per minute' quota, user_id: project000000ed7286d151_us (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description. Before requesting an increase, please ensure your existing streams have enough utilization in terms of write traffic. Entity: projects/box-prod-dp-enterprise-events/datasets/tmp/tables/enterprise-events-compact-cc18286c85
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:57)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
	Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1beta2.BigQueryWriteClient.createWriteStream(BigQueryWriteClient.java:232)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.lambda$retryCreateWriteStream$0(BigQueryDirectDataWriterHelper.java:92)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCallable(BigQueryDirectDataWriterHelper.java:122)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.retryCreateWriteStream(BigQueryDirectDataWriterHelper.java:89)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterHelper.<init>(BigQueryDirectDataWriterHelper.java:68)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriter.<init>(BigQueryDirectDataWriter.java:72)
		at com.google.cloud.spark.bigquery.v2.BigQueryDirectDataWriterFactory.createDataWriter(BigQueryDirectDataWriterFactory.java:65)
		at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:113)
		at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
		at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
		at org.apache.spark.scheduler.Task.run(Task.scala:123)
		at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
		... 3 more
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'CreateWriteStream requests per minute' quota, user_id: project000000ed7286d151_us (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description. Before requesting an increase, please ensure your existing streams have enough utilization in terms of write traffic. Entity: projects/box-prod-dp-enterprise-events/datasets/tmp/tables/enterprise-events-compact-cc18286c85
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:535)
	... 10 more
```

We created a google support ticket to increase the quota as suggested in the error log doubling the quota limit still the same error.

Support reponded with this message:

```
Looking at the usage patterns in this project. All WriteStreams are capped at serving 11 requests, and 80% of streams serve exactly 10 requests. This is pretty low usage per WriteStream and this is the reason why the customer hit the quota limit. Ideal usage of the API would be many more AppendsRows request per stream. We will need to work with the customer to re-use existing streams and increase number of Append requests per WriteStream.

Another thing I noticed is that about 60% of the streams are being aborted due to inactivity after 10 minutes. I wanted to make sure that the customer knows that this is closing the connection, not the WriteStream. They can re-connect with the same WriteStream, and continue to append to it as usual.
```

**Comment by yeshvantbhavnasi** [comment]
Is there any config to increase the number of Append requests per WriteStream

**Comment by davidrabinowitz** [comment]
It can be done from the GCP console - https://console.cloud.google.com/iam-admin/quotas?pageState=(%22allQuotasTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22Metric_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22bigquerystorage.googleapis.com%252Fwrite%252Fcreate_stream_requests_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22metricName_22%257D%255D%22))

Go to Menu -> IAM & Admin -> Quotas -> search for `bigquerystorage.googleapis.com/write/create_stream_requests` and edit the quota

**Comment by VinayLondhe14** [comment]
@yeshvantbhavnasi Are you still seeing this issue? 

If yes, feel free to reopen the issue
