### ISSUE TITLE
NPE when save dataframe to bigquery

### ISSUE THREAD

**Issue by kaiseu** [GoogleCloudDataproc/spark-bigquery-connector#672]
when saving dataframe to bigquery table it failed with below error, the spark-bigquey-connector version used is 0.24.2.

the code snip is as below:
```
dataframe.write().mode(saveMode.getMode())
                .format(Constants.BIGQUERY)
                .option("temporaryGcsBucket", env.getGcsBucket())
                .option(Constants.TABLE, fullTableName)
                .save()
```
another questions is that we noticed there's only one active task even through we have configured many executors, while the one active task seems doing nothing for a long time before the job fail.

we will appreciate it if you have any suggestions, thanks in advance!
```
2022-06-12T05:03:22.338448 Exception in thread "main" java.lang.RuntimeException: Failed to write to BigQuery
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:59)
  at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:112)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
  at com.paypal.cipds.impl.BigQueryWriterImpl.write(BigQueryWriterImpl.java:63)
  at com.paypal.cipds.service.SinkService.write(SinkService.java:15)
  at com.paypal.cipds.spark.CloudPipeline.main(CloudPipeline.java:85)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:890)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)Caused by: java.lang.NullPointerException
  at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:532)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:87)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:66)	... 33 more 2022-06-12T05:03:22.338448 Exception in thread "main" java.lang.RuntimeException: Failed to write to BigQuery
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:59)
  at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:43)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:112)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
  at com.paypal.cipds.impl.BigQueryWriterImpl.write(BigQueryWriterImpl.java:63)
  at com.paypal.cipds.service.SinkService.write(SinkService.java:15)
  at com.paypal.cipds.spark.CloudPipeline.main(CloudPipeline.java:85)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:890)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
  at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:532)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:87)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:66)	... 33 more 
```
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/7146858/173288507-b3774166-91fc-4e76-bfdd-ef523c26ea0f.png">

the executor thread dump is as below:
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/7146858/173291210-db5a89ab-a27a-4df1-946a-6838bdff03b4.png">

**Comment by davidrabinowitz** [comment]
Can you please share the Spark version, Java version, Scala version and the connector version?

**Comment by kaiseu** [comment]
> 

the spark version is 2.3.4， java version 1.8, scala 2.11 and connector version 0.24.2

**Comment by kaiseu** [comment]
> Can you please share the Spark version, Java version, Scala version and the connector version?


the spark version is 2.3.4， java version 1.8, scala 2.11 and connector version 0.24.2

**Comment by kaiseu** [comment]
hi team, do you have any idea or suggestions on this?

**Comment by kaiseu** [comment]
thank you @suryasoma, seems 0.25.2 will have exact schema compare when saving data? e.g. TIMESTAMP can be cast to string implicitly but with exact schema compare it will fail. do we have an option that can disable it?

at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table XXXX. Field dt has changed type from TIMESTAMP to STRING

**Comment by suryasoma** [comment]
@kaiseu are you using DIRECT mode during write?

**Comment by suryasoma** [comment]
Hey @kaiseu, we have not added any new checks to compare the exact schema. Was this use case working previously?

**Comment by kaiseu** [comment]
@suryasoma I remember 0.24.2 should work. can we have an option that can skip the schema check? or can it have implicit type conversion like that in hive?

**Comment by suryasoma** [comment]
Hey @kaiseu sorry for the delay in response. Which write method are you using? and did you change the write method recently?
Also can you please attach the stack trace of the error in 0.25.2

**Comment by suryasoma** [comment]
Closing this since new issue #694  is created for this
