### ISSUE TITLE
Direct writing problem

### ISSUE THREAD

**Issue by nbulatovic** [GoogleCloudDataproc/spark-bigquery-connector#683]
Hi,

I experienced a strange behavior of the connector while I tried to write a local Spark DataFrame to BQ. 

~~~
val DF = Seq(("a","b")).toDF("col1", "col2")
{
DF.write
       .format("bigquery")
       .option("writeMethod", "direct")
       .option("credentialsFile", "path_to_cred")
       .option("proxyAddress", "our_proxy_url:port")
       .option("parentProject", "billing_project")
       .save("mydataset.mytable")
}
~~~
I got the following exception:
~~~
java.lang.IllegalArgumentException: Either temporary or persistent GCS bucket must be set
  at com.google.cloud.spark.bigquery.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
  at com.google.cloud.spark.bigquery.SparkBigQueryUtil.createGcsPath(SparkBigQueryUtil.java:83)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.<init>(BigQueryWriteHelper.scala:45)
  at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:42)
  at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:115)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:228)
  ... 57 elided
~~~

As far as I understand the docs, the direct writeMode shouln't need any GCS bucket, so I think SparkBigQueryUtil.createGcsPath mustn't be called at all. I tried to set the temp and persistent bucket option, but I've got a "No FileSystem for scheme: gs" exception, which is the same when I try with "indirect" mode, but that's another problem I guess.

I'd like to ask for your help, whether it's a bug, or I did something wrong.
Thanks you in advice!

Environment:
- spark: 2.4.0
- scala: 2.11.12 (OpenJDK 64-Bit Server VM GraalVM CE 21.1.0, Java 1.8.0_292)
- connectors: 
  spark-bigquery-with-dependencies_2.11-0.24.2.jar
  spark-bigquery-with-dependencies_2.11-0.25.1.jar
  spark-bigquery-with-dependencies_2.11-0.25.2.jar

**Comment by davidrabinowitz** [comment]
Please notice that the direct write is not supported by the spark-bigquery-with-dependencies connector. Please use the spark-2.4-bigquery connector in order to use the direct write method.
