### ISSUE TITLE
can not save dataframe to bigquery when target table column defined as not null

### ISSUE THREAD

**Issue by kaiseu** [GoogleCloudDataproc/spark-bigquery-connector#694]
when saving dataframe to bigquery table with spark bigquery connector, it throw below error:
```
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table XXXXXX. Field dt has changed mode from REQUIRED to NULLABLE
  at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:419)
  at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:252)
  at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:320)
  at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:310)
  at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:503)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:88)
  at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:67)
... 33 more 
```

the dt column in target table is defined as ' dt STRING NOT NULL' since it would always has a value, but when save a dataframe to this table, it failed with "Field dt has changed mode from REQUIRED to NULLABLE" , the schema of the dt column in dataframe is "dt: string (nullable = true) ".

what's more, when I create a dataframe directly from the target table by using 'select * from targetTable', I checked the schema, the dt column is "dt: string (nullable = true) ". 

seems spark will treat all the string column as nullable, why does the connector needs to check the nullability of the column? Do we have an option to disable the check?

the version used is:
spark 2.3.4
spark-bigquery-connector 0.25.2
java 1.8

**Comment by suryasoma** [comment]
Hey @kaiseu sorry foe the delay in response, so when you create a table with schema `dt STRING NOT NULL`, it gets created as `dt STRING REQUIRED` in BigQuery.
But the dataframe contains the column as `NULLABLE`, so that is why the error is getting created
You can create the dataframe with NULLABLE as false and the write would be successful. 
This failure was there in version 0.24.2 as well.
