### ISSUE TITLE
Unable to Direct Write to BigQuery Table from PySpark Dataframe using Dataproc Servereless

### ISSUE THREAD

**Issue by fkaminishi** [GoogleCloudDataproc/spark-bigquery-connector#797]
Details and discussions are here: `https://stackoverflow.com/questions/73995508/writing-bigquery-table-from-pyspark-dataframe-using-dataproc-servereless`

I'm running a serverless batch job in Dataproc, reading data directly from Bigquery / Cloud Storage, doing some feature engineering and persisting it on BigQuery. However in one routine I'm unable to retrieve the Dataframe and is accusing:
```
22/10/08 08:13:21 WARN BigQueryDataSourceWriterInsertableRelation: It seems that 184 out of 16 partitions have failed, aborting
22/10/08 08:13:21 WARN BigQueryDirectDataSourceWriterContext: BigQuery Data Source writer aedb4dc8-28c5-4118-9dcc-de2ef689e75c aborted
```
Not quite sure but it seems like my Spark configuration is unable to deal with the process. My config is:
```
--properties spark.executor.instances=10,spark.driver.cores=16,spark.executor.cores=16
```
My writing code:
```
user_item_interaction_df.write.format("bigquery").option("writeMethod", "direct").mode("overwrite").save()
```
BTW I'm running some Joins and Crossjoins which I know is expensive. The final output table should have something like 33M.

**Comment by fkaminishi** [comment]
Some details I've found in the logger:
```
{
  "insertId": "sjh8nomojn9i0qpc0",
  "jsonPayload": {
    "message": "com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not retrieve AppendRowsResponse\tat com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:212)\tat com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.sendAppendRowsRequest(BigQueryDirectDataWriterHelper.java:188)\tat com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.addRow(BigQueryDirectDataWriterHelper.java:169)\tat com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:86)\tat com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:35)\tat com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:61)\tat com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:33)\tat org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1(JavaRDDLike.scala:102)\tat org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1$adapted(JavaRDDLike.scala:102)\tat org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:915)\tat org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:915)\tat org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)\tat org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)\tat org.apache.spark.rdd.RDD.iterator(RDD.scala:337)\tat org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)\tat org.apache.spark.scheduler.Task.run(Task.scala:131)\tat org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)\tat org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\tat java.base/java.lang.Thread.run(Thread.java:829)Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'AppendRows throughput' quota, user_id: project00000059fdb2e211_asia-northeast1 (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description.  Entity: projects/ai-platform-dev/datasets/dataset_dev/tables/contents1_train_useritem_v1a1p1_on_20220630_created_20221007/streams/Cic2NDBhNmUyMi0wMDAwLTIxMjUtOTE3YS01ODI0MjliZDA1MTg6czk\tat com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)\tat com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:55)\tat com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:210)\t... 21 moreCaused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'AppendRows throughput' quota, user_id: project00000059fdb2e211_asia-northeast1 (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description.  Entity: projects/ai-platform-dev/datasets/dataset_dev/tables/contents1_train_useritem_v1a1p1_on_20220630_created_20221007/streams/Cic2NDBhNmUyMi0wMDAwLTIxMjUtOTE3YS01ODI0MjliZDA1MTg6czk\tat com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter.requestCallback(StreamWriter.java:629)\tat com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter.access$1100(StreamWriter.java:51)\tat com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter$2.run(StreamWriter.java:234)\tat com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamConnection$1.onResponse(StreamConnection.java:63)\tat com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamConnection$1.onResponse(StreamConnection.java:54)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.tracing.TracedResponseObserver.onResponse(TracedResponseObserver.java:90)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ExceptionResponseObserver.onResponseImpl(ExceptionResponseObserver.java:74)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.StateCheckingResponseObserver.onResponse(StateCheckingResponseObserver.java:60)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onMessage(GrpcDirectStreamController.java:134)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:661)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:646)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)\t... 3 more",
    "filename": "executor.log",
    "component": "executor"
  },
  "resource": {
    "type": "cloud_dataproc_batch",
    "labels": {
      "location": "asia-northeast1",
      "batch_id": "contents1-bandit-20221007141754"
    }
  },
  "timestamp": "2022-10-07T14:22:00.543153163Z",
  "labels": {
    "dataproc.googleapis.com/resource_name": "099ff8f5-dbb4-44f7-845a-743616ed787f-w-0"
  },  "receiveTimestamp": "2022-10-07T14:22:05.306863256Z"
}
```
```
{
  "insertId": "5j5vntpks5gla8oz7",
  "jsonPayload": {
    "class": "DataSourceWriterContextPartitionHandler",
    "filename": "executor.log",
    "message": "Encountered error writing partition 140 in task id 0 for epoch 1665152378297. Calling DataWriter.abort()",
    "component": "executor"
  },
  "resource": {
    "type": "cloud_dataproc_batch",
    "labels": {
      "location": "asia-northeast1",
      "batch_id": "contents1-bandit-20221007141754",
      "project_id": "ai-platform-dev"
    }
  },
  "timestamp": "2022-10-07T14:22:05.687473175Z",
  "severity": "WARNING",
  "labels": {
    "dataproc.googleapis.com/resource_name": "099ff8f5-dbb4-44f7-845a-743616ed787f-w-1"
  },
  "logName": "projects/ai-platform-dev/logs/dataproc.googleapis.com%2Fspark",
  "receiveTimestamp": "2022-10-07T14:22:05.687473175Z"
}
```

**Comment by medb** [comment]
Here is formatted exception from the above executor error log:
```
com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Could not retrieve AppendRowsResponse
	at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:212)
	at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.sendAppendRowsRequest(BigQueryDirectDataWriterHelper.java:188)
	at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.addRow(BigQueryDirectDataWriterHelper.java:169)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:86)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataWriterContext.write(BigQueryDirectDataWriterContext.java:35)
	at com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:61)
	at com.google.cloud.spark.bigquery.write.DataSourceWriterContextPartitionHandler.call(DataSourceWriterContextPartitionHandler.java:33)
	at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1(JavaRDDLike.scala:102)
	at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitionsWithIndex$1$adapted(JavaRDDLike.scala:102)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:915)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:915)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'AppendRows throughput' quota, user_id: project00000059fdb2e211_asia-northeast1 (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description.  Entity: projects/ai-platform-dev/datasets/dataset_dev/tables/contents1_train_useritem_v1a1p1_on_20220630_created_20221007/streams/Cic2NDBhNmUyMi0wMDAwLTIxMjUtOTE3YS01ODI0MjliZDA1MTg6czk
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:55)
	at com.google.cloud.bigquery.connector.common.BigQueryDirectDataWriterHelper.validateAppendRowsResponse(BigQueryDirectDataWriterHelper.java:210)
	... 21 moreCaused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Exceeds 'AppendRows throughput' quota, user_id: project00000059fdb2e211_asia-northeast1 (status: INSUFFICIENT_TOKENS), you can issue a raise quota request through Google Cloud Console. Be sure to include this full error message in the request description.  Entity: projects/ai-platform-dev/datasets/dataset_dev/tables/contents1_train_useritem_v1a1p1_on_20220630_created_20221007/streams/Cic2NDBhNmUyMi0wMDAwLTIxMjUtOTE3YS01ODI0MjliZDA1MTg6czk
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter.requestCallback(StreamWriter.java:629)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter.access$1100(StreamWriter.java:51)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamWriter$2.run(StreamWriter.java:234)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamConnection$1.onResponse(StreamConnection.java:63)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.StreamConnection$1.onResponse(StreamConnection.java:54)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.tracing.TracedResponseObserver.onResponse(TracedResponseObserver.java:90)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ExceptionResponseObserver.onResponseImpl(ExceptionResponseObserver.java:74)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.StateCheckingResponseObserver.onResponse(StateCheckingResponseObserver.java:60)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onMessage(GrpcDirectStreamController.java:134)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:661)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:646)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
   ```

**Comment by medb** [comment]
Judging by the error it seems like your Spark job is hitting BigQuery too hard. You can try to request more quota as suggested in the exception, alternatively you can limit scale of the job by limiting max number of executors with `spark.dynamicAllocation.maxExecutors=100` property, for example. Note that default value for this property is 1000.

**Comment by fkaminishi** [comment]
Thank you @medb! I'll give it a try for the executor and lastly increasing the quota. Let me close the issue!
