### ISSUE TITLE
Unable to write spark dataframe to new bigquery table | BigQueryDataSourceWriterInsertableRelation

### ISSUE THREAD

**Issue by hkarimi-bc** [GoogleCloudDataproc/spark-bigquery-connector#821]
In trying to write from a spark dataframe to bigquery with dataproc (image version image 2.0.45-debian10) in [direct mode](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#writing-data-to-bigquery):

```python
df.write.format("bigquery") \
    .option("writeMethod", "direct") \
    .option("project", project) \
    .save(bq_table_id)
```

I get the following error:
```
        22/11/15 19:05:46 INFO com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataSourceWriterContext: BigQuery DataSource writer c286acf6-7aa6-4a29-8b51-6f6b522ad83e committed with messages:
[]
	22/11/15 19:05:47 WARN com.google.cloud.spark.bigquery.write.BigQueryDataSourceWriterInsertableRelation: unexpected issue trying to save [dummy_col1: string, dummy_col2: bigint ... 61 more fields]
com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.InvalidArgumentException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No stream is provided. Entity: projects/dummy_project/datasets/dummy_dataset/tables/dummy_table
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:572)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:432)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:465)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryWriteClient.batchCommitWriteStreams(BigQueryWriteClient.java:637)
		at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataSourceWriterContext.commit(BigQueryDirectDataSourceWriterContext.java:193)
		at com.google.cloud.spark.bigquery.write.BigQueryDataSourceWriterInsertableRelation.insert(BigQueryDataSourceWriterInsertableRelation.java:75)
		at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createRelation(CreatableRelationProviderHelper.java:58)
		at com.google.cloud.spark.bigquery.v2.BigQueryTableProvider.createRelation(BigQueryTableProvider.java:81)
		at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
		at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
		at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
		at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
		at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
		at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
		at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
		at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
		at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
		at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
		at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
		at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
		at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
		at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
		at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
		at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
		at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
		at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
		at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:409)
		at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
		at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
		at py4j.Gateway.invoke(Gateway.java:282)
		at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
		at py4j.commands.CallCommand.execute(CallCommand.java:79)
		at py4j.GatewayConnection.run(GatewayConnection.java:238)
		... 1 more
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No stream is provided. Entity: projects/dummy_project/datasets/dummy_dataset/tables/dummy_table
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 more
22/11/15 19:05:47 WARN com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataSourceWriterContext: BigQuery Data Source writer c286acf6-7aa6-4a29-8b51-6f6b522ad83e aborted
22/11/15 19:05:47 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@98b0c24{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```

It looks like the issue is related to the partitioning clauses in BigQueryDataSourceWriterInsertableRelation here:
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/9d42fa414e60d898b60afdfb5ddd283649c5b08b/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryDataSourceWriterInsertableRelation.java#L63-L86

Open questions:
- Is there a more detailed explanation that would help me debug the issue?
- Is there an issue with the spark-bigquery writer?
- What steps are recommended to help me write the table from the spark dataframe to bigquery?

**Comment by davidrabinowitz** [comment]
Can you please share the connector and spark versions? Also, are there exceptions on the executors?

**Comment by hkarimi-bc** [comment]
Spark 3.1.3 with dataproc image version [2.0.45-debian10](https://cloud.google.com/dataproc/docs/release-notes?hl=en#July_01_2022). I'm unable to find the spark-bigquery-connector version set by this image, though I imagine it should be somewhere [around here](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0).

I don't see any failures/exceptions on the executors:
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/91922313/202689443-30ad8d1e-de49-44c6-9ef7-55aba0afe75b.png">

**Comment by hkarimi-bc** [comment]
Adding that the spark connector [version is 0.26.0](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/releases/tag/0.26.0)

**Comment by hkarimi-bc** [comment]
As we look further into this, it appears to be an issue associated with *empty* dataframes when writing with the *direct* method only. I see @davidrabinowitz has discovered something similar.

**Comment by davidrabinowitz** [comment]
PR #824 addresses that, should be released soon

**Comment by hkarimi-bc** [comment]
Great, thanks!
