### ISSUE TITLE
An error occurred while writestream to bigquery

### ISSUE THREAD

**Issue by choe09** [GoogleCloudDataproc/spark-bigquery-connector#846]
Running bigquery connector on spark3.3 in a cluster mode.

The below is being executed without any issues

df.writeStream \
    .trigger(processingTime='120 seconds') \
    .format("bigquery").outputMode("append") \
    .option("temporaryGcsBucket",xxx) \
    .option("checkpointLocation",xxx) \
    .option("table", xxx) \
    .start()

The below works fine yielding expected results

.start()

Here's the full stack trace

Py4JJavaError: An error occurred while calling o71.start.
: java.lang.UnsupportedOperationException: Data source bigquery does not support streamed writing
	at org.apache.spark.sql.errors.QueryExecutionErrors$.streamedOperatorUnsupportedByDataSourceError(QueryExecutionErrors.scala:574)
	at org.apache.spark.sql.execution.datasources.DataSource.createSink(DataSource.scala:330)
	at org.apache.spark.sql.streaming.DataStreamWriter.createV1Sink(DataStreamWriter.scala:436)
	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:400)
	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by davidrabinowitz** [comment]
Which connector are you using?

**Comment by choe09** [comment]
I used this connector: spark-3.1-bigquery-0.27.1-preview

**Comment by davidrabinowitz** [comment]
Please use spark-bigquery-with-dependencies_2.13-0.27.1 (based on the scala version)

The preview connector do not support streaming yet.
