### ISSUE TITLE
spark write fails on gcp-bq table save

### ISSUE THREAD

**Issue by vidhyaguru** [GoogleCloudDataproc/spark-bigquery-connector#901]
We have a standalone spark cluster outside of GCP. 

spark version - Spark-2.3.1.bin-hadoop2.7
  |
using library - com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.16.1

When trying to save processed data into the GCP-BQ table, getting below error on .save() 

```
/spark-2.3.1-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o62.save.
: java.lang.NoSuchMethodError: org.apache.spark.sql.SparkSession.active()Lorg/apache/spark/sql/SparkSession;
	at com.google.cloud.spark.bigquery.InjectorBuilder.<init>(InjectorBuilder.java:29)
```

This is python code I am using for write

test_count.write \
  .format("bigquery") \
  .option("writeMethod", "direct") \
  .option("parentProject", “xxxxx”) \
  #.mode("overwrite") \
  #.mode("append") \ 
  .save(“xxxx.yyyyy.test_out")

job submit string - /spark-2.3.1-bin-hadoop2.7/bin/spark-submit --packages com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.16.1 test2.py

Tried multiple options, any suggestions will help.

Thanks
Vidhya

**Comment by vidhyaguru** [comment]
Any inputs on this

**Comment by davidrabinowitz** [comment]
I would try with the com.google.cloud.spark:spark-bigquery-with-dependencies_2.11 package as Spark 2.3 does not have a scala 2.12 release. Also, can you upgrade the spark version? It is very old

**Comment by vidhyaguru** [comment]
Hi David,

Tried spark-2.3.1-bin-hadoop2.7 with com.google.cloud.spark:spark-bigquery-with-dependencies_2.11
and
tried also with spark-2.4.4-bin-hadoop2.7

Still getting same error. Read works fine, issue is with spark write. 

File "/opt/dfadmrpm/spark-2.3.1-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o61.save.


Thanks
Vidhya

**Comment by davidrabinowitz** [comment]
Can you please share the full stack trace?

**Comment by vidhyaguru** [comment]
Traceback (most recent call last):
  File "/apps/sparkadm/vtest/test2.py", line 49, in <module>
    .save("gcp-xx-nprd-xx.yy.test_out")
  File "/opt/dfadmrpm/spark-2.3.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 705, in save
  File "/opt/dfadmrpm/spark-2.3.1-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/dfadmrpm/spark-2.3.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/opt/dfadmrpm/spark-2.3.1-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o61.save.
: java.lang.NoSuchMethodError: org.apache.spark.sql.SparkSession.active()Lorg/apache/spark/sql/SparkSession;
	at com.google.cloud.spark.bigquery.InjectorBuilder.<init>(InjectorBuilder.java:29)
	at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createBigQueryInsertableRelation(CreatableRelationProviderHelper.java:85)
	at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createRelation(CreatableRelationProviderHelper.java:47)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:106)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:654)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Thanks

**Comment by davidrabinowitz** [comment]
FYI `SparkSession.active()` has been added in Spark 2.4, so it is the minimal version to run this connector.

**Comment by vidhyaguru** [comment]
Thank you, David. I got it working now with spark 2.4.4

Vidhya

**Comment by jeeva-98** [comment]
Hi,
can any of u help me in writing table from databricks to bigquery @vidhyaguru pls help me i m working mnc i will help u in future if required pls support its urgent
