### ISSUE TITLE
GRPC error reading from Spark 3.1/Dataproc 2.0-debian10

### ISSUE THREAD

**Issue by kristopherkane** [GoogleCloudDataproc/spark-bigquery-connector#908]
I upgraded our main Scala Spark project today from connector 0.24.2 to 0.28.0. We tested a couple reader/writer jobs successfully but a prod job eventually failed the following. 

The job isn't setting preferred_min_stream_count or max_stream_count. 

Environment: 

Dataproc 2.0-debian10
Scala Spark 3.1 (Dataproc runtime default) 
Java 1.8

`23/02/21 21:17:50 ERROR <omitted>: There was an error in job execution.
com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.InvalidArgumentException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: preferred_min_stream_count must be less than or equal to max_stream_count; received: 24
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.storage.v1.BigQueryReadClient.createReadSession(BigQueryReadClient.java:232)
		at com.google.cloud.bigquery.connector.common.ReadSessionCreator.create(ReadSessionCreator.java:130)
		at com.google.cloud.spark.bigquery.direct.BigQueryRDDFactory.createRddFromTable(BigQueryRDDFactory.java:138)
		at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.java:135)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$apply$4(DataSourceStrategy.scala:332)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:365)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:442)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:364)
		at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:332)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
		at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
		at scala.collection.Iterator.foreach(Iterator.scala:943)
		at scala.collection.Iterator.foreach$(Iterator.scala:943)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
		at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
		at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
		at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
		at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
		at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
		at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
		at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
		at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:392)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:104)
		at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
		at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
		at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:104)
		at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:97)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:117)
		at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
		at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
		at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:117)
		at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:110)
		at org.apache.spark.sql.execution.QueryExecution.$anonfun$simpleString$2(QueryExecution.scala:161)
		at org.apache.spark.sql.execution.ExplainUtils$.processPlan(ExplainUtils.scala:115)
		at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:161)
		at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:206)
		at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:175)
		at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
		at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
		at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
		at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
		at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
		at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3698)
		at org.apache.spark.sql.Dataset.checkpoint(Dataset.scala:689)
		at org.apache.spark.sql.Dataset.checkpoint(Dataset.scala:641)
... omitted
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: preferred_min_stream_count must be less than or equal to max_stream_count; received: 24
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:539)
	... 14 more`

**Comment by kristopherkane** [comment]
I just noticed that we also have an old dep for the bq cloud api: 

`val googleBigQueryClient = "com.google.cloud" % "google-cloud-bigquery" % "1.127.0"`

**Comment by suryasoma** [comment]
What is the value you are setting for `maxParallelism` and `preferredMinParallelism`?
Did updating the dependency work?

**Comment by kristopherkane** [comment]
For other reasons, I am not able to update `google-cloud-bigquery` to a 2.x release at this time.  

0.26.0 is working but 0.27.0 and above are not.  I'm assuming changes to bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java in the 0.27.0-0.26.0 release diff where min/max streams are determined. 

The job is only setting `maxParallelism` of `20` with no other settings for `spark.read.option()`

**Comment by suryasoma** [comment]
From this log `com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: preferred_min_stream_count must be less than or equal to max_stream_count; received: 24 at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)` looks like the min_stream_count is 24. 
Can you please retry by setting the `maxParallelism` to `24` or set `preferredMinParallelism` to `20`?

**Comment by kristopherkane** [comment]
Am I doing this to help test a future fix? 

I can see how that will fix a particular job, but is this an unintended behavior change in a minor release?  The impacts of that would be pretty wide for us.

**Comment by davidrabinowitz** [comment]
Can you please share the the cluster size and configuration, as well as the
table size (row, byte size) .  Also, a code sample would help.

Thanks!

**Comment by kristopherkane** [comment]
I finally narrowed down the problem to one table of many in the troubled job. 

Here are the table attributes: 

Number of rows: 36,410,933
Number of partitions: 924
Total logical bytes: 13.64 GB

Table Type: Partitioned
Partitioned by: Integer Range
Partitioned on field: create_date
Partition Range Start: 1041379200
Partition Range End: 1893456000
Partition Range Interval: 604800

Right or wrong, it looks like they created a seconds based partition on a full 7 day week.  

This query reproduces the problem: 

```
val sss = spark.read.option("maxParallelism", 20).bigquery(mytable).select("col1", "col2", "col3", "col4", "col5").checkpoint
sss.count()
```

`Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: preferred_min_stream_count must be less than or equal to max_stream_count; received: 60`

The query is as you see it... No filtering.  

Cluster attributes: 

Dataproc 2.0 - no extra Spark settings. 
Worker node: e2-standard-8
Master Node: e2-standard-16. 

I could reproduce this in a Dataproc 2.0 Jupyter Kernel using these Maven coordinates: 

```
%%init_spark
launcher.conf.set("spark.jars.packages", "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.27.0,com.google.cloud:google-cloud-bigquery:1.127.0")
```

**Comment by kristopherkane** [comment]
I can also reproduce this with just this Maven coordinate: 

```
%%init_spark
launcher.conf.set("spark.jars.packages", "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.27.0")
```

To rule out our dep on old com.google.cloud:google-cloud-bigquery

**Comment by davidrabinowitz** [comment]
Thanks for clearing it out. The problem is that the connector is auto configured to set the preferred minimal partitions to be 3 times the amount of executors, which usually provides the best performance. Removing the  `.option("maxParallelism", 20)` should remove that, or explicitly reducing the number of min partitions by adding `.option("preferredMinParallelism", 20)` will do the trick as well. 

Regarding the additional `google-cloud-bigquery` library - unless you explicitly invoke the BigQuery API you can remove it, the connector comes with it's own version of the library that has been tested to work well.

**Comment by davidrabinowitz** [comment]
I will fix the option parsing to address that
