### ISSUE TITLE
Cannot write partitioned table with Orc intermediete files

### ISSUE THREAD

**Issue by mathnut02** [GoogleCloudDataproc/spark-bigquery-connector#930]
I am attempting to write a table partitioned on a date field out to big query utilizing orc as an intermediate format (due to parquet creating the nested list -> element structure) utilizing spark streaming.  When attempting to load the streaming data to big query we receive the following error:
```
Caused by: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:60)
	at com.google.cloud.spark.bigquery.BigQueryStreamWriter$.writeBatch(BigQueryStreamWriter.scala:55)
	at com.google.cloud.spark.bigquery.BigQueryStreamingSink.addBatch(BigQueryStreamingSink.scala:52)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$16.apply(MicroBatchExecution.scala:496)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:494)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:493)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:151)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:139)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:139)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:139)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:135)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
	... 1 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Load configuration must specify at least one source URI
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:220)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:400)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:389)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:388)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:353)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:315)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:310)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:512)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:92)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:67)
	... 18 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/wmt-8be7d68a4811a76c70a669e205/jobs?prettyPrint=false
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Load configuration must specify at least one source URI",
    "reason" : "invalid"
  } ],
  "message" : "Load configuration must specify at least one source URI",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:218)
	... 30 more
```

Here is the code that is doing the streaming write:
```
                df.writeStream
                  .option("intermediateFormat","orc")
                  .format("bigquery")
                  .trigger(Trigger.ProcessingTime(s"300 seconds"))
                  .option("partitionField", "adj_date")
                  .option("partitionType", "DAY")
                  .partitionBy("adj_date")
                  .outputMode("append")
                  .option("temporaryGcsBucket",gcsTemporaryBucket)
                  .option("checkpointLocation",s"gs://${checkPointPath}")
                  .option("project", "test-project")
                  .option("dataset", x.bq_table_dataset)
                  .option("table", s"${bqTable}")
                  .start()
```
I've tried changing around the partionBy, partitionField, and partitionType in several different permutations, but when processing with Orc (or Avro) I receive the same big query error.  If we process with parquet, the error doesn't occur but the list structure occurs.

**Comment by davidrabinowitz** [comment]
Is it possible there were no records to write in this window?

Also, there are two additional solutions for writing arrays:
* Use the PARQUET intermediate format, and set the `enableListInference` option to `true`
* Use the AVRO  intermediate format, this will require to add the spark-avro jar to the classpath (by adding it to `spark.jars` or `spark.jars.packages`)

**Comment by mathnut02** [comment]
For the first question, I know that there werr unread messages on the Kafka topic that this is coming from for the consumer group that it is running under. 

We tried the Avro option as well and it generated the same error as the orc format. 

I will attempt the enableListInference with Parquet after I return from lunch.

**Comment by mathnut02** [comment]
So, to ensure that we weren’t just reading and then immedietly trying to read again I jacked the processing timer to 10 minutes and the error came relatively soon after starting the stream.

**Comment by davidrabinowitz** [comment]
I have a feeling that the window is empty hence there are no files for the Load job. Can you please verify that by temporarily streaming to another GCS location and  see if how often files are written? 

Regardless, we will fix the connector to skip empty load jobs.

**Comment by mathnut02** [comment]
Thank you. I greatly appreciate the prompt follow up and suggestions.

**Comment by TheTravellingSalesman** [comment]
Having a similar issue using Avro, but no error thrown, just no data ending up in the table.

```
df.write.format("bigquery").option(
        "temporaryGcsBucket", temporary_gcs_bucket
    ).option(
        "intermediateFormat", "avro"
    ).option(
        "useAvroLogicalTypes", True
    ).option(
        "partitionField", "param_end_date"
    ).option(
        # 90 days by default -- this will not overwrite the expiry policy for existing tables
        "partitionExpirationMs",
        7776000000,
    ).option(
        "table", bq_output_location
    ).mode(
        "overwrite"
    ).save()
```

Double checked that `df` contains data at this point in the processing, but yeah, after running for 45m I end up with a newly created table at `bq_output_location` (if it didn't already exist) and it's totally empty.

A bit in the weeds, but this only happens from dataproc (serverless and otherwise). Other test runs from local using samples of the same data work just fine.

**Comment by mathnut02** [comment]
I am using the latest as found in the global GCS bucket. I’ve gotten the parquet to work now with the above mentioned flags. On Apr 11, 2023, at 6:33 PM, suryasoma ***@***.***> wrote:﻿
Hey @mathnut02, which version of connector are you using? If not the latest can you please retry with the latest one?
Thanks

**Comment by suryasoma** [comment]
Can you please send the entire log and also the code which was causing this.
Thanks
