### ISSUE TITLE
Multiple sources found for bigquery

### ISSUE THREAD

**Issue by wangyu0305** [GoogleCloudDataproc/spark-bigquery-connector#949]
When loading data from bigquery with spark 3, bigquery connector 0.30.0, I got this issue
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: 
Multiple sources found for bigquery (com.google.cloud.spark.bigquery.BigQueryRelationProvider, com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider),
 please specify the fully qualified class name.

Here's dependency package 
google-cloud-bigquery==3.9.0
google-cloud-bigquery-storage==2.19.1
google-cloud-storage==2.8.0
numpy==1.21.0
python-dateutil==2.8.2
pytz==2020.1
requests==2.26.0
pandas==1.5.2
retrying==1.3.3
setuptools!=50.0.0
google-cloud-aiplatform==1.23.0

I tried to specify the provider but still no luck
I tried this:
spark.read.format("bigquery") \
        .option("query", query) \
        .option("provider", "com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2") \
        .load()
and this:
spark.read.format("bigquery") \
        .option("query", query) \
        .option("provider", "com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider") \
        .load()

Can someone please take a look?

**Comment by davidrabinowitz** [comment]
Are you using Dataproc serverless? Can you please share the Dataproc version you are using? 

Dataproc serverless arrives with spark-bigquery-with-dependnecies_2.12-0.28.1 in the runtime. If you want to use the v2 connector, please update your code as follows (assuming you have added spark-3.3-bigquery to the `spark.jars` configuration):
```
spark.read.format("com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider")
.option("query", query)
.load()
```

**Comment by wangyu0305** [comment]
I'm using dataproc 2.1, [2.1-debian11](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.1) https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.1

**Comment by davidrabinowitz** [comment]
It comes with a spark-bigquery-with-dependnecies_2.12 connector as well. My recommendation still holds for this  case

**Comment by wangyu0305** [comment]
I have spark.yarn.secondary.jars=spark-3.3-bigquery-0.30.0.jar in my spark config.

Just tried 
spark.read.format("com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider")
.option("query", query)
.load()

 but got another error : java.lang.NoSuchMethodError: 'java.time.ZoneId com.google.cloud.spark.bigquery.SparkBigQueryConfig.getDatetimeZoneId()'

full logs:
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o301.load.
: java.lang.NoSuchMethodError: 'java.time.ZoneId com.google.cloud.spark.bigquery.SparkBigQueryConfig.getDatetimeZoneId()'
	at com.google.cloud.spark.bigquery.SchemaConvertersConfiguration.from(SchemaConvertersConfiguration.java:32)
	at com.google.cloud.spark.bigquery.v2.Spark3Util.createBigQueryTableInstance(Spark3Util.java:52)
	at com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider.getBigQueryTableInternal(Spark33BigQueryTableProvider.java:33)
	at com.google.cloud.spark.bigquery.v2.Spark31BigQueryTableProvider.inferSchema(Spark31BigQueryTableProvider.java:40)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:90)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.loadV2Source(DataSourceV2Utils.scala:132)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:209)
	at scala.Option.flatMap(Option.scala:271)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:207)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by wangyu0305** [comment]
Hi @davidrabinowitz can you help me on this issue?  
I downloaded this jar [spark-3.3-bigquery-0.30.0.jar](gs://spark-lib/bigquery/spark-3.3-bigquery-0.30.0.jar), I can see the method is there, not sure why this happened.

**Comment by davidrabinowitz** [comment]
Checking

**Comment by davidrabinowitz** [comment]
There may be a conflict between the two versions of the connector. Two possible solutions are:

1. Add the following Spark configuration: `spark.driver.userClassPathFirst=true` `spark.executor.userClassPathFirst=true`  
2. Alternatively, remove the built in connector by creating the cluster with the following init action:
```
#!/bin/sh

JARS=$(find /usr -name spark\*bigquery\*jar)

ls -l $JARS
rm -f $JARS
```

**Comment by wangyu0305** [comment]
Thanks so much David, the issue resolved by removing the built in connector.
