### ISSUE TITLE
`spark-bigquery` connector isn't working in the `Jupyter Notebooks` created in `Vertex AI workbench`

### ISSUE THREAD

**Issue by gomrinal** [GoogleCloudDataproc/spark-bigquery-connector#963]
I tried almost all the approaches listed by people but nothing seems to work.

I am getting this error in jupyter notebook created via `Vertex AI workbench` which ideally should have been optimized for the libraries.

Error:
```
Py4JJavaError: An error occurred while calling o76.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:678)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:213)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:652)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:652)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:652)
	... 13 more

```

Approaches tried:
1.
```python
spark = SparkSession.builder \
  .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar') \
  .getOrCreate()

natality_data = spark.read.format("bigquery").option("table", "natality_regression.regression_input").load()
```

2.
```python
spark = SparkSession.builder \
  .appName('Optimize BigQuery Storage') \
  .config('spark.jars.packages', 'com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.24.2') \
  .getOrCreate()

natality_data = spark.read.format("bigquery").option("table", "natality_regression.regression_input").load()
```

**Comment by gomrinal** [comment]
So, it worked for me after lot of trial and testing different versions of connector.

My spark version in the jupyter notebook was: 

```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.8
      /_/
                        
Using Scala version 2.12.10, OpenJDK 64-Bit Server VM, 1.8.0_362
Branch 
Compiled by user  on 2023-04-17T15:42:10Z
Revision 
Url 
Type --help for more information.
```

I tried using the latest version of the `spark-bigquery` connector which was `gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar`  and it worked!

**Comment by gomrinal** [comment]
Working snippet of code looks like this:

```python
from pyspark.sql import SparkSession
spark = SparkSession.builder \
  .appName('1.2. BigQuery Storage & Spark SQL - Python')\
  .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar') \
  .getOrCreate()

df = (
    spark.read.format("bigquery")
    .option("table", "natality_regression.regression_input")
    .load()
)
```

**Comment by gomrinal** [comment]
Well looking further into it. I found that issue isn't the version of connector but the kernel.

In order to make connector work, One needs to use `Python` as the kernel instead of `pyspark`
