### ISSUE TITLE
Spark Structured Streaming Query is failing with the following stracktrace

### ISSUE THREAD

**Issue by nishant-neo** [GoogleCloudDataproc/spark-bigquery-connector#967]
I have written a Spark Structured Streaming(SS) Query

which triggers from a Kafka Queue and is enriched by a bigquery lookup, this job runs fine for hours but eventually in a few hours / days exits with this stacktrace

Using

> Scala version 2.12.14

> Spark 3.3.0

> gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.28.0.jar`

```
Caused by: java.lang.NullPointerException
  at com.google.cloud.bigquery.connector.common.ReadSessionCreator.getActualTable(ReadSessionCreator.java:173)
  at com.google.cloud.bigquery.connector.common.ReadSessionCreator.getActualTable(ReadSessionCreator.java:168)
  at com.google.cloud.bigquery.connector.common.ReadSessionCreator.create(ReadSessionCreator.java:72)
  at com.google.cloud.spark.bigquery.direct.BigQueryRDDFactory.createRddFromTable(BigQueryRDDFactory.java:134)
  at com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation.buildScan(DirectBigQueryRelation.java:130)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$apply$4(DataSourceStrategy.scala:328)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:362)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:418)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:361)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:328)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
  at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:75)
  at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:69)
  at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:461)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:145)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
  at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:512)
  ... 32 more
"}```

**Comment by davidrabinowitz** [comment]
Are you trying to read from a view or form a query? Also, in general the ReadSession behind the table lives for about 6 hours so it may explain the issue you are facing. 

Please cache the data on spark or refresh the read every few hours.

**Comment by nishant-neo** [comment]
> Are you trying to read from a view or form a query?

I am reading like this

`sql = """SELECT a, b,  TO_JSON_STRING(c) AS c
  FROM X.Y as XY
  INNER JOIN X.Z as XZ
  ON XY.a = XZ.a """`


`dataread = spark.read.format("bigquery").load(sql)`

> Please cache the data on spark or refresh the read every few hours.

Since I need the latest snapshot, cache won't be an option, and also its streaming job that is supposed to run indefinitely, job will not be refreshed.

**Comment by isha97** [comment]
A read session is only valid for 6 hrs, so you can't use this to read data which takes more time than that.

**Comment by isha97** [comment]
@nishant-neo Please try with the latest version of the connector `0.37.0.` which has multiple fixes and let us know if you still face this issue.
