### ISSUE TITLE
Nested array column causes error "Data type not expected: array<string>"

### ISSUE THREAD

**Issue by khaledh** [GoogleCloudDataproc/spark-bigquery-connector#987]
Using connector version 0.30.0 with Spark 3.3.0 on Dataproc:

```python
df = spark.createDataFrame([
    {'id': 1, 'value': [['a', 'b'], ['c', 'd']]},
    {'id': 2, 'value': [['e', 'f'], ['g', 'h']]},
])

df.printSchema()
# root
# |-- id: long (nullable = true)
# |-- value: array (nullable = true)
# |    |-- element: array (containsNull = true)
# |    |    |-- element: string (containsNull = true)

df.write \
  .format("bigquery") \
  .option("writeMethod", "direct") \
  .save("dataset.table")
```

```
java.lang.IllegalArgumentException: Data type not expected: array<string>
	at com.google.cloud.spark.bigquery.SchemaConverters.toBigQueryType(SchemaConverters.java:515)
	at com.google.cloud.spark.bigquery.SchemaConverters.createBigQueryColumn(SchemaConverters.java:455)
	at com.google.cloud.spark.bigquery.SchemaConverters.sparkToBigQueryFields(SchemaConverters.java:406)
	at com.google.cloud.spark.bigquery.SchemaConverters.toBigQuerySchema(SchemaConverters.java:394)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDirectDataSourceWriterContext.<init>(BigQueryDirectDataSourceWriterContext.java:102)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDataSourceWriterModule.provideDirectDataSourceWriterContext(BigQueryDataSourceWriterModule.java:76)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDataSourceWriterModule$$FastClassByGuice$$3635994.GUICE$TRAMPOLINE(<generated>)
	at com.google.cloud.spark.bigquery.write.context.BigQueryDataSourceWriterModule$$FastClassByGuice$$3635994.apply(<generated>)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)
```

I believe the issue around [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/50d62dc902380e29dee4227fac9c1aafb3fc5c56/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java#L422-L427). It looks like `createBigQueryColumn` unwraps the outer array type, and proceeds to call `toBigQueryType` on the array element type, which in this case is another array type, but `toBigQueryType` assumes the incoming type is a simple type, hence the error `Data type not expected: array<string>`.

**Comment by khaledh** [comment]
I actually realized that nested arrays are [not allowed](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_type) in BigQuery:

>  ARRAY | Ordered list of zero or more elements of any non-array type.
>
> Arrays of arrays are not allowed.

We'll find another way to store this data. Sorry for the false alarm.
