### ISSUE TITLE
Indirect writer does not respect `gcpImpersonationServiceAccount` option

### ISSUE THREAD

**Issue by pPanda-beta** [GoogleCloudDataproc/spark-bigquery-connector#995]
It seems the SA impersonation  setting is not getting injected to the underlying gcs-hadoop-connector. 

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/31bb0f74978c9a588a3a9d0b27a968f7e73d1d66/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectDataWriterContextFactory.java#L53-L56

I tried the following things. (in pyspark, bigquery spark connection + bigquery store procedure with pyspark code)
1. Setting `gcpImpersonationServiceAccount` 
    - Spark config in spark session builder
        -  `.config("gcpImpersonationServiceAccount", "...")`
        -  `.config("org.apache.spark.sql.bigquery.gcpImpersonationServiceAccount", "...")`
        - `.config("spark.hadoop.fs.gs.auth.type", "ACCESS_TOKEN_PROVIDER")` + `.config("spark.hadoop.fs.gs.auth.impersonation.service.account", "...")` - This one actually works for direct gcs based read/write. I have tested this separately.
    - Hadoop config after build spark session `spark.sparkContext._jsc.hadoopConfiguration().set("fs.gs.auth.impersonation.service.account", "...")`
    - Data source option 
    ```
          .option("writeMethod", "indirect")
          .option("temporaryGcsBucket", "...")
          .option('gcpImpersonationServiceAccount', "...")
    ```

None of these actually worked.

Error stacktrace:

```
23/06/12 12:03:52 INFO BigQueryClient: Submitted job LoadJobConfiguration{type=LOAD, destinationTable=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=analysis, projectId=..., tableId=...}}, decimalTargetTypes=null, destinationEncryptionConfiguration=null, createDisposition=CREATE_IF_NEEDED, writeDisposition=WRITE_TRUNCATE, formatOptions=FormatOptions{format=PARQUET}, nullMarker=null, maxBadRecords=null, schema=null, ignoreUnknownValue=null, sourceUris=[gs://<...>/.spark-bigquery-app-20230612120030-0000-a25f10ec-41d9-4a19-9da5-8322e9ad2c2c/part-01361-a4a22240-9303-4e1e-901b-784b7caa59a6-c000.snappy.parquet, gs://<...>/.spark-bigquery-app-20230612120030-0000-a25f10ec-41d9-4a19-9da5-8322e9ad2c2c/part-00000-a4a22240-9303-4e1e-901b-784b7caa59a6-c000.snappy.parquet], schemaUpdateOptions=null, autodetect=true, timePartitioning=null, clustering=null, useAvroLogicalTypes=null, labels=null, jobTimeoutMs=null, rangePartitioning=null, hivePartitioningOptions=null, referenceFileSchemaUri=null}. jobId: JobId{project=..., job=d6775ed9-bb35-424f-b385-db01b5d6f7b8, location=US}
23/06/12 12:03:52 ERROR BigQueryClient: Unable to create the job to load to ...
Traceback (most recent call last):
  File "/var/dataproc/tmp/srvls-batch-4ce704f8-bf92-4336-b61e-6fab3c8f9fec/script-job-0f3df227f3218c156b790a7017a13a3b-1.py", line 155, in <module>
    main()
  File "/var/dataproc/tmp/srvls-batch-4ce704f8-bf92-4336-b61e-6fab3c8f9fec/script-job-0f3df227f3218c156b790a7017a13a3b-1.py", line 151, in main
    save_output_df(output_df)
  File "/var/dataproc/tmp/srvls-batch-4ce704f8-bf92-4336-b61e-6fab3c8f9fec/script-job-0f3df227f3218c156b790a7017a13a3b-1.py", line 140, in save_output_df
    .save()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 966, in save
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o160.save.
: com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.write.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.java:110)
	at com.google.cloud.spark.bigquery.write.BigQueryDeprecatedIndirectInsertableRelation.insert(BigQueryDeprecatedIndirectInsertableRelation.java:43)
	at com.google.cloud.spark.bigquery.write.CreatableRelationProviderHelper.createRelation(CreatableRelationProviderHelper.java:54)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:106)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:47)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Access Denied: File gs://<.....>/.spark-bigquery-app-20230612120030-0000-a25f10ec-41d9-4a19-9da5-8322e9ad2c2c/part-01361-a4a22240-9303-4e1e-901b-784b7caa59a6-c000.snappy.parquet: Access Denied
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.reload(Job.java:419)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.Job.waitFor(Job.java:252)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:333)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.createAndWaitFor(BigQueryClient.java:323)
	at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:553)
	at com.google.cloud.spark.bigquery.write.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.java:130)
	at com.google.cloud.spark.bigquery.write.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.java:107)
	... 44 more
```

**Comment by suryasoma** [comment]
Hey, from the exception
```
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Access Denied: File gs://<.....>/.spark-bigquery-app-20230612120030-0000-a25f10ec-41d9-4a19-9da5-8322e9ad2c2c/part-01361-a4a22240-9303-4e1e-901b-784b7caa59a6-c000.snappy.parquet: Access Denied
```
 it looks like the application does not have permissions for the GCS bucket passed as part of `temporaryGcsBucket` option.

**Comment by pPanda-beta** [comment]
@suryasoma The service account I'm delegating to has the permission. 

I double checked this by giving permissions to the current job's service account (bigquery spark connection's SA). Everything ran fine. 

So this indicates SA delegation is not working.

**Comment by pPanda-beta** [comment]
My bad it worked after changing the jar to `gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.13-0.31.1.jar` (using spark.jars).

Bigquery pyspark connection uses `spark-bigquery-with-dependencies_2.13-0.27.1.jar` which does not have the changes from May 2023. 

Both of the following worked independently. 
- Spark config in spark session builder
    -  `.config("gcpImpersonationServiceAccount", "...")`
- Data source option 
```
      .option("writeMethod", "indirect")
      .option("temporaryGcsBucket", "...")
      .option('gcpImpersonationServiceAccount', "...")
```


It is surprising that `.config("org.apache.spark.sql.bigquery.gcpImpersonationServiceAccount", "...")` or `.config("spark.sql.bigquery.gcpImpersonationServiceAccount", "...")` did not work which is a common way of setting global options for spark datasource v2.

**Comment by suryasoma** [comment]
Could you try by setting the config as `.config("spark.datasource.bigquery.gcpImpersonationServiceAccount", "...")` instead.

**Comment by pPanda-beta** [comment]
We are continuing to use `spark-bigquery-with-dependencies_2.13-0.31.1.jar` (will remove this once Bigquery pyspark connection updates this dep)  with `.config("gcpImpersonationServiceAccount", "...")`.  Things are working in this version.
